// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Details of the final state "abort" and associated resource.
public struct AbortInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Causes that the analysis is aborted.
  public var cause: AbortInfo.Cause = AbortInfo.Cause()

  /// URI of the resource that caused the abort.
  public var resourceUri: Swift.String = Swift.String()

  /// IP address that caused the abort.
  public var ipAddress: Swift.String = Swift.String()

  /// List of project IDs the user specified in the request but lacks access to.
  /// In this case, analysis is aborted with the PERMISSION_DENIED cause.
  public var projectsMissingPermission: [Swift.String] = []

  /// Initialize a new instance of `AbortInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AbortInfo().with { $0.cause = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Abort cause types:
  public enum Cause: Codable, Equatable, Sendable {
    /// Cause is unspecified.
    case unspecified
    /// Aborted due to unknown network. Deprecated, not used in the new tests.
    @available(*, deprecated)
    case unknownNetwork
    /// Aborted because no endpoint with the packet's destination IP address is
    /// found.
    case unknownIp
    /// Aborted because no project information can be derived from the test
    /// input. Deprecated, not used in the new tests.
    @available(*, deprecated)
    case unknownProject
    /// Aborted because user lacks permission to access all or part of the
    /// network configurations required to run the test.
    case permissionDenied
    /// Aborted because no valid source or destination endpoint can be derived
    /// from the test request.
    case noSourceLocation
    /// Aborted because the source or destination endpoint specified in
    /// the request is invalid. Some examples:
    /// - The request might contain malformed resource URI, project ID, or IP
    /// address.
    /// - The request might contain inconsistent information (for example, the
    /// request might include both the instance and the network, but the instance
    /// might not have a NIC in that network).
    case invalidArgument
    /// Aborted because traffic is sent from a public IP to an instance without
    /// an external IP. Deprecated, not used in the new tests.
    @available(*, deprecated)
    case noExternalIp
    /// Aborted because none of the traces matches destination information
    /// specified in the input test request. Deprecated, not used in the new
    /// tests.
    @available(*, deprecated)
    case unintendedDestination
    /// Aborted because the number of steps in the trace exceeds a certain
    /// limit. It might be caused by a routing loop.
    case traceTooLong
    /// Aborted due to internal server error.
    case internalError
    /// Aborted because the source endpoint could not be found. Deprecated, not
    /// used in the new tests.
    @available(*, deprecated)
    case sourceEndpointNotFound
    /// Aborted because the source network does not match the source endpoint.
    /// Deprecated, not used in the new tests.
    @available(*, deprecated)
    case mismatchedSourceNetwork
    /// Aborted because the destination endpoint could not be found. Deprecated,
    /// not used in the new tests.
    @available(*, deprecated)
    case destinationEndpointNotFound
    /// Aborted because the destination network does not match the destination
    /// endpoint. Deprecated, not used in the new tests.
    @available(*, deprecated)
    case mismatchedDestinationNetwork
    /// Aborted because the test scenario is not supported.
    case unsupported
    /// Aborted because the source and destination resources have no common IP
    /// version.
    case mismatchedIpVersion
    /// Aborted because the connection between the control plane and the node of
    /// the source cluster is initiated by the node and managed by the
    /// Konnectivity proxy.
    case gkeKonnectivityProxyUnsupported
    /// Aborted because expected resource configuration was missing.
    case resourceConfigNotFound
    /// Aborted because PSC endpoint selection for the Google-managed service
    /// is ambiguous (several PSC endpoints satisfy test input).
    case googleManagedServiceAmbiguousPscEndpoint
    /// Aborted because tests with a PSC-based Cloud SQL instance as a source are
    /// not supported.
    case sourcePscCloudSqlUnsupported
    /// Aborted because tests with a forwarding rule as a source are not
    /// supported.
    case sourceForwardingRuleUnsupported
    /// Aborted because one of the endpoints is a non-routable IP address
    /// (loopback, link-local, etc).
    case nonRoutableIpAddress
    /// Aborted because the source IP address doesn't belong to any of the
    /// subnets of the source VPC network.
    case sourceIpAddressNotInSourceNetwork
    /// Aborted because expected VM instance configuration was missing.
    case vmInstanceConfigNotFound
    /// Aborted because expected network configuration was missing.
    case networkConfigNotFound
    /// Aborted because expected firewall configuration was missing.
    case firewallConfigNotFound
    /// Aborted because expected route configuration was missing.
    case routeConfigNotFound
    /// Aborted because user lacks permission to access Cloud NAT configs
    /// required to run the test.
    case permissionDeniedNoCloudNatConfigs
    /// Aborted because user lacks permission to access Network endpoint group
    /// endpoint configs required to run the test.
    case permissionDeniedNoNegEndpointConfigs
    /// Aborted due to an unknown issue in the Google-managed project.
    case unknownIssueInGoogleManagedProject
    /// Aborted due to an unsupported configuration of the Google-managed
    /// project.
    case unsupportedGoogleManagedProjectConfig
    /// Aborted because no endpoint with the packet's destination IP is found in
    /// the Google-managed project.
    case googleManagedServiceUnknownIp
    /// Aborted because tests with a Redis Cluster as a source are not supported.
    case sourceRedisClusterUnsupported
    /// Aborted because tests with a Redis Instance as a source are not
    /// supported.
    case sourceRedisInstanceUnsupported
    /// Aborted because user lacks permission to access Cloud Router configs
    /// required to run the test.
    case permissionDeniedNoCloudRouterConfigs
    /// Aborted because the source endpoint is a Cloud Run revision with direct
    /// VPC access enabled, but there are no reserved serverless IP ranges.
    case noServerlessIpRanges
    /// Aborted because endpoint selection for the Google-managed service is
    /// ambiguous (several endpoints satisfy test input).
    case googleManagedServiceAmbiguousEndpoint
    /// Aborted because the used protocol is not supported for the used IP
    /// version.
    case ipVersionProtocolMismatch
    /// Aborted because selected GKE Pod endpoint location is unknown. This is
    /// often the case for "Pending" Pods, which don't have assigned IP addresses
    /// yet.
    case gkePodUnknownEndpointLocation
    /// Aborted because the source IP address is not contained within the subnet
    /// ranges of the provided VPC network.
    case noSourceGcpNetworkLocation
    /// Aborted because the source IP address is not contained within the
    /// destination ranges of the routes towards non-GCP networks in the provided
    /// VPC network.
    case noSourceNonGcpNetworkLocation
    /// Aborted because the source IP address can't be resolved as an Internet
    /// IP address.
    case noSourceInternetLocation
    /// Aborted because tests with the external database as a source are not
    /// supported. In such replication scenarios, the connection is initiated by
    /// the Cloud SQL replica instance.
    case sourceExternalCloudSqlUnsupported
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .unknownNetwork: return 1
      case .unknownIp: return 2
      case .unknownProject: return 3
      case .permissionDenied: return 4
      case .noSourceLocation: return 5
      case .invalidArgument: return 6
      case .noExternalIp: return 7
      case .unintendedDestination: return 8
      case .traceTooLong: return 9
      case .internalError: return 10
      case .sourceEndpointNotFound: return 11
      case .mismatchedSourceNetwork: return 12
      case .destinationEndpointNotFound: return 13
      case .mismatchedDestinationNetwork: return 14
      case .unsupported: return 15
      case .mismatchedIpVersion: return 16
      case .gkeKonnectivityProxyUnsupported: return 17
      case .resourceConfigNotFound: return 18
      case .googleManagedServiceAmbiguousPscEndpoint: return 19
      case .sourcePscCloudSqlUnsupported: return 20
      case .sourceForwardingRuleUnsupported: return 21
      case .nonRoutableIpAddress: return 22
      case .sourceIpAddressNotInSourceNetwork: return 23
      case .vmInstanceConfigNotFound: return 24
      case .networkConfigNotFound: return 25
      case .firewallConfigNotFound: return 26
      case .routeConfigNotFound: return 27
      case .permissionDeniedNoCloudNatConfigs: return 28
      case .permissionDeniedNoNegEndpointConfigs: return 29
      case .unknownIssueInGoogleManagedProject: return 30
      case .unsupportedGoogleManagedProjectConfig: return 31
      case .googleManagedServiceUnknownIp: return 32
      case .sourceRedisClusterUnsupported: return 34
      case .sourceRedisInstanceUnsupported: return 35
      case .permissionDeniedNoCloudRouterConfigs: return 36
      case .noServerlessIpRanges: return 37
      case .googleManagedServiceAmbiguousEndpoint: return 39
      case .ipVersionProtocolMismatch: return 40
      case .gkePodUnknownEndpointLocation: return 41
      case .noSourceGcpNetworkLocation: return 42
      case .noSourceNonGcpNetworkLocation: return 43
      case .noSourceInternetLocation: return 44
      case .sourceExternalCloudSqlUnsupported: return 45
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CAUSE_UNSPECIFIED"
      case .unknownNetwork: return "UNKNOWN_NETWORK"
      case .unknownIp: return "UNKNOWN_IP"
      case .unknownProject: return "UNKNOWN_PROJECT"
      case .permissionDenied: return "PERMISSION_DENIED"
      case .noSourceLocation: return "NO_SOURCE_LOCATION"
      case .invalidArgument: return "INVALID_ARGUMENT"
      case .noExternalIp: return "NO_EXTERNAL_IP"
      case .unintendedDestination: return "UNINTENDED_DESTINATION"
      case .traceTooLong: return "TRACE_TOO_LONG"
      case .internalError: return "INTERNAL_ERROR"
      case .sourceEndpointNotFound: return "SOURCE_ENDPOINT_NOT_FOUND"
      case .mismatchedSourceNetwork: return "MISMATCHED_SOURCE_NETWORK"
      case .destinationEndpointNotFound: return "DESTINATION_ENDPOINT_NOT_FOUND"
      case .mismatchedDestinationNetwork: return "MISMATCHED_DESTINATION_NETWORK"
      case .unsupported: return "UNSUPPORTED"
      case .mismatchedIpVersion: return "MISMATCHED_IP_VERSION"
      case .gkeKonnectivityProxyUnsupported: return "GKE_KONNECTIVITY_PROXY_UNSUPPORTED"
      case .resourceConfigNotFound: return "RESOURCE_CONFIG_NOT_FOUND"
      case .googleManagedServiceAmbiguousPscEndpoint:
        return "GOOGLE_MANAGED_SERVICE_AMBIGUOUS_PSC_ENDPOINT"
      case .sourcePscCloudSqlUnsupported: return "SOURCE_PSC_CLOUD_SQL_UNSUPPORTED"
      case .sourceForwardingRuleUnsupported: return "SOURCE_FORWARDING_RULE_UNSUPPORTED"
      case .nonRoutableIpAddress: return "NON_ROUTABLE_IP_ADDRESS"
      case .sourceIpAddressNotInSourceNetwork: return "SOURCE_IP_ADDRESS_NOT_IN_SOURCE_NETWORK"
      case .vmInstanceConfigNotFound: return "VM_INSTANCE_CONFIG_NOT_FOUND"
      case .networkConfigNotFound: return "NETWORK_CONFIG_NOT_FOUND"
      case .firewallConfigNotFound: return "FIREWALL_CONFIG_NOT_FOUND"
      case .routeConfigNotFound: return "ROUTE_CONFIG_NOT_FOUND"
      case .permissionDeniedNoCloudNatConfigs: return "PERMISSION_DENIED_NO_CLOUD_NAT_CONFIGS"
      case .permissionDeniedNoNegEndpointConfigs: return "PERMISSION_DENIED_NO_NEG_ENDPOINT_CONFIGS"
      case .unknownIssueInGoogleManagedProject: return "UNKNOWN_ISSUE_IN_GOOGLE_MANAGED_PROJECT"
      case .unsupportedGoogleManagedProjectConfig:
        return "UNSUPPORTED_GOOGLE_MANAGED_PROJECT_CONFIG"
      case .googleManagedServiceUnknownIp: return "GOOGLE_MANAGED_SERVICE_UNKNOWN_IP"
      case .sourceRedisClusterUnsupported: return "SOURCE_REDIS_CLUSTER_UNSUPPORTED"
      case .sourceRedisInstanceUnsupported: return "SOURCE_REDIS_INSTANCE_UNSUPPORTED"
      case .permissionDeniedNoCloudRouterConfigs: return "PERMISSION_DENIED_NO_CLOUD_ROUTER_CONFIGS"
      case .noServerlessIpRanges: return "NO_SERVERLESS_IP_RANGES"
      case .googleManagedServiceAmbiguousEndpoint:
        return "GOOGLE_MANAGED_SERVICE_AMBIGUOUS_ENDPOINT"
      case .ipVersionProtocolMismatch: return "IP_VERSION_PROTOCOL_MISMATCH"
      case .gkePodUnknownEndpointLocation: return "GKE_POD_UNKNOWN_ENDPOINT_LOCATION"
      case .noSourceGcpNetworkLocation: return "NO_SOURCE_GCP_NETWORK_LOCATION"
      case .noSourceNonGcpNetworkLocation: return "NO_SOURCE_NON_GCP_NETWORK_LOCATION"
      case .noSourceInternetLocation: return "NO_SOURCE_INTERNET_LOCATION"
      case .sourceExternalCloudSqlUnsupported: return "SOURCE_EXTERNAL_CLOUD_SQL_UNSUPPORTED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Cause/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CAUSE_UNSPECIFIED": self = .unspecified
      case "UNKNOWN_NETWORK": self = .unknownNetwork
      case "UNKNOWN_PROJECT": self = .unknownProject
      case "NO_EXTERNAL_IP": self = .noExternalIp
      case "UNINTENDED_DESTINATION": self = .unintendedDestination
      case "SOURCE_ENDPOINT_NOT_FOUND": self = .sourceEndpointNotFound
      case "MISMATCHED_SOURCE_NETWORK": self = .mismatchedSourceNetwork
      case "DESTINATION_ENDPOINT_NOT_FOUND": self = .destinationEndpointNotFound
      case "MISMATCHED_DESTINATION_NETWORK": self = .mismatchedDestinationNetwork
      case "UNKNOWN_IP": self = .unknownIp
      case "GOOGLE_MANAGED_SERVICE_UNKNOWN_IP": self = .googleManagedServiceUnknownIp
      case "SOURCE_IP_ADDRESS_NOT_IN_SOURCE_NETWORK": self = .sourceIpAddressNotInSourceNetwork
      case "PERMISSION_DENIED": self = .permissionDenied
      case "PERMISSION_DENIED_NO_CLOUD_NAT_CONFIGS": self = .permissionDeniedNoCloudNatConfigs
      case "PERMISSION_DENIED_NO_NEG_ENDPOINT_CONFIGS": self = .permissionDeniedNoNegEndpointConfigs
      case "PERMISSION_DENIED_NO_CLOUD_ROUTER_CONFIGS": self = .permissionDeniedNoCloudRouterConfigs
      case "NO_SOURCE_LOCATION": self = .noSourceLocation
      case "NO_SOURCE_GCP_NETWORK_LOCATION": self = .noSourceGcpNetworkLocation
      case "NO_SOURCE_NON_GCP_NETWORK_LOCATION": self = .noSourceNonGcpNetworkLocation
      case "NO_SOURCE_INTERNET_LOCATION": self = .noSourceInternetLocation
      case "INVALID_ARGUMENT": self = .invalidArgument
      case "TRACE_TOO_LONG": self = .traceTooLong
      case "INTERNAL_ERROR": self = .internalError
      case "UNSUPPORTED": self = .unsupported
      case "MISMATCHED_IP_VERSION": self = .mismatchedIpVersion
      case "GKE_KONNECTIVITY_PROXY_UNSUPPORTED": self = .gkeKonnectivityProxyUnsupported
      case "RESOURCE_CONFIG_NOT_FOUND": self = .resourceConfigNotFound
      case "VM_INSTANCE_CONFIG_NOT_FOUND": self = .vmInstanceConfigNotFound
      case "NETWORK_CONFIG_NOT_FOUND": self = .networkConfigNotFound
      case "FIREWALL_CONFIG_NOT_FOUND": self = .firewallConfigNotFound
      case "ROUTE_CONFIG_NOT_FOUND": self = .routeConfigNotFound
      case "GOOGLE_MANAGED_SERVICE_AMBIGUOUS_PSC_ENDPOINT":
        self = .googleManagedServiceAmbiguousPscEndpoint
      case "GOOGLE_MANAGED_SERVICE_AMBIGUOUS_ENDPOINT":
        self = .googleManagedServiceAmbiguousEndpoint
      case "SOURCE_PSC_CLOUD_SQL_UNSUPPORTED": self = .sourcePscCloudSqlUnsupported
      case "SOURCE_EXTERNAL_CLOUD_SQL_UNSUPPORTED": self = .sourceExternalCloudSqlUnsupported
      case "SOURCE_REDIS_CLUSTER_UNSUPPORTED": self = .sourceRedisClusterUnsupported
      case "SOURCE_REDIS_INSTANCE_UNSUPPORTED": self = .sourceRedisInstanceUnsupported
      case "SOURCE_FORWARDING_RULE_UNSUPPORTED": self = .sourceForwardingRuleUnsupported
      case "NON_ROUTABLE_IP_ADDRESS": self = .nonRoutableIpAddress
      case "UNKNOWN_ISSUE_IN_GOOGLE_MANAGED_PROJECT": self = .unknownIssueInGoogleManagedProject
      case "UNSUPPORTED_GOOGLE_MANAGED_PROJECT_CONFIG":
        self = .unsupportedGoogleManagedProjectConfig
      case "NO_SERVERLESS_IP_RANGES": self = .noServerlessIpRanges
      case "IP_VERSION_PROTOCOL_MISMATCH": self = .ipVersionProtocolMismatch
      case "GKE_POD_UNKNOWN_ENDPOINT_LOCATION": self = .gkePodUnknownEndpointLocation
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Cause/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .unknownNetwork
      case 2: self = .unknownIp
      case 3: self = .unknownProject
      case 4: self = .permissionDenied
      case 5: self = .noSourceLocation
      case 6: self = .invalidArgument
      case 7: self = .noExternalIp
      case 8: self = .unintendedDestination
      case 9: self = .traceTooLong
      case 10: self = .internalError
      case 11: self = .sourceEndpointNotFound
      case 12: self = .mismatchedSourceNetwork
      case 13: self = .destinationEndpointNotFound
      case 14: self = .mismatchedDestinationNetwork
      case 15: self = .unsupported
      case 16: self = .mismatchedIpVersion
      case 17: self = .gkeKonnectivityProxyUnsupported
      case 18: self = .resourceConfigNotFound
      case 19: self = .googleManagedServiceAmbiguousPscEndpoint
      case 20: self = .sourcePscCloudSqlUnsupported
      case 21: self = .sourceForwardingRuleUnsupported
      case 22: self = .nonRoutableIpAddress
      case 23: self = .sourceIpAddressNotInSourceNetwork
      case 24: self = .vmInstanceConfigNotFound
      case 25: self = .networkConfigNotFound
      case 26: self = .firewallConfigNotFound
      case 27: self = .routeConfigNotFound
      case 28: self = .permissionDeniedNoCloudNatConfigs
      case 29: self = .permissionDeniedNoNegEndpointConfigs
      case 30: self = .unknownIssueInGoogleManagedProject
      case 31: self = .unsupportedGoogleManagedProjectConfig
      case 32: self = .googleManagedServiceUnknownIp
      case 34: self = .sourceRedisClusterUnsupported
      case 35: self = .sourceRedisInstanceUnsupported
      case 36: self = .permissionDeniedNoCloudRouterConfigs
      case 37: self = .noServerlessIpRanges
      case 39: self = .googleManagedServiceAmbiguousEndpoint
      case 40: self = .ipVersionProtocolMismatch
      case 41: self = .gkePodUnknownEndpointLocation
      case 42: self = .noSourceGcpNetworkLocation
      case 43: self = .noSourceNonGcpNetworkLocation
      case 44: self = .noSourceInternetLocation
      case 45: self = .sourceExternalCloudSqlUnsupported
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .unknownNetwork: return try container.encode(1)
      case .unknownIp: return try container.encode(2)
      case .unknownProject: return try container.encode(3)
      case .permissionDenied: return try container.encode(4)
      case .noSourceLocation: return try container.encode(5)
      case .invalidArgument: return try container.encode(6)
      case .noExternalIp: return try container.encode(7)
      case .unintendedDestination: return try container.encode(8)
      case .traceTooLong: return try container.encode(9)
      case .internalError: return try container.encode(10)
      case .sourceEndpointNotFound: return try container.encode(11)
      case .mismatchedSourceNetwork: return try container.encode(12)
      case .destinationEndpointNotFound: return try container.encode(13)
      case .mismatchedDestinationNetwork: return try container.encode(14)
      case .unsupported: return try container.encode(15)
      case .mismatchedIpVersion: return try container.encode(16)
      case .gkeKonnectivityProxyUnsupported: return try container.encode(17)
      case .resourceConfigNotFound: return try container.encode(18)
      case .googleManagedServiceAmbiguousPscEndpoint: return try container.encode(19)
      case .sourcePscCloudSqlUnsupported: return try container.encode(20)
      case .sourceForwardingRuleUnsupported: return try container.encode(21)
      case .nonRoutableIpAddress: return try container.encode(22)
      case .sourceIpAddressNotInSourceNetwork: return try container.encode(23)
      case .vmInstanceConfigNotFound: return try container.encode(24)
      case .networkConfigNotFound: return try container.encode(25)
      case .firewallConfigNotFound: return try container.encode(26)
      case .routeConfigNotFound: return try container.encode(27)
      case .permissionDeniedNoCloudNatConfigs: return try container.encode(28)
      case .permissionDeniedNoNegEndpointConfigs: return try container.encode(29)
      case .unknownIssueInGoogleManagedProject: return try container.encode(30)
      case .unsupportedGoogleManagedProjectConfig: return try container.encode(31)
      case .googleManagedServiceUnknownIp: return try container.encode(32)
      case .sourceRedisClusterUnsupported: return try container.encode(34)
      case .sourceRedisInstanceUnsupported: return try container.encode(35)
      case .permissionDeniedNoCloudRouterConfigs: return try container.encode(36)
      case .noServerlessIpRanges: return try container.encode(37)
      case .googleManagedServiceAmbiguousEndpoint: return try container.encode(39)
      case .ipVersionProtocolMismatch: return try container.encode(40)
      case .gkePodUnknownEndpointLocation: return try container.encode(41)
      case .noSourceGcpNetworkLocation: return try container.encode(42)
      case .noSourceNonGcpNetworkLocation: return try container.encode(43)
      case .noSourceInternetLocation: return try container.encode(44)
      case .sourceExternalCloudSqlUnsupported: return try container.encode(45)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkmanagement.v1.AbortInfo"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
