// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request for the `CreateVpcFlowLogsConfig` method.
public struct CreateVpcFlowLogsConfigRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The parent resource of the VpcFlowLogsConfig to create,
  /// in one of the following formats:
  ///
  /// - For project-level resources: `projects/{project_id}/locations/global`
  ///
  /// - For organization-level resources:
  /// `organizations/{organization_id}/locations/global`
  public var parent: Swift.String = Swift.String()

  /// Required. ID of the `VpcFlowLogsConfig`.
  public var vpcFlowLogsConfigId: Swift.String = Swift.String()

  /// Required. A `VpcFlowLogsConfig` resource
  public var vpcFlowLogsConfig: VpcFlowLogsConfig? = nil

  /// Initialize a new instance of `CreateVpcFlowLogsConfigRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateVpcFlowLogsConfigRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkmanagement.v1.CreateVpcFlowLogsConfigRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
