// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Details of the final state "deliver" and associated resource.
public struct DeliverInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Target type where the packet is delivered to.
  public var target: DeliverInfo.Target = DeliverInfo.Target()

  /// URI of the resource that the packet is delivered to.
  public var resourceUri: Swift.String = Swift.String()

  /// IP address of the target (if applicable).
  public var ipAddress: Swift.String = Swift.String()

  /// Name of the Cloud Storage Bucket the packet is delivered to (if
  /// applicable).
  public var storageBucket: Swift.String = Swift.String()

  /// PSC Google API target the packet is delivered to (if applicable).
  public var pscGoogleApiTarget: Swift.String = Swift.String()

  /// Recognized type of a Google Service the packet is delivered to (if
  /// applicable).
  public var googleServiceType: DeliverInfo.GoogleServiceType = DeliverInfo.GoogleServiceType()

  /// Initialize a new instance of `DeliverInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DeliverInfo().with { $0.target = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Deliver target types:
  public enum Target: Codable, Equatable, Sendable {
    /// Target not specified.
    case unspecified
    /// Target is a Compute Engine instance.
    case instance
    /// Target is the internet.
    case internet
    /// Target is a Google API.
    case googleApi
    /// Target is a Google Kubernetes Engine cluster master.
    case gkeMaster
    /// Target is a Cloud SQL instance.
    case cloudSqlInstance
    /// Target is a published service that uses [Private Service
    /// Connect](https://cloud.google.com/vpc/docs/configure-private-service-connect-services).
    case pscPublishedService
    /// Target is Google APIs that use [Private Service
    /// Connect](https://cloud.google.com/vpc/docs/configure-private-service-connect-apis).
    case pscGoogleApi
    /// Target is a VPC-SC that uses [Private Service
    /// Connect](https://cloud.google.com/vpc/docs/configure-private-service-connect-apis).
    case pscVpcSc
    /// Target is a serverless network endpoint group.
    case serverlessNeg
    /// Target is a Cloud Storage bucket.
    case storageBucket
    /// Target is a private network. Used only for return traces.
    case privateNetwork
    /// Target is a Cloud Function. Used only for return traces.
    case cloudFunction
    /// Target is a App Engine service version. Used only for return traces.
    case appEngineVersion
    /// Target is a Cloud Run revision. Used only for return traces.
    case cloudRunRevision
    /// Target is a Google-managed service. Used only for return traces.
    case googleManagedService
    /// Target is a Redis Instance.
    case redisInstance
    /// Target is a Redis Cluster.
    case redisCluster
    /// Target is a GKE Pod.
    case gkePod
    /// Target is a Cloud Run Job. Used only for return traces.
    case cloudRunJob
    /// Target is a DMS Private Connection. Used only for return traces.
    case dmsPrivateConnection
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .instance: return 1
      case .internet: return 2
      case .googleApi: return 3
      case .gkeMaster: return 4
      case .cloudSqlInstance: return 5
      case .pscPublishedService: return 6
      case .pscGoogleApi: return 7
      case .pscVpcSc: return 8
      case .serverlessNeg: return 9
      case .storageBucket: return 10
      case .privateNetwork: return 11
      case .cloudFunction: return 12
      case .appEngineVersion: return 13
      case .cloudRunRevision: return 14
      case .googleManagedService: return 15
      case .redisInstance: return 16
      case .redisCluster: return 17
      case .gkePod: return 19
      case .cloudRunJob: return 20
      case .dmsPrivateConnection: return 21
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TARGET_UNSPECIFIED"
      case .instance: return "INSTANCE"
      case .internet: return "INTERNET"
      case .googleApi: return "GOOGLE_API"
      case .gkeMaster: return "GKE_MASTER"
      case .cloudSqlInstance: return "CLOUD_SQL_INSTANCE"
      case .pscPublishedService: return "PSC_PUBLISHED_SERVICE"
      case .pscGoogleApi: return "PSC_GOOGLE_API"
      case .pscVpcSc: return "PSC_VPC_SC"
      case .serverlessNeg: return "SERVERLESS_NEG"
      case .storageBucket: return "STORAGE_BUCKET"
      case .privateNetwork: return "PRIVATE_NETWORK"
      case .cloudFunction: return "CLOUD_FUNCTION"
      case .appEngineVersion: return "APP_ENGINE_VERSION"
      case .cloudRunRevision: return "CLOUD_RUN_REVISION"
      case .googleManagedService: return "GOOGLE_MANAGED_SERVICE"
      case .redisInstance: return "REDIS_INSTANCE"
      case .redisCluster: return "REDIS_CLUSTER"
      case .gkePod: return "GKE_POD"
      case .cloudRunJob: return "CLOUD_RUN_JOB"
      case .dmsPrivateConnection: return "DMS_PRIVATE_CONNECTION"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Target/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TARGET_UNSPECIFIED": self = .unspecified
      case "INSTANCE": self = .instance
      case "INTERNET": self = .internet
      case "GOOGLE_API": self = .googleApi
      case "GKE_MASTER": self = .gkeMaster
      case "CLOUD_SQL_INSTANCE": self = .cloudSqlInstance
      case "PSC_PUBLISHED_SERVICE": self = .pscPublishedService
      case "PSC_GOOGLE_API": self = .pscGoogleApi
      case "PSC_VPC_SC": self = .pscVpcSc
      case "SERVERLESS_NEG": self = .serverlessNeg
      case "STORAGE_BUCKET": self = .storageBucket
      case "PRIVATE_NETWORK": self = .privateNetwork
      case "CLOUD_FUNCTION": self = .cloudFunction
      case "APP_ENGINE_VERSION": self = .appEngineVersion
      case "CLOUD_RUN_REVISION": self = .cloudRunRevision
      case "GOOGLE_MANAGED_SERVICE": self = .googleManagedService
      case "REDIS_INSTANCE": self = .redisInstance
      case "REDIS_CLUSTER": self = .redisCluster
      case "GKE_POD": self = .gkePod
      case "CLOUD_RUN_JOB": self = .cloudRunJob
      case "DMS_PRIVATE_CONNECTION": self = .dmsPrivateConnection
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Target/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .instance
      case 2: self = .internet
      case 3: self = .googleApi
      case 4: self = .gkeMaster
      case 5: self = .cloudSqlInstance
      case 6: self = .pscPublishedService
      case 7: self = .pscGoogleApi
      case 8: self = .pscVpcSc
      case 9: self = .serverlessNeg
      case 10: self = .storageBucket
      case 11: self = .privateNetwork
      case 12: self = .cloudFunction
      case 13: self = .appEngineVersion
      case 14: self = .cloudRunRevision
      case 15: self = .googleManagedService
      case 16: self = .redisInstance
      case 17: self = .redisCluster
      case 19: self = .gkePod
      case 20: self = .cloudRunJob
      case 21: self = .dmsPrivateConnection
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .instance: return try container.encode(1)
      case .internet: return try container.encode(2)
      case .googleApi: return try container.encode(3)
      case .gkeMaster: return try container.encode(4)
      case .cloudSqlInstance: return try container.encode(5)
      case .pscPublishedService: return try container.encode(6)
      case .pscGoogleApi: return try container.encode(7)
      case .pscVpcSc: return try container.encode(8)
      case .serverlessNeg: return try container.encode(9)
      case .storageBucket: return try container.encode(10)
      case .privateNetwork: return try container.encode(11)
      case .cloudFunction: return try container.encode(12)
      case .appEngineVersion: return try container.encode(13)
      case .cloudRunRevision: return try container.encode(14)
      case .googleManagedService: return try container.encode(15)
      case .redisInstance: return try container.encode(16)
      case .redisCluster: return try container.encode(17)
      case .gkePod: return try container.encode(19)
      case .cloudRunJob: return try container.encode(20)
      case .dmsPrivateConnection: return try container.encode(21)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Recognized type of a Google Service.
  public enum GoogleServiceType: Codable, Equatable, Sendable {
    /// Unspecified Google Service.
    case unspecified
    /// Identity aware proxy.
    /// https://cloud.google.com/iap/docs/using-tcp-forwarding
    case iap
    /// One of two services sharing IP ranges:
    /// * Load Balancer proxy
    /// * Centralized Health Check prober
    /// https://cloud.google.com/load-balancing/docs/firewall-rules
    case gfeProxyOrHealthCheckProber
    /// Connectivity from Cloud DNS to forwarding targets or alternate name
    /// servers that use private routing.
    /// https://cloud.google.com/dns/docs/zones/forwarding-zones#firewall-rules
    /// https://cloud.google.com/dns/docs/policies#firewall-rules
    case cloudDns
    /// private.googleapis.com and restricted.googleapis.com
    case privateGoogleAccess
    /// Google API via Private Service Connect.
    /// https://cloud.google.com/vpc/docs/configure-private-service-connect-apis
    /// Google API via Serverless VPC Access.
    /// https://cloud.google.com/vpc/docs/serverless-vpc-access
    case serverlessVpcAccess
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .iap: return 1
      case .gfeProxyOrHealthCheckProber: return 2
      case .cloudDns: return 3
      case .privateGoogleAccess: return 4
      case .serverlessVpcAccess: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "GOOGLE_SERVICE_TYPE_UNSPECIFIED"
      case .iap: return "IAP"
      case .gfeProxyOrHealthCheckProber: return "GFE_PROXY_OR_HEALTH_CHECK_PROBER"
      case .cloudDns: return "CLOUD_DNS"
      case .privateGoogleAccess: return "PRIVATE_GOOGLE_ACCESS"
      case .serverlessVpcAccess: return "SERVERLESS_VPC_ACCESS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:GoogleServiceType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "GOOGLE_SERVICE_TYPE_UNSPECIFIED": self = .unspecified
      case "IAP": self = .iap
      case "GFE_PROXY_OR_HEALTH_CHECK_PROBER": self = .gfeProxyOrHealthCheckProber
      case "CLOUD_DNS": self = .cloudDns
      case "PRIVATE_GOOGLE_ACCESS": self = .privateGoogleAccess
      case "SERVERLESS_VPC_ACCESS": self = .serverlessVpcAccess
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:GoogleServiceType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .iap
      case 2: self = .gfeProxyOrHealthCheckProber
      case 3: self = .cloudDns
      case 4: self = .privateGoogleAccess
      case 5: self = .serverlessVpcAccess
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .iap: return try container.encode(1)
      case .gfeProxyOrHealthCheckProber: return try container.encode(2)
      case .cloudDns: return try container.encode(3)
      case .privateGoogleAccess: return try container.encode(4)
      case .serverlessVpcAccess: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkmanagement.v1.DeliverInfo"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
