// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// For display only. Metadata associated with a serverless direct VPC egress
/// connection.
public struct DirectVpcEgressConnectionInfo: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// URI of direct access network.
  public var networkUri: Swift.String = Swift.String()

  /// URI of direct access subnetwork.
  public var subnetworkUri: Swift.String = Swift.String()

  /// Selected IP range.
  public var selectedIpRange: Swift.String = Swift.String()

  /// Selected starting IP address, from the selected IP range.
  public var selectedIpAddress: Swift.String = Swift.String()

  /// Region in which the Direct VPC egress is deployed.
  public var region: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DirectVpcEgressConnectionInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DirectVpcEgressConnectionInfo().with { $0.networkUri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let networkUri = CodingKeys(stringValue: "networkUri")
    static let subnetworkUri = CodingKeys(stringValue: "subnetworkUri")
    static let selectedIpRange = CodingKeys(stringValue: "selectedIpRange")
    static let selectedIpAddress = CodingKeys(stringValue: "selectedIpAddress")
    static let region = CodingKeys(stringValue: "region")

    static let _knownKeys: Set<Swift.String> = [
      "networkUri",
      "subnetworkUri",
      "selectedIpRange",
      "selectedIpAddress",
      "region",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .networkUri) {
      self.networkUri = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .subnetworkUri) {
      self.subnetworkUri = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .selectedIpRange) {
      self.selectedIpRange = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .selectedIpAddress) {
      self.selectedIpAddress = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .region) {
      self.region = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.networkUri, forKey: .networkUri)
    try container.encode(self.subnetworkUri, forKey: .subnetworkUri)
    try container.encode(self.selectedIpRange, forKey: .selectedIpRange)
    try container.encode(self.selectedIpAddress, forKey: .selectedIpAddress)
    try container.encode(self.region, forKey: .region)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkmanagement.v1.DirectVpcEgressConnectionInfo"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
