// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// For display only. Metadata associated with a serverless direct VPC egress
/// connection.
public struct DirectVpcEgressConnectionInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// URI of direct access network.
  public var networkUri: Swift.String = Swift.String()

  /// URI of direct access subnetwork.
  public var subnetworkUri: Swift.String = Swift.String()

  /// Selected IP range.
  public var selectedIpRange: Swift.String = Swift.String()

  /// Selected starting IP address, from the selected IP range.
  public var selectedIpAddress: Swift.String = Swift.String()

  /// Region in which the Direct VPC egress is deployed.
  public var region: Swift.String = Swift.String()

  /// Initialize a new instance of `DirectVpcEgressConnectionInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DirectVpcEgressConnectionInfo().with { $0.networkUri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkmanagement.v1.DirectVpcEgressConnectionInfo"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
