// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Details of the final state "drop" and associated resource.
public struct DropInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Cause that the packet is dropped.
  public var cause: DropInfo.Cause = DropInfo.Cause()

  /// URI of the resource that caused the drop.
  public var resourceUri: Swift.String = Swift.String()

  /// Source IP address of the dropped packet (if relevant).
  public var sourceIp: Swift.String = Swift.String()

  /// Destination IP address of the dropped packet (if relevant).
  public var destinationIp: Swift.String = Swift.String()

  /// Region of the dropped packet (if relevant).
  public var region: Swift.String = Swift.String()

  /// Geolocation (region code) of the source IP address (if relevant).
  public var sourceGeolocationCode: Swift.String = Swift.String()

  /// Geolocation (region code) of the destination IP address (if relevant).
  public var destinationGeolocationCode: Swift.String = Swift.String()

  /// Initialize a new instance of `DropInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DropInfo().with { $0.cause = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Drop cause types:
  public enum Cause: Codable, Equatable, Sendable {
    /// Cause is unspecified.
    case unspecified
    /// Destination external address cannot be resolved to a known target. If
    /// the address is used in a Google Cloud project, provide the project ID
    /// as test input.
    case unknownExternalAddress
    /// A Compute Engine instance can only send or receive a packet with a
    /// foreign IP address if ip_forward is enabled.
    case foreignIpDisallowed
    /// Dropped due to a firewall rule, unless allowed due to connection
    /// tracking.
    case firewallRule
    /// Dropped due to no matching routes.
    case noRoute
    /// Dropped due to invalid route. Route's next hop is a blackhole.
    case routeBlackhole
    /// Packet is sent to a wrong (unintended) network. Example: you trace a
    /// packet from VM1:Network1 to VM2:Network2, however, the route configured
    /// in Network1 sends the packet destined for VM2's IP address to Network3.
    case routeWrongNetwork
    /// Packet with internal destination address sent to the internet gateway.
    case privateTrafficToInternet
    /// Endpoint with only an internal IP address tries to access Google API and
    /// services, but Private Google Access is not enabled in the subnet or is
    /// not applicable.
    case privateGoogleAccessDisallowed
    /// Endpoint with only an internal IP address tries to access external hosts,
    /// but there is no matching Cloud NAT gateway in the subnet.
    case noExternalAddress
    /// Destination internal address cannot be resolved to a known target. If
    /// this is a shared VPC scenario, verify if the service project ID is
    /// provided as test input. Otherwise, verify if the IP address is being
    /// used in the project.
    case unknownInternalAddress
    /// Forwarding rule's protocol and ports do not match the packet header.
    case forwardingRuleMismatch
    /// Forwarding rule does not have backends configured.
    case forwardingRuleNoInstances
    /// Firewalls block the health check probes to the backends and cause
    /// the backends to be unavailable for traffic from the load balancer.
    /// For more details, see [Health check firewall
    /// rules](https://cloud.google.com/load-balancing/docs/health-checks#firewall_rules).
    case firewallBlockingLoadBalancerBackendHealthCheck
    /// Packet is sent from or to a Compute Engine instance that is not in a
    /// running state.
    case instanceNotRunning
    /// The type of traffic is blocked and the user cannot configure a firewall
    /// rule to enable it. See [Always blocked
    /// traffic](https://cloud.google.com/vpc/docs/firewalls#blockedtraffic) for
    /// more details.
    case trafficTypeBlocked
    /// Access to Google Kubernetes Engine cluster master's endpoint is not
    /// authorized. See [Access to the cluster
    /// endpoints](https://cloud.google.com/kubernetes-engine/docs/how-to/private-clusters#access_to_the_cluster_endpoints)
    /// for more details.
    case gkeMasterUnauthorizedAccess
    /// Access to the Cloud SQL instance endpoint is not authorized.
    /// See [Authorizing with authorized
    /// networks](https://cloud.google.com/sql/docs/mysql/authorize-networks) for
    /// more details.
    case cloudSqlInstanceUnauthorizedAccess
    /// Packet was dropped inside Google Kubernetes Engine Service.
    case droppedInsideGkeService
    /// Packet was dropped inside Cloud SQL Service.
    case droppedInsideCloudSqlService
    /// Packet was dropped because there is no peering between the originating
    /// network and the Google Managed Services Network.
    case googleManagedServiceNoPeering
    /// Packet was dropped because the Cloud SQL instance has neither a private
    /// nor a public IP address.
    case cloudSqlInstanceNoIpAddress
    /// Packet could be dropped because the Cloud Function is not in an active
    /// status.
    case cloudFunctionNotActive
    /// Packet could be dropped because no VPC connector is set.
    case vpcConnectorNotSet
    /// Packet could be dropped because the VPC connector is not in a running
    /// state.
    case vpcConnectorNotRunning
    /// Packet could be dropped because it was sent from a different region
    /// to a regional forwarding without global access.
    case forwardingRuleRegionMismatch
    /// The Private Service Connect endpoint is in a project that is not approved
    /// to connect to the service.
    case pscConnectionNotAccepted
    /// Packet sent from or to a GKE cluster that is not in running state.
    case gkeClusterNotRunning
    /// Packet sent from or to a Cloud SQL instance that is not in running state.
    case cloudSqlInstanceNotRunning
    /// Packet sent from a Cloud Run revision that is not ready.
    case cloudRunRevisionNotReady
    /// Packet was dropped because a GKE cluster private endpoint is
    /// unreachable from a region different from the cluster's region.
    case gkeControlPlaneRegionMismatch
    /// Packet sent from a public GKE cluster control plane to a private
    /// IP address.
    case publicGkeControlPlaneToPrivateDestination
    /// Packet was dropped because there is no route from a GKE cluster
    /// control plane to a destination network.
    case gkeControlPlaneNoRoute
    /// Packet sent from a Cloud SQL instance to an external IP address is not
    /// allowed. The Cloud SQL instance is not configured to send packets to
    /// external IP addresses.
    case cloudSqlInstanceNotConfiguredForExternalTraffic
    /// Packet sent from a Cloud SQL instance with only a public IP address to a
    /// private IP address.
    case publicCloudSqlInstanceToPrivateDestination
    /// Packet was dropped because there is no route from a Cloud SQL
    /// instance to a destination network.
    case cloudSqlInstanceNoRoute
    /// Packet was dropped because the GKE cluster uses Private Service Connect
    /// (PSC), but the PSC endpoint is not found in the project.
    case gkePscEndpointMissing
    /// Packet was dropped inside Private Service Connect service producer.
    case droppedInsidePscServiceProducer
    /// Packet was dropped because the Google-managed service uses Private
    /// Service Connect (PSC), but the PSC endpoint is not found in the project.
    case googleManagedServiceNoPscEndpoint
    /// Packet sent to a load balancer, which requires a proxy-only subnet and
    /// the subnet is not found.
    case loadBalancerHasNoProxySubnet
    /// Packet sent to Cloud Nat without active NAT IPs.
    case cloudNatNoAddresses
    /// The packet is sent to the Private Service Connect endpoint over the
    /// peering, but [it's not
    /// supported](https://cloud.google.com/vpc/docs/configure-private-service-connect-services#on-premises).
    case pscEndpointAccessedFromPeeredNetwork
    /// Route's next hop IP address cannot be resolved to a GCP resource.
    case routeNextHopIpAddressNotResolved
    /// Route's next hop resource is not found.
    case routeNextHopResourceNotFound
    /// Packet is sent from the Internet to the private IPv6 address.
    case noRouteFromInternetToPrivateIpv6Address
    /// The packet does not match a policy-based VPN tunnel local selector.
    case vpnTunnelLocalSelectorMismatch
    /// The packet does not match a policy-based VPN tunnel remote selector.
    case vpnTunnelRemoteSelectorMismatch
    /// Source endpoint tries to access Google API and services through the VPN
    /// tunnel to another network, but Private Google Access needs to be enabled
    /// in the source endpoint network.
    case privateGoogleAccessViaVpnTunnelUnsupported
    /// The packet is sent to the Private Service Connect backend (network
    /// endpoint group), but the producer PSC forwarding rule does not have
    /// global access enabled.
    case pscNegProducerEndpointNoGlobalAccess
    /// Route's next hop instance doesn't have a NIC in the route's network.
    case routeNextHopInstanceWrongNetwork
    /// Route's next hop IP address is not a primary IP address of the next hop
    /// instance.
    case routeNextHopInstanceNonPrimaryIp
    /// Route's next hop forwarding rule doesn't match next hop IP address.
    case routeNextHopForwardingRuleIpMismatch
    /// Route's next hop VPN tunnel is down (does not have valid IKE SAs).
    case routeNextHopVpnTunnelNotEstablished
    /// Route's next hop forwarding rule type is invalid (it's not a forwarding
    /// rule of the internal passthrough load balancer).
    case routeNextHopForwardingRuleTypeInvalid
    /// The packet is sent to the Private Service Connect backend (network
    /// endpoint group), but the producer PSC forwarding rule has multiple ports
    /// specified.
    case pscNegProducerForwardingRuleMultiplePorts
    /// The packet sent from the hybrid NEG proxy matches a non-dynamic route,
    /// but such a configuration is not supported.
    case hybridNegNonDynamicRouteMatched
    /// The packet sent from the hybrid NEG proxy matches a dynamic route with a
    /// next hop in a different region, but such a configuration is not
    /// supported.
    case hybridNegNonLocalDynamicRouteMatched
    /// No NAT subnets are defined for the PSC service attachment.
    case noNatSubnetsForPscServiceAttachment
    /// The packet is sent to the Private Service Connect backend (network
    /// endpoint group) targeting a Cloud SQL service attachment, but this
    /// configuration is not supported.
    case cloudSqlPscNegUnsupported
    /// Packet is stuck in a routing loop.
    case routingLoop
    /// Packet could be dropped because the traffic from the serverless service
    /// to the VPC connector is not allowed.
    case vpcConnectorServerlessTrafficBlocked
    /// Packet could be dropped because the health check traffic to the VPC
    /// connector is not allowed.
    case vpcConnectorHealthCheckTrafficBlocked
    /// Packet is dropped inside a Google-managed service due to being delivered
    /// in return trace to an endpoint that doesn't match the endpoint the packet
    /// was sent from in forward trace. Used only for return traces.
    case droppedInsideGoogleManagedService
    /// Packet was dropped because the Cloud SQL instance requires all
    /// connections to use Cloud SQL connectors and to target the Cloud SQL proxy
    /// port (3307).
    case cloudSqlConnectorRequired
    /// PSC endpoint is accessed via NCC, but PSC transitivity configuration is
    /// not yet propagated.
    case pscTransitivityNotPropagated
    /// Packet is dropped due to a load balancer backend instance not having a
    /// network interface in the network expected by the load balancer.
    case loadBalancerBackendInvalidNetwork
    /// Packet is dropped due to a backend service named port not being defined
    /// on the instance group level.
    case backendServiceNamedPortNotDefined
    /// Packet is dropped due to a destination IP range being part of a Private
    /// NAT IP range.
    case destinationIsPrivateNatIpRange
    /// Packet sent from or to a Redis Instance that is not in running state.
    case redisInstanceNotRunning
    /// Packet sent from or to a Redis Cluster that is not in running state.
    case redisClusterNotRunning
    /// Generic drop cause for a packet being dropped inside a Redis Instance
    /// service project.
    case droppedInsideRedisInstanceService
    /// Packet is dropped due to an unsupported port being used to connect to a
    /// Redis Instance. Port 6379 should be used to connect to a Redis Instance.
    case redisInstanceUnsupportedPort
    /// Packet is dropped due to connecting from PUPI address to a PSA based
    /// Redis Instance.
    case redisInstanceConnectingFromPupiAddress
    /// Packet is dropped due to no route to the destination network.
    case redisInstanceNoRouteToDestinationNetwork
    /// Redis Instance does not have an external IP address.
    case redisInstanceNoExternalIp
    /// Generic drop cause for a packet being dropped inside a Redis Cluster
    /// service project.
    case droppedInsideRedisClusterService
    /// Packet is dropped due to an unsupported port being used to connect to a
    /// Redis Cluster. Ports 6379 and 11000 to 13047 should be used to connect to
    /// a Redis Cluster.
    case redisClusterUnsupportedPort
    /// Redis Cluster does not have an external IP address.
    case redisClusterNoExternalIp
    /// Packet is dropped due to an unsupported protocol being used to connect to
    /// a Redis Instance. Only TCP connections are accepted by a Redis Instance.
    case redisInstanceUnsupportedProtocol
    /// Packet is dropped due to an unsupported protocol being used to connect to
    /// a Redis Cluster. Only TCP connections are accepted by a Redis Cluster.
    case redisClusterUnsupportedProtocol
    /// Packet from the non-GCP (on-prem) or unknown GCP network is dropped due
    /// to the destination IP address not belonging to any IP prefix advertised
    /// via BGP by the Cloud Router.
    case noAdvertisedRouteToGcpDestination
    /// Packet from the non-GCP (on-prem) or unknown GCP network is dropped due
    /// to the destination IP address not belonging to any IP prefix included to
    /// the local traffic selector of the VPN tunnel.
    case noTrafficSelectorToGcpDestination
    /// Packet from the unknown peered network is dropped due to no known route
    /// from the source network to the destination IP address.
    case noKnownRouteFromPeeredNetworkToDestination
    /// Sending packets processed by the Private NAT Gateways to the Private
    /// Service Connect endpoints is not supported.
    case privateNatToPscEndpointUnsupported
    /// Matching ingress firewall rules by network tags for packets sent via
    /// serverless VPC direct egress is unsupported. Behavior is undefined.
    /// https://cloud.google.com/run/docs/configuring/vpc-direct-vpc#limitations
    case ingressFirewallTagsUnsupportedByDirectVpcEgress
    /// Packet is sent to the PSC port mapping service, but its destination port
    /// does not match any port mapping rules.
    case pscPortMappingPortMismatch
    /// Sending packets directly to the PSC port mapping service without going
    /// through the PSC connection is not supported.
    case pscPortMappingWithoutPscConnectionUnsupported
    /// Packet with destination IP address within the reserved NAT64 range is
    /// dropped due to matching a route of an unsupported type.
    case unsupportedRouteMatchedForNat64Destination
    /// Packet could be dropped because hybrid endpoint like a VPN gateway or
    /// Interconnect is not allowed to send traffic to the Internet.
    case trafficFromHybridEndpointToInternetDisallowed
    /// Packet with destination IP address within the reserved NAT64 range is
    /// dropped due to no matching NAT gateway in the subnet.
    case noMatchingNat64Gateway
    /// Packet is dropped due to being sent to a backend of a passthrough load
    /// balancer that doesn't use the same IP version as the frontend.
    case loadBalancerBackendIpVersionMismatch
    /// Packet from the unknown NCC network is dropped due to no known route
    /// from the source network to the destination IP address.
    case noKnownRouteFromNccNetworkToDestination
    /// Packet is sent from the external IPv6 source address of an instance to
    /// the private IPv6 address of an instance.
    case noRouteFromExternalIpv6SourceToPrivateIpv6Address
    /// Packet is dropped by Cloud NAT due to using an unsupported protocol.
    case cloudNatProtocolUnsupported
    /// Packet is dropped due to using an unsupported protocol (any other than
    /// UDP) for L2 Interconnect.
    case l2InterconnectUnsupportedProtocol
    /// Packet is dropped due to using an unsupported port (any other than
    /// 6081) for L2 Interconnect.
    case l2InterconnectUnsupportedPort
    /// Packet is dropped due to destination IP not matching the appliance
    /// mapping IPs configured on the L2 Interconnect attachment.
    case l2InterconnectDestinationIpMismatch
    /// Packet sent from or to a GKE Pod that is not in running state.
    case gkePodNotRunning
    /// Packet could be dropped because it matches a route associated with an NCC
    /// spoke in the hybrid subnet context, but such a configuration is not
    /// supported.
    case nccRouteWithinHybridSubnetUnsupported
    /// Packet is dropped because the region of the hybrid subnet is different
    /// from the region of the next hop of the route matched within this hybrid
    /// subnet.
    case hybridSubnetRegionMismatch
    /// Packet is dropped because no matching route was found in the hybrid
    /// subnet.
    case hybridSubnetNoRoute
    /// Packet is dropped due to matching a Private NAT64 gateway with no rules
    /// for source IPv6 addresses.
    case noConfiguredPrivateNat64Rule
    /// Packet is dropped by GKE Network Policy.
    case gkeNetworkPolicy
    /// Packet is sent from the Internet to the private IPv4 address.
    case noRouteFromInternetToPrivateIpv4Address
    /// Packet is dropped because there is no valid matching route from the
    /// network of the Google-managed service to the destination.
    case noValidRouteFromGoogleManagedNetworkToDestination
    /// Packet is dropped due to no running instance found for private
    /// connection.
    case privateConnectionNoRunningInstance
    /// Packet sent from a Cloud Run job that is not ready.
    case cloudRunJobNotReady
    /// Packet was dropped inside DMS Private Connection.
    case droppedInsideDmsPrivateConnection
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .unknownExternalAddress: return 1
      case .foreignIpDisallowed: return 2
      case .firewallRule: return 3
      case .noRoute: return 4
      case .routeBlackhole: return 5
      case .routeWrongNetwork: return 6
      case .privateTrafficToInternet: return 7
      case .privateGoogleAccessDisallowed: return 8
      case .noExternalAddress: return 9
      case .unknownInternalAddress: return 10
      case .forwardingRuleMismatch: return 11
      case .forwardingRuleNoInstances: return 12
      case .firewallBlockingLoadBalancerBackendHealthCheck: return 13
      case .instanceNotRunning: return 14
      case .trafficTypeBlocked: return 15
      case .gkeMasterUnauthorizedAccess: return 16
      case .cloudSqlInstanceUnauthorizedAccess: return 17
      case .droppedInsideGkeService: return 18
      case .droppedInsideCloudSqlService: return 19
      case .googleManagedServiceNoPeering: return 20
      case .cloudSqlInstanceNoIpAddress: return 21
      case .cloudFunctionNotActive: return 22
      case .vpcConnectorNotSet: return 23
      case .vpcConnectorNotRunning: return 24
      case .forwardingRuleRegionMismatch: return 25
      case .pscConnectionNotAccepted: return 26
      case .gkeClusterNotRunning: return 27
      case .cloudSqlInstanceNotRunning: return 28
      case .cloudRunRevisionNotReady: return 29
      case .gkeControlPlaneRegionMismatch: return 30
      case .publicGkeControlPlaneToPrivateDestination: return 31
      case .gkeControlPlaneNoRoute: return 32
      case .cloudSqlInstanceNotConfiguredForExternalTraffic: return 33
      case .publicCloudSqlInstanceToPrivateDestination: return 34
      case .cloudSqlInstanceNoRoute: return 35
      case .gkePscEndpointMissing: return 36
      case .droppedInsidePscServiceProducer: return 37
      case .googleManagedServiceNoPscEndpoint: return 38
      case .loadBalancerHasNoProxySubnet: return 39
      case .cloudNatNoAddresses: return 40
      case .pscEndpointAccessedFromPeeredNetwork: return 41
      case .routeNextHopIpAddressNotResolved: return 42
      case .routeNextHopResourceNotFound: return 43
      case .noRouteFromInternetToPrivateIpv6Address: return 44
      case .vpnTunnelLocalSelectorMismatch: return 45
      case .vpnTunnelRemoteSelectorMismatch: return 46
      case .privateGoogleAccessViaVpnTunnelUnsupported: return 47
      case .pscNegProducerEndpointNoGlobalAccess: return 48
      case .routeNextHopInstanceWrongNetwork: return 49
      case .routeNextHopInstanceNonPrimaryIp: return 50
      case .routeNextHopForwardingRuleIpMismatch: return 51
      case .routeNextHopVpnTunnelNotEstablished: return 52
      case .routeNextHopForwardingRuleTypeInvalid: return 53
      case .pscNegProducerForwardingRuleMultiplePorts: return 54
      case .hybridNegNonDynamicRouteMatched: return 55
      case .hybridNegNonLocalDynamicRouteMatched: return 56
      case .noNatSubnetsForPscServiceAttachment: return 57
      case .cloudSqlPscNegUnsupported: return 58
      case .routingLoop: return 59
      case .vpcConnectorServerlessTrafficBlocked: return 60
      case .vpcConnectorHealthCheckTrafficBlocked: return 61
      case .droppedInsideGoogleManagedService: return 62
      case .cloudSqlConnectorRequired: return 63
      case .pscTransitivityNotPropagated: return 64
      case .loadBalancerBackendInvalidNetwork: return 65
      case .backendServiceNamedPortNotDefined: return 66
      case .destinationIsPrivateNatIpRange: return 67
      case .redisInstanceNotRunning: return 68
      case .redisClusterNotRunning: return 69
      case .droppedInsideRedisInstanceService: return 70
      case .redisInstanceUnsupportedPort: return 71
      case .redisInstanceConnectingFromPupiAddress: return 72
      case .redisInstanceNoRouteToDestinationNetwork: return 73
      case .redisInstanceNoExternalIp: return 74
      case .droppedInsideRedisClusterService: return 75
      case .redisClusterUnsupportedPort: return 76
      case .redisClusterNoExternalIp: return 77
      case .redisInstanceUnsupportedProtocol: return 78
      case .redisClusterUnsupportedProtocol: return 79
      case .noAdvertisedRouteToGcpDestination: return 80
      case .noTrafficSelectorToGcpDestination: return 81
      case .noKnownRouteFromPeeredNetworkToDestination: return 82
      case .privateNatToPscEndpointUnsupported: return 83
      case .ingressFirewallTagsUnsupportedByDirectVpcEgress: return 85
      case .pscPortMappingPortMismatch: return 86
      case .pscPortMappingWithoutPscConnectionUnsupported: return 87
      case .unsupportedRouteMatchedForNat64Destination: return 88
      case .trafficFromHybridEndpointToInternetDisallowed: return 89
      case .noMatchingNat64Gateway: return 90
      case .loadBalancerBackendIpVersionMismatch: return 96
      case .noKnownRouteFromNccNetworkToDestination: return 97
      case .noRouteFromExternalIpv6SourceToPrivateIpv6Address: return 98
      case .cloudNatProtocolUnsupported: return 99
      case .l2InterconnectUnsupportedProtocol: return 100
      case .l2InterconnectUnsupportedPort: return 101
      case .l2InterconnectDestinationIpMismatch: return 102
      case .gkePodNotRunning: return 103
      case .nccRouteWithinHybridSubnetUnsupported: return 104
      case .hybridSubnetRegionMismatch: return 105
      case .hybridSubnetNoRoute: return 106
      case .noConfiguredPrivateNat64Rule: return 107
      case .gkeNetworkPolicy: return 108
      case .noRouteFromInternetToPrivateIpv4Address: return 109
      case .noValidRouteFromGoogleManagedNetworkToDestination: return 110
      case .privateConnectionNoRunningInstance: return 111
      case .cloudRunJobNotReady: return 113
      case .droppedInsideDmsPrivateConnection: return 114
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CAUSE_UNSPECIFIED"
      case .unknownExternalAddress: return "UNKNOWN_EXTERNAL_ADDRESS"
      case .foreignIpDisallowed: return "FOREIGN_IP_DISALLOWED"
      case .firewallRule: return "FIREWALL_RULE"
      case .noRoute: return "NO_ROUTE"
      case .routeBlackhole: return "ROUTE_BLACKHOLE"
      case .routeWrongNetwork: return "ROUTE_WRONG_NETWORK"
      case .privateTrafficToInternet: return "PRIVATE_TRAFFIC_TO_INTERNET"
      case .privateGoogleAccessDisallowed: return "PRIVATE_GOOGLE_ACCESS_DISALLOWED"
      case .noExternalAddress: return "NO_EXTERNAL_ADDRESS"
      case .unknownInternalAddress: return "UNKNOWN_INTERNAL_ADDRESS"
      case .forwardingRuleMismatch: return "FORWARDING_RULE_MISMATCH"
      case .forwardingRuleNoInstances: return "FORWARDING_RULE_NO_INSTANCES"
      case .firewallBlockingLoadBalancerBackendHealthCheck:
        return "FIREWALL_BLOCKING_LOAD_BALANCER_BACKEND_HEALTH_CHECK"
      case .instanceNotRunning: return "INSTANCE_NOT_RUNNING"
      case .trafficTypeBlocked: return "TRAFFIC_TYPE_BLOCKED"
      case .gkeMasterUnauthorizedAccess: return "GKE_MASTER_UNAUTHORIZED_ACCESS"
      case .cloudSqlInstanceUnauthorizedAccess: return "CLOUD_SQL_INSTANCE_UNAUTHORIZED_ACCESS"
      case .droppedInsideGkeService: return "DROPPED_INSIDE_GKE_SERVICE"
      case .droppedInsideCloudSqlService: return "DROPPED_INSIDE_CLOUD_SQL_SERVICE"
      case .googleManagedServiceNoPeering: return "GOOGLE_MANAGED_SERVICE_NO_PEERING"
      case .cloudSqlInstanceNoIpAddress: return "CLOUD_SQL_INSTANCE_NO_IP_ADDRESS"
      case .cloudFunctionNotActive: return "CLOUD_FUNCTION_NOT_ACTIVE"
      case .vpcConnectorNotSet: return "VPC_CONNECTOR_NOT_SET"
      case .vpcConnectorNotRunning: return "VPC_CONNECTOR_NOT_RUNNING"
      case .forwardingRuleRegionMismatch: return "FORWARDING_RULE_REGION_MISMATCH"
      case .pscConnectionNotAccepted: return "PSC_CONNECTION_NOT_ACCEPTED"
      case .gkeClusterNotRunning: return "GKE_CLUSTER_NOT_RUNNING"
      case .cloudSqlInstanceNotRunning: return "CLOUD_SQL_INSTANCE_NOT_RUNNING"
      case .cloudRunRevisionNotReady: return "CLOUD_RUN_REVISION_NOT_READY"
      case .gkeControlPlaneRegionMismatch: return "GKE_CONTROL_PLANE_REGION_MISMATCH"
      case .publicGkeControlPlaneToPrivateDestination:
        return "PUBLIC_GKE_CONTROL_PLANE_TO_PRIVATE_DESTINATION"
      case .gkeControlPlaneNoRoute: return "GKE_CONTROL_PLANE_NO_ROUTE"
      case .cloudSqlInstanceNotConfiguredForExternalTraffic:
        return "CLOUD_SQL_INSTANCE_NOT_CONFIGURED_FOR_EXTERNAL_TRAFFIC"
      case .publicCloudSqlInstanceToPrivateDestination:
        return "PUBLIC_CLOUD_SQL_INSTANCE_TO_PRIVATE_DESTINATION"
      case .cloudSqlInstanceNoRoute: return "CLOUD_SQL_INSTANCE_NO_ROUTE"
      case .gkePscEndpointMissing: return "GKE_PSC_ENDPOINT_MISSING"
      case .droppedInsidePscServiceProducer: return "DROPPED_INSIDE_PSC_SERVICE_PRODUCER"
      case .googleManagedServiceNoPscEndpoint: return "GOOGLE_MANAGED_SERVICE_NO_PSC_ENDPOINT"
      case .loadBalancerHasNoProxySubnet: return "LOAD_BALANCER_HAS_NO_PROXY_SUBNET"
      case .cloudNatNoAddresses: return "CLOUD_NAT_NO_ADDRESSES"
      case .pscEndpointAccessedFromPeeredNetwork: return "PSC_ENDPOINT_ACCESSED_FROM_PEERED_NETWORK"
      case .routeNextHopIpAddressNotResolved: return "ROUTE_NEXT_HOP_IP_ADDRESS_NOT_RESOLVED"
      case .routeNextHopResourceNotFound: return "ROUTE_NEXT_HOP_RESOURCE_NOT_FOUND"
      case .noRouteFromInternetToPrivateIpv6Address:
        return "NO_ROUTE_FROM_INTERNET_TO_PRIVATE_IPV6_ADDRESS"
      case .vpnTunnelLocalSelectorMismatch: return "VPN_TUNNEL_LOCAL_SELECTOR_MISMATCH"
      case .vpnTunnelRemoteSelectorMismatch: return "VPN_TUNNEL_REMOTE_SELECTOR_MISMATCH"
      case .privateGoogleAccessViaVpnTunnelUnsupported:
        return "PRIVATE_GOOGLE_ACCESS_VIA_VPN_TUNNEL_UNSUPPORTED"
      case .pscNegProducerEndpointNoGlobalAccess:
        return "PSC_NEG_PRODUCER_ENDPOINT_NO_GLOBAL_ACCESS"
      case .routeNextHopInstanceWrongNetwork: return "ROUTE_NEXT_HOP_INSTANCE_WRONG_NETWORK"
      case .routeNextHopInstanceNonPrimaryIp: return "ROUTE_NEXT_HOP_INSTANCE_NON_PRIMARY_IP"
      case .routeNextHopForwardingRuleIpMismatch:
        return "ROUTE_NEXT_HOP_FORWARDING_RULE_IP_MISMATCH"
      case .routeNextHopVpnTunnelNotEstablished: return "ROUTE_NEXT_HOP_VPN_TUNNEL_NOT_ESTABLISHED"
      case .routeNextHopForwardingRuleTypeInvalid:
        return "ROUTE_NEXT_HOP_FORWARDING_RULE_TYPE_INVALID"
      case .pscNegProducerForwardingRuleMultiplePorts:
        return "PSC_NEG_PRODUCER_FORWARDING_RULE_MULTIPLE_PORTS"
      case .hybridNegNonDynamicRouteMatched: return "HYBRID_NEG_NON_DYNAMIC_ROUTE_MATCHED"
      case .hybridNegNonLocalDynamicRouteMatched:
        return "HYBRID_NEG_NON_LOCAL_DYNAMIC_ROUTE_MATCHED"
      case .noNatSubnetsForPscServiceAttachment: return "NO_NAT_SUBNETS_FOR_PSC_SERVICE_ATTACHMENT"
      case .cloudSqlPscNegUnsupported: return "CLOUD_SQL_PSC_NEG_UNSUPPORTED"
      case .routingLoop: return "ROUTING_LOOP"
      case .vpcConnectorServerlessTrafficBlocked: return "VPC_CONNECTOR_SERVERLESS_TRAFFIC_BLOCKED"
      case .vpcConnectorHealthCheckTrafficBlocked:
        return "VPC_CONNECTOR_HEALTH_CHECK_TRAFFIC_BLOCKED"
      case .droppedInsideGoogleManagedService: return "DROPPED_INSIDE_GOOGLE_MANAGED_SERVICE"
      case .cloudSqlConnectorRequired: return "CLOUD_SQL_CONNECTOR_REQUIRED"
      case .pscTransitivityNotPropagated: return "PSC_TRANSITIVITY_NOT_PROPAGATED"
      case .loadBalancerBackendInvalidNetwork: return "LOAD_BALANCER_BACKEND_INVALID_NETWORK"
      case .backendServiceNamedPortNotDefined: return "BACKEND_SERVICE_NAMED_PORT_NOT_DEFINED"
      case .destinationIsPrivateNatIpRange: return "DESTINATION_IS_PRIVATE_NAT_IP_RANGE"
      case .redisInstanceNotRunning: return "REDIS_INSTANCE_NOT_RUNNING"
      case .redisClusterNotRunning: return "REDIS_CLUSTER_NOT_RUNNING"
      case .droppedInsideRedisInstanceService: return "DROPPED_INSIDE_REDIS_INSTANCE_SERVICE"
      case .redisInstanceUnsupportedPort: return "REDIS_INSTANCE_UNSUPPORTED_PORT"
      case .redisInstanceConnectingFromPupiAddress:
        return "REDIS_INSTANCE_CONNECTING_FROM_PUPI_ADDRESS"
      case .redisInstanceNoRouteToDestinationNetwork:
        return "REDIS_INSTANCE_NO_ROUTE_TO_DESTINATION_NETWORK"
      case .redisInstanceNoExternalIp: return "REDIS_INSTANCE_NO_EXTERNAL_IP"
      case .droppedInsideRedisClusterService: return "DROPPED_INSIDE_REDIS_CLUSTER_SERVICE"
      case .redisClusterUnsupportedPort: return "REDIS_CLUSTER_UNSUPPORTED_PORT"
      case .redisClusterNoExternalIp: return "REDIS_CLUSTER_NO_EXTERNAL_IP"
      case .redisInstanceUnsupportedProtocol: return "REDIS_INSTANCE_UNSUPPORTED_PROTOCOL"
      case .redisClusterUnsupportedProtocol: return "REDIS_CLUSTER_UNSUPPORTED_PROTOCOL"
      case .noAdvertisedRouteToGcpDestination: return "NO_ADVERTISED_ROUTE_TO_GCP_DESTINATION"
      case .noTrafficSelectorToGcpDestination: return "NO_TRAFFIC_SELECTOR_TO_GCP_DESTINATION"
      case .noKnownRouteFromPeeredNetworkToDestination:
        return "NO_KNOWN_ROUTE_FROM_PEERED_NETWORK_TO_DESTINATION"
      case .privateNatToPscEndpointUnsupported: return "PRIVATE_NAT_TO_PSC_ENDPOINT_UNSUPPORTED"
      case .ingressFirewallTagsUnsupportedByDirectVpcEgress:
        return "INGRESS_FIREWALL_TAGS_UNSUPPORTED_BY_DIRECT_VPC_EGRESS"
      case .pscPortMappingPortMismatch: return "PSC_PORT_MAPPING_PORT_MISMATCH"
      case .pscPortMappingWithoutPscConnectionUnsupported:
        return "PSC_PORT_MAPPING_WITHOUT_PSC_CONNECTION_UNSUPPORTED"
      case .unsupportedRouteMatchedForNat64Destination:
        return "UNSUPPORTED_ROUTE_MATCHED_FOR_NAT64_DESTINATION"
      case .trafficFromHybridEndpointToInternetDisallowed:
        return "TRAFFIC_FROM_HYBRID_ENDPOINT_TO_INTERNET_DISALLOWED"
      case .noMatchingNat64Gateway: return "NO_MATCHING_NAT64_GATEWAY"
      case .loadBalancerBackendIpVersionMismatch: return "LOAD_BALANCER_BACKEND_IP_VERSION_MISMATCH"
      case .noKnownRouteFromNccNetworkToDestination:
        return "NO_KNOWN_ROUTE_FROM_NCC_NETWORK_TO_DESTINATION"
      case .noRouteFromExternalIpv6SourceToPrivateIpv6Address:
        return "NO_ROUTE_FROM_EXTERNAL_IPV6_SOURCE_TO_PRIVATE_IPV6_ADDRESS"
      case .cloudNatProtocolUnsupported: return "CLOUD_NAT_PROTOCOL_UNSUPPORTED"
      case .l2InterconnectUnsupportedProtocol: return "L2_INTERCONNECT_UNSUPPORTED_PROTOCOL"
      case .l2InterconnectUnsupportedPort: return "L2_INTERCONNECT_UNSUPPORTED_PORT"
      case .l2InterconnectDestinationIpMismatch: return "L2_INTERCONNECT_DESTINATION_IP_MISMATCH"
      case .gkePodNotRunning: return "GKE_POD_NOT_RUNNING"
      case .nccRouteWithinHybridSubnetUnsupported:
        return "NCC_ROUTE_WITHIN_HYBRID_SUBNET_UNSUPPORTED"
      case .hybridSubnetRegionMismatch: return "HYBRID_SUBNET_REGION_MISMATCH"
      case .hybridSubnetNoRoute: return "HYBRID_SUBNET_NO_ROUTE"
      case .noConfiguredPrivateNat64Rule: return "NO_CONFIGURED_PRIVATE_NAT64_RULE"
      case .gkeNetworkPolicy: return "GKE_NETWORK_POLICY"
      case .noRouteFromInternetToPrivateIpv4Address:
        return "NO_ROUTE_FROM_INTERNET_TO_PRIVATE_IPV4_ADDRESS"
      case .noValidRouteFromGoogleManagedNetworkToDestination:
        return "NO_VALID_ROUTE_FROM_GOOGLE_MANAGED_NETWORK_TO_DESTINATION"
      case .privateConnectionNoRunningInstance: return "PRIVATE_CONNECTION_NO_RUNNING_INSTANCE"
      case .cloudRunJobNotReady: return "CLOUD_RUN_JOB_NOT_READY"
      case .droppedInsideDmsPrivateConnection: return "DROPPED_INSIDE_DMS_PRIVATE_CONNECTION"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Cause/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CAUSE_UNSPECIFIED": self = .unspecified
      case "UNKNOWN_EXTERNAL_ADDRESS": self = .unknownExternalAddress
      case "FOREIGN_IP_DISALLOWED": self = .foreignIpDisallowed
      case "FIREWALL_RULE": self = .firewallRule
      case "NO_ROUTE": self = .noRoute
      case "ROUTE_BLACKHOLE": self = .routeBlackhole
      case "ROUTE_WRONG_NETWORK": self = .routeWrongNetwork
      case "ROUTE_NEXT_HOP_IP_ADDRESS_NOT_RESOLVED": self = .routeNextHopIpAddressNotResolved
      case "ROUTE_NEXT_HOP_RESOURCE_NOT_FOUND": self = .routeNextHopResourceNotFound
      case "ROUTE_NEXT_HOP_INSTANCE_WRONG_NETWORK": self = .routeNextHopInstanceWrongNetwork
      case "ROUTE_NEXT_HOP_INSTANCE_NON_PRIMARY_IP": self = .routeNextHopInstanceNonPrimaryIp
      case "ROUTE_NEXT_HOP_FORWARDING_RULE_IP_MISMATCH":
        self = .routeNextHopForwardingRuleIpMismatch
      case "ROUTE_NEXT_HOP_VPN_TUNNEL_NOT_ESTABLISHED": self = .routeNextHopVpnTunnelNotEstablished
      case "ROUTE_NEXT_HOP_FORWARDING_RULE_TYPE_INVALID":
        self = .routeNextHopForwardingRuleTypeInvalid
      case "NO_ROUTE_FROM_INTERNET_TO_PRIVATE_IPV6_ADDRESS":
        self = .noRouteFromInternetToPrivateIpv6Address
      case "NO_ROUTE_FROM_INTERNET_TO_PRIVATE_IPV4_ADDRESS":
        self = .noRouteFromInternetToPrivateIpv4Address
      case "NO_ROUTE_FROM_EXTERNAL_IPV6_SOURCE_TO_PRIVATE_IPV6_ADDRESS":
        self = .noRouteFromExternalIpv6SourceToPrivateIpv6Address
      case "VPN_TUNNEL_LOCAL_SELECTOR_MISMATCH": self = .vpnTunnelLocalSelectorMismatch
      case "VPN_TUNNEL_REMOTE_SELECTOR_MISMATCH": self = .vpnTunnelRemoteSelectorMismatch
      case "PRIVATE_TRAFFIC_TO_INTERNET": self = .privateTrafficToInternet
      case "PRIVATE_GOOGLE_ACCESS_DISALLOWED": self = .privateGoogleAccessDisallowed
      case "PRIVATE_GOOGLE_ACCESS_VIA_VPN_TUNNEL_UNSUPPORTED":
        self = .privateGoogleAccessViaVpnTunnelUnsupported
      case "NO_EXTERNAL_ADDRESS": self = .noExternalAddress
      case "UNKNOWN_INTERNAL_ADDRESS": self = .unknownInternalAddress
      case "FORWARDING_RULE_MISMATCH": self = .forwardingRuleMismatch
      case "FORWARDING_RULE_NO_INSTANCES": self = .forwardingRuleNoInstances
      case "FIREWALL_BLOCKING_LOAD_BALANCER_BACKEND_HEALTH_CHECK":
        self = .firewallBlockingLoadBalancerBackendHealthCheck
      case "INGRESS_FIREWALL_TAGS_UNSUPPORTED_BY_DIRECT_VPC_EGRESS":
        self = .ingressFirewallTagsUnsupportedByDirectVpcEgress
      case "INSTANCE_NOT_RUNNING": self = .instanceNotRunning
      case "GKE_CLUSTER_NOT_RUNNING": self = .gkeClusterNotRunning
      case "GKE_POD_NOT_RUNNING": self = .gkePodNotRunning
      case "CLOUD_SQL_INSTANCE_NOT_RUNNING": self = .cloudSqlInstanceNotRunning
      case "REDIS_INSTANCE_NOT_RUNNING": self = .redisInstanceNotRunning
      case "REDIS_CLUSTER_NOT_RUNNING": self = .redisClusterNotRunning
      case "TRAFFIC_TYPE_BLOCKED": self = .trafficTypeBlocked
      case "GKE_MASTER_UNAUTHORIZED_ACCESS": self = .gkeMasterUnauthorizedAccess
      case "CLOUD_SQL_INSTANCE_UNAUTHORIZED_ACCESS": self = .cloudSqlInstanceUnauthorizedAccess
      case "DROPPED_INSIDE_GKE_SERVICE": self = .droppedInsideGkeService
      case "DROPPED_INSIDE_CLOUD_SQL_SERVICE": self = .droppedInsideCloudSqlService
      case "DROPPED_INSIDE_DMS_PRIVATE_CONNECTION": self = .droppedInsideDmsPrivateConnection
      case "GOOGLE_MANAGED_SERVICE_NO_PEERING": self = .googleManagedServiceNoPeering
      case "GOOGLE_MANAGED_SERVICE_NO_PSC_ENDPOINT": self = .googleManagedServiceNoPscEndpoint
      case "GKE_PSC_ENDPOINT_MISSING": self = .gkePscEndpointMissing
      case "CLOUD_SQL_INSTANCE_NO_IP_ADDRESS": self = .cloudSqlInstanceNoIpAddress
      case "GKE_CONTROL_PLANE_REGION_MISMATCH": self = .gkeControlPlaneRegionMismatch
      case "PUBLIC_GKE_CONTROL_PLANE_TO_PRIVATE_DESTINATION":
        self = .publicGkeControlPlaneToPrivateDestination
      case "GKE_CONTROL_PLANE_NO_ROUTE": self = .gkeControlPlaneNoRoute
      case "CLOUD_SQL_INSTANCE_NOT_CONFIGURED_FOR_EXTERNAL_TRAFFIC":
        self = .cloudSqlInstanceNotConfiguredForExternalTraffic
      case "PUBLIC_CLOUD_SQL_INSTANCE_TO_PRIVATE_DESTINATION":
        self = .publicCloudSqlInstanceToPrivateDestination
      case "CLOUD_SQL_INSTANCE_NO_ROUTE": self = .cloudSqlInstanceNoRoute
      case "CLOUD_SQL_CONNECTOR_REQUIRED": self = .cloudSqlConnectorRequired
      case "CLOUD_FUNCTION_NOT_ACTIVE": self = .cloudFunctionNotActive
      case "VPC_CONNECTOR_NOT_SET": self = .vpcConnectorNotSet
      case "VPC_CONNECTOR_NOT_RUNNING": self = .vpcConnectorNotRunning
      case "VPC_CONNECTOR_SERVERLESS_TRAFFIC_BLOCKED": self = .vpcConnectorServerlessTrafficBlocked
      case "VPC_CONNECTOR_HEALTH_CHECK_TRAFFIC_BLOCKED":
        self = .vpcConnectorHealthCheckTrafficBlocked
      case "FORWARDING_RULE_REGION_MISMATCH": self = .forwardingRuleRegionMismatch
      case "PSC_CONNECTION_NOT_ACCEPTED": self = .pscConnectionNotAccepted
      case "PSC_ENDPOINT_ACCESSED_FROM_PEERED_NETWORK": self = .pscEndpointAccessedFromPeeredNetwork
      case "PSC_NEG_PRODUCER_ENDPOINT_NO_GLOBAL_ACCESS":
        self = .pscNegProducerEndpointNoGlobalAccess
      case "PSC_NEG_PRODUCER_FORWARDING_RULE_MULTIPLE_PORTS":
        self = .pscNegProducerForwardingRuleMultiplePorts
      case "CLOUD_SQL_PSC_NEG_UNSUPPORTED": self = .cloudSqlPscNegUnsupported
      case "NO_NAT_SUBNETS_FOR_PSC_SERVICE_ATTACHMENT": self = .noNatSubnetsForPscServiceAttachment
      case "PSC_TRANSITIVITY_NOT_PROPAGATED": self = .pscTransitivityNotPropagated
      case "HYBRID_NEG_NON_DYNAMIC_ROUTE_MATCHED": self = .hybridNegNonDynamicRouteMatched
      case "HYBRID_NEG_NON_LOCAL_DYNAMIC_ROUTE_MATCHED":
        self = .hybridNegNonLocalDynamicRouteMatched
      case "CLOUD_RUN_REVISION_NOT_READY": self = .cloudRunRevisionNotReady
      case "CLOUD_RUN_JOB_NOT_READY": self = .cloudRunJobNotReady
      case "DROPPED_INSIDE_PSC_SERVICE_PRODUCER": self = .droppedInsidePscServiceProducer
      case "LOAD_BALANCER_HAS_NO_PROXY_SUBNET": self = .loadBalancerHasNoProxySubnet
      case "CLOUD_NAT_NO_ADDRESSES": self = .cloudNatNoAddresses
      case "ROUTING_LOOP": self = .routingLoop
      case "DROPPED_INSIDE_GOOGLE_MANAGED_SERVICE": self = .droppedInsideGoogleManagedService
      case "LOAD_BALANCER_BACKEND_INVALID_NETWORK": self = .loadBalancerBackendInvalidNetwork
      case "BACKEND_SERVICE_NAMED_PORT_NOT_DEFINED": self = .backendServiceNamedPortNotDefined
      case "DESTINATION_IS_PRIVATE_NAT_IP_RANGE": self = .destinationIsPrivateNatIpRange
      case "DROPPED_INSIDE_REDIS_INSTANCE_SERVICE": self = .droppedInsideRedisInstanceService
      case "REDIS_INSTANCE_UNSUPPORTED_PORT": self = .redisInstanceUnsupportedPort
      case "REDIS_INSTANCE_CONNECTING_FROM_PUPI_ADDRESS":
        self = .redisInstanceConnectingFromPupiAddress
      case "REDIS_INSTANCE_NO_ROUTE_TO_DESTINATION_NETWORK":
        self = .redisInstanceNoRouteToDestinationNetwork
      case "REDIS_INSTANCE_NO_EXTERNAL_IP": self = .redisInstanceNoExternalIp
      case "REDIS_INSTANCE_UNSUPPORTED_PROTOCOL": self = .redisInstanceUnsupportedProtocol
      case "DROPPED_INSIDE_REDIS_CLUSTER_SERVICE": self = .droppedInsideRedisClusterService
      case "REDIS_CLUSTER_UNSUPPORTED_PORT": self = .redisClusterUnsupportedPort
      case "REDIS_CLUSTER_NO_EXTERNAL_IP": self = .redisClusterNoExternalIp
      case "REDIS_CLUSTER_UNSUPPORTED_PROTOCOL": self = .redisClusterUnsupportedProtocol
      case "NO_ADVERTISED_ROUTE_TO_GCP_DESTINATION": self = .noAdvertisedRouteToGcpDestination
      case "NO_TRAFFIC_SELECTOR_TO_GCP_DESTINATION": self = .noTrafficSelectorToGcpDestination
      case "NO_KNOWN_ROUTE_FROM_PEERED_NETWORK_TO_DESTINATION":
        self = .noKnownRouteFromPeeredNetworkToDestination
      case "PRIVATE_NAT_TO_PSC_ENDPOINT_UNSUPPORTED": self = .privateNatToPscEndpointUnsupported
      case "PSC_PORT_MAPPING_PORT_MISMATCH": self = .pscPortMappingPortMismatch
      case "PSC_PORT_MAPPING_WITHOUT_PSC_CONNECTION_UNSUPPORTED":
        self = .pscPortMappingWithoutPscConnectionUnsupported
      case "UNSUPPORTED_ROUTE_MATCHED_FOR_NAT64_DESTINATION":
        self = .unsupportedRouteMatchedForNat64Destination
      case "TRAFFIC_FROM_HYBRID_ENDPOINT_TO_INTERNET_DISALLOWED":
        self = .trafficFromHybridEndpointToInternetDisallowed
      case "NO_MATCHING_NAT64_GATEWAY": self = .noMatchingNat64Gateway
      case "NO_CONFIGURED_PRIVATE_NAT64_RULE": self = .noConfiguredPrivateNat64Rule
      case "LOAD_BALANCER_BACKEND_IP_VERSION_MISMATCH": self = .loadBalancerBackendIpVersionMismatch
      case "NO_KNOWN_ROUTE_FROM_NCC_NETWORK_TO_DESTINATION":
        self = .noKnownRouteFromNccNetworkToDestination
      case "CLOUD_NAT_PROTOCOL_UNSUPPORTED": self = .cloudNatProtocolUnsupported
      case "L2_INTERCONNECT_UNSUPPORTED_PROTOCOL": self = .l2InterconnectUnsupportedProtocol
      case "L2_INTERCONNECT_UNSUPPORTED_PORT": self = .l2InterconnectUnsupportedPort
      case "L2_INTERCONNECT_DESTINATION_IP_MISMATCH": self = .l2InterconnectDestinationIpMismatch
      case "NCC_ROUTE_WITHIN_HYBRID_SUBNET_UNSUPPORTED":
        self = .nccRouteWithinHybridSubnetUnsupported
      case "HYBRID_SUBNET_REGION_MISMATCH": self = .hybridSubnetRegionMismatch
      case "HYBRID_SUBNET_NO_ROUTE": self = .hybridSubnetNoRoute
      case "GKE_NETWORK_POLICY": self = .gkeNetworkPolicy
      case "NO_VALID_ROUTE_FROM_GOOGLE_MANAGED_NETWORK_TO_DESTINATION":
        self = .noValidRouteFromGoogleManagedNetworkToDestination
      case "PRIVATE_CONNECTION_NO_RUNNING_INSTANCE": self = .privateConnectionNoRunningInstance
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Cause/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .unknownExternalAddress
      case 2: self = .foreignIpDisallowed
      case 3: self = .firewallRule
      case 4: self = .noRoute
      case 5: self = .routeBlackhole
      case 6: self = .routeWrongNetwork
      case 7: self = .privateTrafficToInternet
      case 8: self = .privateGoogleAccessDisallowed
      case 9: self = .noExternalAddress
      case 10: self = .unknownInternalAddress
      case 11: self = .forwardingRuleMismatch
      case 12: self = .forwardingRuleNoInstances
      case 13: self = .firewallBlockingLoadBalancerBackendHealthCheck
      case 14: self = .instanceNotRunning
      case 15: self = .trafficTypeBlocked
      case 16: self = .gkeMasterUnauthorizedAccess
      case 17: self = .cloudSqlInstanceUnauthorizedAccess
      case 18: self = .droppedInsideGkeService
      case 19: self = .droppedInsideCloudSqlService
      case 20: self = .googleManagedServiceNoPeering
      case 21: self = .cloudSqlInstanceNoIpAddress
      case 22: self = .cloudFunctionNotActive
      case 23: self = .vpcConnectorNotSet
      case 24: self = .vpcConnectorNotRunning
      case 25: self = .forwardingRuleRegionMismatch
      case 26: self = .pscConnectionNotAccepted
      case 27: self = .gkeClusterNotRunning
      case 28: self = .cloudSqlInstanceNotRunning
      case 29: self = .cloudRunRevisionNotReady
      case 30: self = .gkeControlPlaneRegionMismatch
      case 31: self = .publicGkeControlPlaneToPrivateDestination
      case 32: self = .gkeControlPlaneNoRoute
      case 33: self = .cloudSqlInstanceNotConfiguredForExternalTraffic
      case 34: self = .publicCloudSqlInstanceToPrivateDestination
      case 35: self = .cloudSqlInstanceNoRoute
      case 36: self = .gkePscEndpointMissing
      case 37: self = .droppedInsidePscServiceProducer
      case 38: self = .googleManagedServiceNoPscEndpoint
      case 39: self = .loadBalancerHasNoProxySubnet
      case 40: self = .cloudNatNoAddresses
      case 41: self = .pscEndpointAccessedFromPeeredNetwork
      case 42: self = .routeNextHopIpAddressNotResolved
      case 43: self = .routeNextHopResourceNotFound
      case 44: self = .noRouteFromInternetToPrivateIpv6Address
      case 45: self = .vpnTunnelLocalSelectorMismatch
      case 46: self = .vpnTunnelRemoteSelectorMismatch
      case 47: self = .privateGoogleAccessViaVpnTunnelUnsupported
      case 48: self = .pscNegProducerEndpointNoGlobalAccess
      case 49: self = .routeNextHopInstanceWrongNetwork
      case 50: self = .routeNextHopInstanceNonPrimaryIp
      case 51: self = .routeNextHopForwardingRuleIpMismatch
      case 52: self = .routeNextHopVpnTunnelNotEstablished
      case 53: self = .routeNextHopForwardingRuleTypeInvalid
      case 54: self = .pscNegProducerForwardingRuleMultiplePorts
      case 55: self = .hybridNegNonDynamicRouteMatched
      case 56: self = .hybridNegNonLocalDynamicRouteMatched
      case 57: self = .noNatSubnetsForPscServiceAttachment
      case 58: self = .cloudSqlPscNegUnsupported
      case 59: self = .routingLoop
      case 60: self = .vpcConnectorServerlessTrafficBlocked
      case 61: self = .vpcConnectorHealthCheckTrafficBlocked
      case 62: self = .droppedInsideGoogleManagedService
      case 63: self = .cloudSqlConnectorRequired
      case 64: self = .pscTransitivityNotPropagated
      case 65: self = .loadBalancerBackendInvalidNetwork
      case 66: self = .backendServiceNamedPortNotDefined
      case 67: self = .destinationIsPrivateNatIpRange
      case 68: self = .redisInstanceNotRunning
      case 69: self = .redisClusterNotRunning
      case 70: self = .droppedInsideRedisInstanceService
      case 71: self = .redisInstanceUnsupportedPort
      case 72: self = .redisInstanceConnectingFromPupiAddress
      case 73: self = .redisInstanceNoRouteToDestinationNetwork
      case 74: self = .redisInstanceNoExternalIp
      case 75: self = .droppedInsideRedisClusterService
      case 76: self = .redisClusterUnsupportedPort
      case 77: self = .redisClusterNoExternalIp
      case 78: self = .redisInstanceUnsupportedProtocol
      case 79: self = .redisClusterUnsupportedProtocol
      case 80: self = .noAdvertisedRouteToGcpDestination
      case 81: self = .noTrafficSelectorToGcpDestination
      case 82: self = .noKnownRouteFromPeeredNetworkToDestination
      case 83: self = .privateNatToPscEndpointUnsupported
      case 85: self = .ingressFirewallTagsUnsupportedByDirectVpcEgress
      case 86: self = .pscPortMappingPortMismatch
      case 87: self = .pscPortMappingWithoutPscConnectionUnsupported
      case 88: self = .unsupportedRouteMatchedForNat64Destination
      case 89: self = .trafficFromHybridEndpointToInternetDisallowed
      case 90: self = .noMatchingNat64Gateway
      case 96: self = .loadBalancerBackendIpVersionMismatch
      case 97: self = .noKnownRouteFromNccNetworkToDestination
      case 98: self = .noRouteFromExternalIpv6SourceToPrivateIpv6Address
      case 99: self = .cloudNatProtocolUnsupported
      case 100: self = .l2InterconnectUnsupportedProtocol
      case 101: self = .l2InterconnectUnsupportedPort
      case 102: self = .l2InterconnectDestinationIpMismatch
      case 103: self = .gkePodNotRunning
      case 104: self = .nccRouteWithinHybridSubnetUnsupported
      case 105: self = .hybridSubnetRegionMismatch
      case 106: self = .hybridSubnetNoRoute
      case 107: self = .noConfiguredPrivateNat64Rule
      case 108: self = .gkeNetworkPolicy
      case 109: self = .noRouteFromInternetToPrivateIpv4Address
      case 110: self = .noValidRouteFromGoogleManagedNetworkToDestination
      case 111: self = .privateConnectionNoRunningInstance
      case 113: self = .cloudRunJobNotReady
      case 114: self = .droppedInsideDmsPrivateConnection
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .unknownExternalAddress: return try container.encode(1)
      case .foreignIpDisallowed: return try container.encode(2)
      case .firewallRule: return try container.encode(3)
      case .noRoute: return try container.encode(4)
      case .routeBlackhole: return try container.encode(5)
      case .routeWrongNetwork: return try container.encode(6)
      case .privateTrafficToInternet: return try container.encode(7)
      case .privateGoogleAccessDisallowed: return try container.encode(8)
      case .noExternalAddress: return try container.encode(9)
      case .unknownInternalAddress: return try container.encode(10)
      case .forwardingRuleMismatch: return try container.encode(11)
      case .forwardingRuleNoInstances: return try container.encode(12)
      case .firewallBlockingLoadBalancerBackendHealthCheck: return try container.encode(13)
      case .instanceNotRunning: return try container.encode(14)
      case .trafficTypeBlocked: return try container.encode(15)
      case .gkeMasterUnauthorizedAccess: return try container.encode(16)
      case .cloudSqlInstanceUnauthorizedAccess: return try container.encode(17)
      case .droppedInsideGkeService: return try container.encode(18)
      case .droppedInsideCloudSqlService: return try container.encode(19)
      case .googleManagedServiceNoPeering: return try container.encode(20)
      case .cloudSqlInstanceNoIpAddress: return try container.encode(21)
      case .cloudFunctionNotActive: return try container.encode(22)
      case .vpcConnectorNotSet: return try container.encode(23)
      case .vpcConnectorNotRunning: return try container.encode(24)
      case .forwardingRuleRegionMismatch: return try container.encode(25)
      case .pscConnectionNotAccepted: return try container.encode(26)
      case .gkeClusterNotRunning: return try container.encode(27)
      case .cloudSqlInstanceNotRunning: return try container.encode(28)
      case .cloudRunRevisionNotReady: return try container.encode(29)
      case .gkeControlPlaneRegionMismatch: return try container.encode(30)
      case .publicGkeControlPlaneToPrivateDestination: return try container.encode(31)
      case .gkeControlPlaneNoRoute: return try container.encode(32)
      case .cloudSqlInstanceNotConfiguredForExternalTraffic: return try container.encode(33)
      case .publicCloudSqlInstanceToPrivateDestination: return try container.encode(34)
      case .cloudSqlInstanceNoRoute: return try container.encode(35)
      case .gkePscEndpointMissing: return try container.encode(36)
      case .droppedInsidePscServiceProducer: return try container.encode(37)
      case .googleManagedServiceNoPscEndpoint: return try container.encode(38)
      case .loadBalancerHasNoProxySubnet: return try container.encode(39)
      case .cloudNatNoAddresses: return try container.encode(40)
      case .pscEndpointAccessedFromPeeredNetwork: return try container.encode(41)
      case .routeNextHopIpAddressNotResolved: return try container.encode(42)
      case .routeNextHopResourceNotFound: return try container.encode(43)
      case .noRouteFromInternetToPrivateIpv6Address: return try container.encode(44)
      case .vpnTunnelLocalSelectorMismatch: return try container.encode(45)
      case .vpnTunnelRemoteSelectorMismatch: return try container.encode(46)
      case .privateGoogleAccessViaVpnTunnelUnsupported: return try container.encode(47)
      case .pscNegProducerEndpointNoGlobalAccess: return try container.encode(48)
      case .routeNextHopInstanceWrongNetwork: return try container.encode(49)
      case .routeNextHopInstanceNonPrimaryIp: return try container.encode(50)
      case .routeNextHopForwardingRuleIpMismatch: return try container.encode(51)
      case .routeNextHopVpnTunnelNotEstablished: return try container.encode(52)
      case .routeNextHopForwardingRuleTypeInvalid: return try container.encode(53)
      case .pscNegProducerForwardingRuleMultiplePorts: return try container.encode(54)
      case .hybridNegNonDynamicRouteMatched: return try container.encode(55)
      case .hybridNegNonLocalDynamicRouteMatched: return try container.encode(56)
      case .noNatSubnetsForPscServiceAttachment: return try container.encode(57)
      case .cloudSqlPscNegUnsupported: return try container.encode(58)
      case .routingLoop: return try container.encode(59)
      case .vpcConnectorServerlessTrafficBlocked: return try container.encode(60)
      case .vpcConnectorHealthCheckTrafficBlocked: return try container.encode(61)
      case .droppedInsideGoogleManagedService: return try container.encode(62)
      case .cloudSqlConnectorRequired: return try container.encode(63)
      case .pscTransitivityNotPropagated: return try container.encode(64)
      case .loadBalancerBackendInvalidNetwork: return try container.encode(65)
      case .backendServiceNamedPortNotDefined: return try container.encode(66)
      case .destinationIsPrivateNatIpRange: return try container.encode(67)
      case .redisInstanceNotRunning: return try container.encode(68)
      case .redisClusterNotRunning: return try container.encode(69)
      case .droppedInsideRedisInstanceService: return try container.encode(70)
      case .redisInstanceUnsupportedPort: return try container.encode(71)
      case .redisInstanceConnectingFromPupiAddress: return try container.encode(72)
      case .redisInstanceNoRouteToDestinationNetwork: return try container.encode(73)
      case .redisInstanceNoExternalIp: return try container.encode(74)
      case .droppedInsideRedisClusterService: return try container.encode(75)
      case .redisClusterUnsupportedPort: return try container.encode(76)
      case .redisClusterNoExternalIp: return try container.encode(77)
      case .redisInstanceUnsupportedProtocol: return try container.encode(78)
      case .redisClusterUnsupportedProtocol: return try container.encode(79)
      case .noAdvertisedRouteToGcpDestination: return try container.encode(80)
      case .noTrafficSelectorToGcpDestination: return try container.encode(81)
      case .noKnownRouteFromPeeredNetworkToDestination: return try container.encode(82)
      case .privateNatToPscEndpointUnsupported: return try container.encode(83)
      case .ingressFirewallTagsUnsupportedByDirectVpcEgress: return try container.encode(85)
      case .pscPortMappingPortMismatch: return try container.encode(86)
      case .pscPortMappingWithoutPscConnectionUnsupported: return try container.encode(87)
      case .unsupportedRouteMatchedForNat64Destination: return try container.encode(88)
      case .trafficFromHybridEndpointToInternetDisallowed: return try container.encode(89)
      case .noMatchingNat64Gateway: return try container.encode(90)
      case .loadBalancerBackendIpVersionMismatch: return try container.encode(96)
      case .noKnownRouteFromNccNetworkToDestination: return try container.encode(97)
      case .noRouteFromExternalIpv6SourceToPrivateIpv6Address: return try container.encode(98)
      case .cloudNatProtocolUnsupported: return try container.encode(99)
      case .l2InterconnectUnsupportedProtocol: return try container.encode(100)
      case .l2InterconnectUnsupportedPort: return try container.encode(101)
      case .l2InterconnectDestinationIpMismatch: return try container.encode(102)
      case .gkePodNotRunning: return try container.encode(103)
      case .nccRouteWithinHybridSubnetUnsupported: return try container.encode(104)
      case .hybridSubnetRegionMismatch: return try container.encode(105)
      case .hybridSubnetNoRoute: return try container.encode(106)
      case .noConfiguredPrivateNat64Rule: return try container.encode(107)
      case .gkeNetworkPolicy: return try container.encode(108)
      case .noRouteFromInternetToPrivateIpv4Address: return try container.encode(109)
      case .noValidRouteFromGoogleManagedNetworkToDestination: return try container.encode(110)
      case .privateConnectionNoRunningInstance: return try container.encode(111)
      case .cloudRunJobNotReady: return try container.encode(113)
      case .droppedInsideDmsPrivateConnection: return try container.encode(114)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkmanagement.v1.DropInfo"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
