// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// For display only. Metadata associated with a Compute Engine forwarding rule.
public struct ForwardingRuleInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Name of the forwarding rule.
  public var displayName: Swift.String = Swift.String()

  /// URI of the forwarding rule.
  public var uri: Swift.String = Swift.String()

  /// Protocol defined in the forwarding rule that matches the packet.
  public var matchedProtocol: Swift.String = Swift.String()

  /// Port range defined in the forwarding rule that matches the packet.
  public var matchedPortRange: Swift.String = Swift.String()

  /// VIP of the forwarding rule.
  public var vip: Swift.String = Swift.String()

  /// Target type of the forwarding rule.
  public var target: Swift.String = Swift.String()

  /// Network URI.
  public var networkUri: Swift.String = Swift.String()

  /// Region of the forwarding rule. Set only for regional forwarding rules.
  public var region: Swift.String = Swift.String()

  /// Name of the load balancer the forwarding rule belongs to. Empty for
  /// forwarding rules not related to load balancers (like PSC forwarding rules).
  public var loadBalancerName: Swift.String = Swift.String()

  /// URI of the PSC service attachment this forwarding rule targets (if
  /// applicable).
  public var pscServiceAttachmentUri: Swift.String = Swift.String()

  /// PSC Google API target this forwarding rule targets (if applicable).
  public var pscGoogleApiTarget: Swift.String = Swift.String()

  /// Initialize a new instance of `ForwardingRuleInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ForwardingRuleInfo().with { $0.displayName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkmanagement.v1.ForwardingRuleInfo"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
