// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Details of the final state "forward" and associated resource.
public struct ForwardInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Target type where this packet is forwarded to.
  public var target: ForwardInfo.Target = ForwardInfo.Target()

  /// URI of the resource that the packet is forwarded to.
  public var resourceUri: Swift.String = Swift.String()

  /// IP address of the target (if applicable).
  public var ipAddress: Swift.String = Swift.String()

  /// Initialize a new instance of `ForwardInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ForwardInfo().with { $0.target = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Forward target types.
  public enum Target: Codable, Equatable, Sendable {
    /// Target not specified.
    case unspecified
    /// Forwarded to a VPC peering network.
    case peeringVpc
    /// Forwarded to a Cloud VPN gateway.
    case vpnGateway
    /// Forwarded to a Cloud Interconnect connection.
    case interconnect
    /// Forwarded to a Google Kubernetes Engine Container cluster master.
    @available(*, deprecated)
    case gkeMaster
    /// Forwarded to the next hop of a custom route imported from a peering VPC.
    case importedCustomRouteNextHop
    /// Forwarded to a Cloud SQL instance.
    @available(*, deprecated)
    case cloudSqlInstance
    /// Forwarded to a VPC network in another project.
    case anotherProject
    /// Forwarded to an NCC Hub.
    case nccHub
    /// Forwarded to a router appliance.
    case routerAppliance
    /// Forwarded to a Secure Web Proxy Gateway.
    case secureWebProxyGateway
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .peeringVpc: return 1
      case .vpnGateway: return 2
      case .interconnect: return 3
      case .gkeMaster: return 4
      case .importedCustomRouteNextHop: return 5
      case .cloudSqlInstance: return 6
      case .anotherProject: return 7
      case .nccHub: return 8
      case .routerAppliance: return 9
      case .secureWebProxyGateway: return 10
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TARGET_UNSPECIFIED"
      case .peeringVpc: return "PEERING_VPC"
      case .vpnGateway: return "VPN_GATEWAY"
      case .interconnect: return "INTERCONNECT"
      case .gkeMaster: return "GKE_MASTER"
      case .importedCustomRouteNextHop: return "IMPORTED_CUSTOM_ROUTE_NEXT_HOP"
      case .cloudSqlInstance: return "CLOUD_SQL_INSTANCE"
      case .anotherProject: return "ANOTHER_PROJECT"
      case .nccHub: return "NCC_HUB"
      case .routerAppliance: return "ROUTER_APPLIANCE"
      case .secureWebProxyGateway: return "SECURE_WEB_PROXY_GATEWAY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Target/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TARGET_UNSPECIFIED": self = .unspecified
      case "PEERING_VPC": self = .peeringVpc
      case "VPN_GATEWAY": self = .vpnGateway
      case "INTERCONNECT": self = .interconnect
      case "GKE_MASTER": self = .gkeMaster
      case "IMPORTED_CUSTOM_ROUTE_NEXT_HOP": self = .importedCustomRouteNextHop
      case "CLOUD_SQL_INSTANCE": self = .cloudSqlInstance
      case "ANOTHER_PROJECT": self = .anotherProject
      case "NCC_HUB": self = .nccHub
      case "ROUTER_APPLIANCE": self = .routerAppliance
      case "SECURE_WEB_PROXY_GATEWAY": self = .secureWebProxyGateway
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Target/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .peeringVpc
      case 2: self = .vpnGateway
      case 3: self = .interconnect
      case 4: self = .gkeMaster
      case 5: self = .importedCustomRouteNextHop
      case 6: self = .cloudSqlInstance
      case 7: self = .anotherProject
      case 8: self = .nccHub
      case 9: self = .routerAppliance
      case 10: self = .secureWebProxyGateway
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .peeringVpc: return try container.encode(1)
      case .vpnGateway: return try container.encode(2)
      case .interconnect: return try container.encode(3)
      case .gkeMaster: return try container.encode(4)
      case .importedCustomRouteNextHop: return try container.encode(5)
      case .cloudSqlInstance: return try container.encode(6)
      case .anotherProject: return try container.encode(7)
      case .nccHub: return try container.encode(8)
      case .routerAppliance: return try container.encode(9)
      case .secureWebProxyGateway: return try container.encode(10)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkmanagement.v1.ForwardInfo"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
