// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// For display only. Metadata associated with a Google Kubernetes Engine (GKE)
/// cluster master.
public struct GKEMasterInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// URI of a GKE cluster.
  public var clusterUri: Swift.String = Swift.String()

  /// URI of a GKE cluster network.
  public var clusterNetworkUri: Swift.String = Swift.String()

  /// Internal IP address of a GKE cluster control plane.
  public var internalIp: Swift.String = Swift.String()

  /// External IP address of a GKE cluster control plane.
  public var externalIp: Swift.String = Swift.String()

  /// DNS endpoint of a GKE cluster control plane.
  public var dnsEndpoint: Swift.String = Swift.String()

  /// Initialize a new instance of `GKEMasterInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GKEMasterInfo().with { $0.clusterUri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkmanagement.v1.GKEMasterInfo"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
