// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// For display only. Metadata associated with a Google Kubernetes Engine (GKE)
/// Pod.
public struct GkePodInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// URI of a GKE Pod.
  /// For Pods in regional Clusters, the URI format is:
  /// `projects/{project}/locations/{location}/clusters/{cluster}/k8s/namespaces/{namespace}/pods/{pod}`
  /// For Pods in zonal Clusters, the URI format is:
  /// `projects/{project}/zones/{zone}/clusters/{cluster}/k8s/namespaces/{namespace}/pods/{pod}`
  public var podUri: Swift.String = Swift.String()

  /// IP address of a GKE Pod. If the Pod is dual-stack, this is the IP address
  /// relevant to the trace.
  public var ipAddress: Swift.String = Swift.String()

  /// URI of the network containing the GKE Pod.
  public var networkUri: Swift.String = Swift.String()

  /// Initialize a new instance of `GkePodInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GkePodInfo().with { $0.podUri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkmanagement.v1.GkePodInfo"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
