// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// For display only. Metadata associated with an Interconnect attachment.
public struct InterconnectAttachmentInfo: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Name of an Interconnect attachment.
  public var displayName: Swift.String = Swift.String()

  /// URI of an Interconnect attachment.
  public var uri: Swift.String = Swift.String()

  /// URI of the Interconnect where the Interconnect attachment is
  /// configured.
  public var interconnectUri: Swift.String = Swift.String()

  /// Name of a Google Cloud region where the Interconnect attachment is
  /// configured.
  public var region: Swift.String = Swift.String()

  /// URI of the Cloud Router to be used for dynamic routing.
  public var cloudRouterUri: Swift.String = Swift.String()

  /// The type of interconnect attachment this is.
  public var type: InterconnectAttachmentInfo.Type_ = InterconnectAttachmentInfo.Type_()

  /// Appliance IP address that was matched for L2_DEDICATED attachments.
  public var l2AttachmentMatchedIpAddress: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `InterconnectAttachmentInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = InterconnectAttachmentInfo().with { $0.displayName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let displayName = CodingKeys(stringValue: "displayName")
    static let uri = CodingKeys(stringValue: "uri")
    static let interconnectUri = CodingKeys(stringValue: "interconnectUri")
    static let region = CodingKeys(stringValue: "region")
    static let cloudRouterUri = CodingKeys(stringValue: "cloudRouterUri")
    static let type = CodingKeys(stringValue: "type")
    static let l2AttachmentMatchedIpAddress = CodingKeys(
      stringValue: "l2AttachmentMatchedIpAddress")

    static let _knownKeys: Set<Swift.String> = [
      "displayName",
      "uri",
      "interconnectUri",
      "region",
      "cloudRouterUri",
      "type",
      "l2AttachmentMatchedIpAddress",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uri) {
      self.uri = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .interconnectUri) {
      self.interconnectUri = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .region) {
      self.region = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .cloudRouterUri) {
      self.cloudRouterUri = value
    }
    if let value = try container.decodeIfPresent(
      InterconnectAttachmentInfo.Type_.self, forKey: .type)
    {
      self.type = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .l2AttachmentMatchedIpAddress)
    {
      self.l2AttachmentMatchedIpAddress = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.uri, forKey: .uri)
    try container.encode(self.interconnectUri, forKey: .interconnectUri)
    try container.encode(self.region, forKey: .region)
    try container.encode(self.cloudRouterUri, forKey: .cloudRouterUri)
    try container.encode(self.type, forKey: .type)
    try container.encode(self.l2AttachmentMatchedIpAddress, forKey: .l2AttachmentMatchedIpAddress)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// What type of interconnect attachment this is.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Type_: Codable, Equatable, Sendable {
    /// Unspecified type.
    case unspecified
    /// Attachment to a dedicated interconnect.
    case dedicated
    /// Attachment to a partner interconnect, created by the customer.
    case partner
    /// Attachment to a partner interconnect, created by the partner.
    case partnerProvider
    /// Attachment to a L2 interconnect, created by the customer.
    case l2Dedicated
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .dedicated: return 1
      case .partner: return 2
      case .partnerProvider: return 3
      case .l2Dedicated: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TYPE_UNSPECIFIED"
      case .dedicated: return "DEDICATED"
      case .partner: return "PARTNER"
      case .partnerProvider: return "PARTNER_PROVIDER"
      case .l2Dedicated: return "L2_DEDICATED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Type_/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TYPE_UNSPECIFIED": self = .unspecified
      case "DEDICATED": self = .dedicated
      case "PARTNER": self = .partner
      case "PARTNER_PROVIDER": self = .partnerProvider
      case "L2_DEDICATED": self = .l2Dedicated
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Type_/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .dedicated
      case 2: self = .partner
      case 3: self = .partnerProvider
      case 4: self = .l2Dedicated
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("TYPE_UNSPECIFIED")
      case .dedicated: return try container.encode("DEDICATED")
      case .partner: return try container.encode("PARTNER")
      case .partnerProvider: return try container.encode("PARTNER_PROVIDER")
      case .l2Dedicated: return try container.encode("L2_DEDICATED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkmanagement.v1.InterconnectAttachmentInfo"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
