// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// For display only. Contains information about why IP masquerading was skipped
/// for the packet.
public struct IpMasqueradingSkippedInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Reason why IP masquerading was not applied.
  public var reason: IpMasqueradingSkippedInfo.Reason = IpMasqueradingSkippedInfo.Reason()

  /// The matched non-masquerade IP range. Only set if reason is
  /// DESTINATION_IP_IN_CONFIGURED_NON_MASQUERADE_RANGE or
  /// DESTINATION_IP_IN_DEFAULT_NON_MASQUERADE_RANGE.
  public var nonMasqueradeRange: Swift.String = Swift.String()

  /// Initialize a new instance of `IpMasqueradingSkippedInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = IpMasqueradingSkippedInfo().with { $0.reason = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Reason why IP masquerading was skipped.
  public enum Reason: Codable, Equatable, Sendable {
    /// Unused default value.
    case unspecified
    /// Masquerading not applied because destination IP is in one of configured
    /// non-masquerade ranges.
    case destinationIpInConfiguredNonMasqueradeRange
    /// Masquerading not applied because destination IP is in one of default
    /// non-masquerade ranges.
    case destinationIpInDefaultNonMasqueradeRange
    /// Masquerading not applied because destination is on the same Node.
    case destinationOnSameNode
    /// Masquerading not applied because ip-masq-agent doesn't exist and default
    /// SNAT is disabled.
    case defaultSnatDisabled
    /// Masquerading not applied because the packet's IP version is IPv6.
    case noMasqueradingForIpv6
    /// Masquerading not applied because the source Pod uses the host Node's
    /// network namespace, including the Node's IP address.
    case podUsesNodeNetworkNamespace
    /// Masquerading not applied because the packet is a return packet.
    case noMasqueradingForReturnPacket
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .destinationIpInConfiguredNonMasqueradeRange: return 1
      case .destinationIpInDefaultNonMasqueradeRange: return 2
      case .destinationOnSameNode: return 3
      case .defaultSnatDisabled: return 4
      case .noMasqueradingForIpv6: return 5
      case .podUsesNodeNetworkNamespace: return 6
      case .noMasqueradingForReturnPacket: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "REASON_UNSPECIFIED"
      case .destinationIpInConfiguredNonMasqueradeRange:
        return "DESTINATION_IP_IN_CONFIGURED_NON_MASQUERADE_RANGE"
      case .destinationIpInDefaultNonMasqueradeRange:
        return "DESTINATION_IP_IN_DEFAULT_NON_MASQUERADE_RANGE"
      case .destinationOnSameNode: return "DESTINATION_ON_SAME_NODE"
      case .defaultSnatDisabled: return "DEFAULT_SNAT_DISABLED"
      case .noMasqueradingForIpv6: return "NO_MASQUERADING_FOR_IPV6"
      case .podUsesNodeNetworkNamespace: return "POD_USES_NODE_NETWORK_NAMESPACE"
      case .noMasqueradingForReturnPacket: return "NO_MASQUERADING_FOR_RETURN_PACKET"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Reason/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "REASON_UNSPECIFIED": self = .unspecified
      case "DESTINATION_IP_IN_CONFIGURED_NON_MASQUERADE_RANGE":
        self = .destinationIpInConfiguredNonMasqueradeRange
      case "DESTINATION_IP_IN_DEFAULT_NON_MASQUERADE_RANGE":
        self = .destinationIpInDefaultNonMasqueradeRange
      case "DESTINATION_ON_SAME_NODE": self = .destinationOnSameNode
      case "DEFAULT_SNAT_DISABLED": self = .defaultSnatDisabled
      case "NO_MASQUERADING_FOR_IPV6": self = .noMasqueradingForIpv6
      case "POD_USES_NODE_NETWORK_NAMESPACE": self = .podUsesNodeNetworkNamespace
      case "NO_MASQUERADING_FOR_RETURN_PACKET": self = .noMasqueradingForReturnPacket
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Reason/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .destinationIpInConfiguredNonMasqueradeRange
      case 2: self = .destinationIpInDefaultNonMasqueradeRange
      case 3: self = .destinationOnSameNode
      case 4: self = .defaultSnatDisabled
      case 5: self = .noMasqueradingForIpv6
      case 6: self = .podUsesNodeNetworkNamespace
      case 7: self = .noMasqueradingForReturnPacket
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .destinationIpInConfiguredNonMasqueradeRange: return try container.encode(1)
      case .destinationIpInDefaultNonMasqueradeRange: return try container.encode(2)
      case .destinationOnSameNode: return try container.encode(3)
      case .defaultSnatDisabled: return try container.encode(4)
      case .noMasqueradingForIpv6: return try container.encode(5)
      case .podUsesNodeNetworkNamespace: return try container.encode(6)
      case .noMasqueradingForReturnPacket: return try container.encode(7)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkmanagement.v1.IpMasqueradingSkippedInfo"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
