// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// For display only. Metadata associated with a specific load balancer backend.
public struct LoadBalancerBackend: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Name of a Compute Engine instance or network endpoint.
  public var displayName: Swift.String = Swift.String()

  /// URI of a Compute Engine instance or network endpoint.
  public var uri: Swift.String = Swift.String()

  /// State of the health check firewall configuration.
  public var healthCheckFirewallState: LoadBalancerBackend.HealthCheckFirewallState =
    LoadBalancerBackend.HealthCheckFirewallState()

  /// A list of firewall rule URIs allowing probes from health check IP ranges.
  public var healthCheckAllowingFirewallRules: [Swift.String] = []

  /// A list of firewall rule URIs blocking probes from health check IP ranges.
  public var healthCheckBlockingFirewallRules: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `LoadBalancerBackend`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LoadBalancerBackend().with { $0.displayName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let displayName = CodingKeys(stringValue: "displayName")
    static let uri = CodingKeys(stringValue: "uri")
    static let healthCheckFirewallState = CodingKeys(stringValue: "healthCheckFirewallState")
    static let healthCheckAllowingFirewallRules = CodingKeys(
      stringValue: "healthCheckAllowingFirewallRules")
    static let healthCheckBlockingFirewallRules = CodingKeys(
      stringValue: "healthCheckBlockingFirewallRules")

    static let _knownKeys: Set<Swift.String> = [
      "displayName",
      "uri",
      "healthCheckFirewallState",
      "healthCheckAllowingFirewallRules",
      "healthCheckBlockingFirewallRules",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uri) {
      self.uri = value
    }
    if let value = try container.decodeIfPresent(
      LoadBalancerBackend.HealthCheckFirewallState.self, forKey: .healthCheckFirewallState)
    {
      self.healthCheckFirewallState = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String].self, forKey: .healthCheckAllowingFirewallRules)
    {
      self.healthCheckAllowingFirewallRules = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String].self, forKey: .healthCheckBlockingFirewallRules)
    {
      self.healthCheckBlockingFirewallRules = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.uri, forKey: .uri)
    try container.encode(self.healthCheckFirewallState, forKey: .healthCheckFirewallState)
    try container.encode(
      self.healthCheckAllowingFirewallRules, forKey: .healthCheckAllowingFirewallRules)
    try container.encode(
      self.healthCheckBlockingFirewallRules, forKey: .healthCheckBlockingFirewallRules)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// State of a health check firewall configuration:
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum HealthCheckFirewallState: Codable, Equatable, Sendable {
    /// State is unspecified. Default state if not populated.
    case unspecified
    /// There are configured firewall rules to allow health check probes to the
    /// backend.
    case configured
    /// There are firewall rules configured to allow partial health check ranges
    /// or block all health check ranges.
    /// If a health check probe is sent from denied IP ranges,
    /// the health check to the backend will fail. Then, the backend will be
    /// marked unhealthy and will not receive traffic sent to the load balancer.
    case misconfigured
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .configured: return 1
      case .misconfigured: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "HEALTH_CHECK_FIREWALL_STATE_UNSPECIFIED"
      case .configured: return "CONFIGURED"
      case .misconfigured: return "MISCONFIGURED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:HealthCheckFirewallState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "HEALTH_CHECK_FIREWALL_STATE_UNSPECIFIED": self = .unspecified
      case "CONFIGURED": self = .configured
      case "MISCONFIGURED": self = .misconfigured
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:HealthCheckFirewallState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .configured
      case 2: self = .misconfigured
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("HEALTH_CHECK_FIREWALL_STATE_UNSPECIFIED")
      case .configured: return try container.encode("CONFIGURED")
      case .misconfigured: return try container.encode("MISCONFIGURED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkmanagement.v1.LoadBalancerBackend"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
