// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// For display only. Metadata associated with the load balancer backend.
public struct LoadBalancerBackendInfo: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Display name of the backend. For example, it might be an instance name for
  /// the instance group backends, or an IP address and port for zonal network
  /// endpoint group backends.
  public var name: Swift.String = Swift.String()

  /// URI of the backend instance (if applicable). Populated for instance group
  /// backends, and zonal NEG backends.
  public var instanceUri: Swift.String = Swift.String()

  /// URI of the backend service this backend belongs to (if applicable).
  public var backendServiceUri: Swift.String = Swift.String()

  /// URI of the instance group this backend belongs to (if applicable).
  public var instanceGroupUri: Swift.String = Swift.String()

  /// URI of the network endpoint group this backend belongs to (if applicable).
  public var networkEndpointGroupUri: Swift.String = Swift.String()

  /// URI of the backend bucket this backend targets (if applicable).
  public var backendBucketUri: Swift.String = Swift.String()

  /// URI of the PSC service attachment this PSC NEG backend targets (if
  /// applicable).
  public var pscServiceAttachmentUri: Swift.String = Swift.String()

  /// PSC Google API target this PSC NEG backend targets (if applicable).
  public var pscGoogleApiTarget: Swift.String = Swift.String()

  /// URI of the health check attached to this backend (if applicable).
  public var healthCheckUri: Swift.String = Swift.String()

  /// Output only. Health check firewalls configuration state for the backend.
  /// This is a result of the static firewall analysis (verifying that health
  /// check traffic from required IP ranges to the backend is allowed or not).
  /// The backend might still be unhealthy even if these firewalls are
  /// configured. Please refer to the documentation for more information:
  /// https://cloud.google.com/load-balancing/docs/firewall-rules
  public var healthCheckFirewallsConfigState:
    LoadBalancerBackendInfo.HealthCheckFirewallsConfigState =
      LoadBalancerBackendInfo.HealthCheckFirewallsConfigState()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `LoadBalancerBackendInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LoadBalancerBackendInfo().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let instanceUri = CodingKeys(stringValue: "instanceUri")
    static let backendServiceUri = CodingKeys(stringValue: "backendServiceUri")
    static let instanceGroupUri = CodingKeys(stringValue: "instanceGroupUri")
    static let networkEndpointGroupUri = CodingKeys(stringValue: "networkEndpointGroupUri")
    static let backendBucketUri = CodingKeys(stringValue: "backendBucketUri")
    static let pscServiceAttachmentUri = CodingKeys(stringValue: "pscServiceAttachmentUri")
    static let pscGoogleApiTarget = CodingKeys(stringValue: "pscGoogleApiTarget")
    static let healthCheckUri = CodingKeys(stringValue: "healthCheckUri")
    static let healthCheckFirewallsConfigState = CodingKeys(
      stringValue: "healthCheckFirewallsConfigState")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "instanceUri",
      "backendServiceUri",
      "instanceGroupUri",
      "networkEndpointGroupUri",
      "backendBucketUri",
      "pscServiceAttachmentUri",
      "pscGoogleApiTarget",
      "healthCheckUri",
      "healthCheckFirewallsConfigState",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .instanceUri) {
      self.instanceUri = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .backendServiceUri) {
      self.backendServiceUri = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .instanceGroupUri) {
      self.instanceGroupUri = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .networkEndpointGroupUri)
    {
      self.networkEndpointGroupUri = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .backendBucketUri) {
      self.backendBucketUri = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .pscServiceAttachmentUri)
    {
      self.pscServiceAttachmentUri = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pscGoogleApiTarget) {
      self.pscGoogleApiTarget = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .healthCheckUri) {
      self.healthCheckUri = value
    }
    if let value = try container.decodeIfPresent(
      LoadBalancerBackendInfo.HealthCheckFirewallsConfigState.self,
      forKey: .healthCheckFirewallsConfigState)
    {
      self.healthCheckFirewallsConfigState = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.instanceUri, forKey: .instanceUri)
    try container.encode(self.backendServiceUri, forKey: .backendServiceUri)
    try container.encode(self.instanceGroupUri, forKey: .instanceGroupUri)
    try container.encode(self.networkEndpointGroupUri, forKey: .networkEndpointGroupUri)
    try container.encode(self.backendBucketUri, forKey: .backendBucketUri)
    try container.encode(self.pscServiceAttachmentUri, forKey: .pscServiceAttachmentUri)
    try container.encode(self.pscGoogleApiTarget, forKey: .pscGoogleApiTarget)
    try container.encode(self.healthCheckUri, forKey: .healthCheckUri)
    try container.encode(
      self.healthCheckFirewallsConfigState, forKey: .healthCheckFirewallsConfigState)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Health check firewalls configuration state enum.
  public enum HealthCheckFirewallsConfigState: Codable, Equatable, Sendable {
    /// Configuration state unspecified. It usually means that the backend has
    /// no health check attached, or there was an unexpected configuration error
    /// preventing Connectivity tests from verifying health check configuration.
    case unspecified
    /// Firewall rules (policies) allowing health check traffic from all required
    /// IP ranges to the backend are configured.
    case firewallsConfigured
    /// Firewall rules (policies) allow health check traffic only from a part of
    /// required IP ranges.
    case firewallsPartiallyConfigured
    /// Firewall rules (policies) deny health check traffic from all required
    /// IP ranges to the backend.
    case firewallsNotConfigured
    /// The network contains firewall rules of unsupported types, so Connectivity
    /// tests were not able to verify health check configuration status. Please
    /// refer to the documentation for the list of unsupported configurations:
    /// https://cloud.google.com/network-intelligence-center/docs/connectivity-tests/concepts/overview#unsupported-configs
    case firewallsUnsupported
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .firewallsConfigured: return 1
      case .firewallsPartiallyConfigured: return 2
      case .firewallsNotConfigured: return 3
      case .firewallsUnsupported: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "HEALTH_CHECK_FIREWALLS_CONFIG_STATE_UNSPECIFIED"
      case .firewallsConfigured: return "FIREWALLS_CONFIGURED"
      case .firewallsPartiallyConfigured: return "FIREWALLS_PARTIALLY_CONFIGURED"
      case .firewallsNotConfigured: return "FIREWALLS_NOT_CONFIGURED"
      case .firewallsUnsupported: return "FIREWALLS_UNSUPPORTED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:HealthCheckFirewallsConfigState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "HEALTH_CHECK_FIREWALLS_CONFIG_STATE_UNSPECIFIED": self = .unspecified
      case "FIREWALLS_CONFIGURED": self = .firewallsConfigured
      case "FIREWALLS_PARTIALLY_CONFIGURED": self = .firewallsPartiallyConfigured
      case "FIREWALLS_NOT_CONFIGURED": self = .firewallsNotConfigured
      case "FIREWALLS_UNSUPPORTED": self = .firewallsUnsupported
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:HealthCheckFirewallsConfigState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .firewallsConfigured
      case 2: self = .firewallsPartiallyConfigured
      case 3: self = .firewallsNotConfigured
      case 4: self = .firewallsUnsupported
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified:
        return try container.encode("HEALTH_CHECK_FIREWALLS_CONFIG_STATE_UNSPECIFIED")
      case .firewallsConfigured: return try container.encode("FIREWALLS_CONFIGURED")
      case .firewallsPartiallyConfigured:
        return try container.encode("FIREWALLS_PARTIALLY_CONFIGURED")
      case .firewallsNotConfigured: return try container.encode("FIREWALLS_NOT_CONFIGURED")
      case .firewallsUnsupported: return try container.encode("FIREWALLS_UNSUPPORTED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkmanagement.v1.LoadBalancerBackendInfo"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
