// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// For display only. Metadata associated with NAT.
public struct NatInfo: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Type of NAT.
  public var type: NatInfo.Type_ = NatInfo.Type_()

  /// IP protocol in string format, for example: "TCP", "UDP", "ICMP".
  public var `protocol`: Swift.String = Swift.String()

  /// URI of the network where NAT translation takes place.
  public var networkUri: Swift.String = Swift.String()

  /// Source IP address before NAT translation.
  public var oldSourceIp: Swift.String = Swift.String()

  /// Source IP address after NAT translation.
  public var newSourceIp: Swift.String = Swift.String()

  /// Destination IP address before NAT translation.
  public var oldDestinationIp: Swift.String = Swift.String()

  /// Destination IP address after NAT translation.
  public var newDestinationIp: Swift.String = Swift.String()

  /// Source port before NAT translation. Only valid when protocol is TCP or UDP.
  public var oldSourcePort: Swift.Int32 = Swift.Int32()

  /// Source port after NAT translation. Only valid when protocol is TCP or UDP.
  public var newSourcePort: Swift.Int32 = Swift.Int32()

  /// Destination port before NAT translation. Only valid when protocol is TCP or
  /// UDP.
  public var oldDestinationPort: Swift.Int32 = Swift.Int32()

  /// Destination port after NAT translation. Only valid when protocol is TCP or
  /// UDP.
  public var newDestinationPort: Swift.Int32 = Swift.Int32()

  /// Uri of the Cloud Router. Only valid when type is CLOUD_NAT.
  public var routerUri: Swift.String = Swift.String()

  /// The name of Cloud NAT Gateway. Only valid when type is CLOUD_NAT.
  public var natGatewayName: Swift.String = Swift.String()

  /// Type of Cloud NAT gateway. Only valid when `type` is CLOUD_NAT.
  public var cloudNatGatewayType: NatInfo.CloudNatGatewayType = NatInfo.CloudNatGatewayType()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `NatInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = NatInfo().with { $0.type = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let type = CodingKeys(stringValue: "type")
    static let `protocol` = CodingKeys(stringValue: "protocol")
    static let networkUri = CodingKeys(stringValue: "networkUri")
    static let oldSourceIp = CodingKeys(stringValue: "oldSourceIp")
    static let newSourceIp = CodingKeys(stringValue: "newSourceIp")
    static let oldDestinationIp = CodingKeys(stringValue: "oldDestinationIp")
    static let newDestinationIp = CodingKeys(stringValue: "newDestinationIp")
    static let oldSourcePort = CodingKeys(stringValue: "oldSourcePort")
    static let newSourcePort = CodingKeys(stringValue: "newSourcePort")
    static let oldDestinationPort = CodingKeys(stringValue: "oldDestinationPort")
    static let newDestinationPort = CodingKeys(stringValue: "newDestinationPort")
    static let routerUri = CodingKeys(stringValue: "routerUri")
    static let natGatewayName = CodingKeys(stringValue: "natGatewayName")
    static let cloudNatGatewayType = CodingKeys(stringValue: "cloudNatGatewayType")

    static let _knownKeys: Set<Swift.String> = [
      "type",
      "protocol",
      "networkUri",
      "oldSourceIp",
      "newSourceIp",
      "oldDestinationIp",
      "newDestinationIp",
      "oldSourcePort",
      "newSourcePort",
      "oldDestinationPort",
      "newDestinationPort",
      "routerUri",
      "natGatewayName",
      "cloudNatGatewayType",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(NatInfo.Type_.self, forKey: .type) {
      self.type = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .`protocol`) {
      self.`protocol` = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .networkUri) {
      self.networkUri = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .oldSourceIp) {
      self.oldSourceIp = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .newSourceIp) {
      self.newSourceIp = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .oldDestinationIp) {
      self.oldDestinationIp = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .newDestinationIp) {
      self.newDestinationIp = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .oldSourcePort) {
      self.oldSourcePort = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .newSourcePort) {
      self.newSourcePort = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .oldDestinationPort) {
      self.oldDestinationPort = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .newDestinationPort) {
      self.newDestinationPort = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .routerUri) {
      self.routerUri = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .natGatewayName) {
      self.natGatewayName = value
    }
    if let value = try container.decodeIfPresent(
      NatInfo.CloudNatGatewayType.self, forKey: .cloudNatGatewayType)
    {
      self.cloudNatGatewayType = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.type, forKey: .type)
    try container.encode(self.`protocol`, forKey: .`protocol`)
    try container.encode(self.networkUri, forKey: .networkUri)
    try container.encode(self.oldSourceIp, forKey: .oldSourceIp)
    try container.encode(self.newSourceIp, forKey: .newSourceIp)
    try container.encode(self.oldDestinationIp, forKey: .oldDestinationIp)
    try container.encode(self.newDestinationIp, forKey: .newDestinationIp)
    try container.encode(self.oldSourcePort, forKey: .oldSourcePort)
    try container.encode(self.newSourcePort, forKey: .newSourcePort)
    try container.encode(self.oldDestinationPort, forKey: .oldDestinationPort)
    try container.encode(self.newDestinationPort, forKey: .newDestinationPort)
    try container.encode(self.routerUri, forKey: .routerUri)
    try container.encode(self.natGatewayName, forKey: .natGatewayName)
    try container.encode(self.cloudNatGatewayType, forKey: .cloudNatGatewayType)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Types of NAT.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Type_: Codable, Equatable, Sendable {
    /// Type is unspecified.
    case unspecified
    /// From Compute Engine instance's internal address to external address.
    case internalToExternal
    /// From Compute Engine instance's external address to internal address.
    case externalToInternal
    /// Cloud NAT Gateway.
    case cloudNat
    /// Private service connect NAT.
    case privateServiceConnect
    /// GKE Pod IP address masquerading.
    case gkePodIpMasquerading
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .internalToExternal: return 1
      case .externalToInternal: return 2
      case .cloudNat: return 3
      case .privateServiceConnect: return 4
      case .gkePodIpMasquerading: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TYPE_UNSPECIFIED"
      case .internalToExternal: return "INTERNAL_TO_EXTERNAL"
      case .externalToInternal: return "EXTERNAL_TO_INTERNAL"
      case .cloudNat: return "CLOUD_NAT"
      case .privateServiceConnect: return "PRIVATE_SERVICE_CONNECT"
      case .gkePodIpMasquerading: return "GKE_POD_IP_MASQUERADING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Type_/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TYPE_UNSPECIFIED": self = .unspecified
      case "INTERNAL_TO_EXTERNAL": self = .internalToExternal
      case "EXTERNAL_TO_INTERNAL": self = .externalToInternal
      case "CLOUD_NAT": self = .cloudNat
      case "PRIVATE_SERVICE_CONNECT": self = .privateServiceConnect
      case "GKE_POD_IP_MASQUERADING": self = .gkePodIpMasquerading
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Type_/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .internalToExternal
      case 2: self = .externalToInternal
      case 3: self = .cloudNat
      case 4: self = .privateServiceConnect
      case 5: self = .gkePodIpMasquerading
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("TYPE_UNSPECIFIED")
      case .internalToExternal: return try container.encode("INTERNAL_TO_EXTERNAL")
      case .externalToInternal: return try container.encode("EXTERNAL_TO_INTERNAL")
      case .cloudNat: return try container.encode("CLOUD_NAT")
      case .privateServiceConnect: return try container.encode("PRIVATE_SERVICE_CONNECT")
      case .gkePodIpMasquerading: return try container.encode("GKE_POD_IP_MASQUERADING")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Types of Cloud NAT gateway.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum CloudNatGatewayType: Codable, Equatable, Sendable {
    /// Type is unspecified.
    case unspecified
    /// Public NAT gateway.
    case publicNat44
    /// Public NAT64 gateway.
    case publicNat64
    /// Private NAT gateway for NCC.
    case privateNatNcc
    /// Private NAT gateway for hybrid connectivity.
    case privateNatHybrid
    /// Private NAT64 gateway.
    case privateNat64
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .publicNat44: return 1
      case .publicNat64: return 2
      case .privateNatNcc: return 3
      case .privateNatHybrid: return 4
      case .privateNat64: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CLOUD_NAT_GATEWAY_TYPE_UNSPECIFIED"
      case .publicNat44: return "PUBLIC_NAT44"
      case .publicNat64: return "PUBLIC_NAT64"
      case .privateNatNcc: return "PRIVATE_NAT_NCC"
      case .privateNatHybrid: return "PRIVATE_NAT_HYBRID"
      case .privateNat64: return "PRIVATE_NAT64"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:CloudNatGatewayType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CLOUD_NAT_GATEWAY_TYPE_UNSPECIFIED": self = .unspecified
      case "PUBLIC_NAT44": self = .publicNat44
      case "PUBLIC_NAT64": self = .publicNat64
      case "PRIVATE_NAT_NCC": self = .privateNatNcc
      case "PRIVATE_NAT_HYBRID": self = .privateNatHybrid
      case "PRIVATE_NAT64": self = .privateNat64
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:CloudNatGatewayType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .publicNat44
      case 2: self = .publicNat64
      case 3: self = .privateNatNcc
      case 4: self = .privateNatHybrid
      case 5: self = .privateNat64
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("CLOUD_NAT_GATEWAY_TYPE_UNSPECIFIED")
      case .publicNat44: return try container.encode("PUBLIC_NAT44")
      case .publicNat64: return try container.encode("PUBLIC_NAT64")
      case .privateNatNcc: return try container.encode("PRIVATE_NAT_NCC")
      case .privateNatHybrid: return try container.encode("PRIVATE_NAT_HYBRID")
      case .privateNat64: return try container.encode("PRIVATE_NAT64")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkmanagement.v1.NatInfo"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
