// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// For display only. Metadata associated with a Compute Engine network.
public struct NetworkInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Name of a Compute Engine network.
  public var displayName: Swift.String = Swift.String()

  /// URI of a Compute Engine network.
  public var uri: Swift.String = Swift.String()

  /// URI of the subnet matching the source IP address of the test.
  public var matchedSubnetUri: Swift.String = Swift.String()

  /// The IP range of the subnet matching the source IP address of the test.
  public var matchedIpRange: Swift.String = Swift.String()

  /// The region of the subnet matching the source IP address of the test.
  public var region: Swift.String = Swift.String()

  /// Initialize a new instance of `NetworkInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = NetworkInfo().with { $0.displayName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkmanagement.v1.NetworkInfo"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
