// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// For display only. Metadata associated with ProxyConnection.
public struct ProxyConnectionInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// IP protocol in string format, for example: "TCP", "UDP", "ICMP".
  public var `protocol`: Swift.String = Swift.String()

  /// Source IP address of an original connection.
  public var oldSourceIp: Swift.String = Swift.String()

  /// Source IP address of a new connection.
  public var newSourceIp: Swift.String = Swift.String()

  /// Destination IP address of an original connection
  public var oldDestinationIp: Swift.String = Swift.String()

  /// Destination IP address of a new connection.
  public var newDestinationIp: Swift.String = Swift.String()

  /// Source port of an original connection. Only valid when protocol is TCP or
  /// UDP.
  public var oldSourcePort: Swift.Int32 = Swift.Int32()

  /// Source port of a new connection. Only valid when protocol is TCP or UDP.
  public var newSourcePort: Swift.Int32 = Swift.Int32()

  /// Destination port of an original connection. Only valid when protocol is TCP
  /// or UDP.
  public var oldDestinationPort: Swift.Int32 = Swift.Int32()

  /// Destination port of a new connection. Only valid when protocol is TCP or
  /// UDP.
  public var newDestinationPort: Swift.Int32 = Swift.Int32()

  /// Uri of proxy subnet.
  public var subnetUri: Swift.String = Swift.String()

  /// URI of the network where connection is proxied.
  public var networkUri: Swift.String = Swift.String()

  /// Initialize a new instance of `ProxyConnectionInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ProxyConnectionInfo().with { $0.`protocol` = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case `protocol` = "protocol"
    case oldSourceIp = "oldSourceIp"
    case newSourceIp = "newSourceIp"
    case oldDestinationIp = "oldDestinationIp"
    case newDestinationIp = "newDestinationIp"
    case oldSourcePort = "oldSourcePort"
    case newSourcePort = "newSourcePort"
    case oldDestinationPort = "oldDestinationPort"
    case newDestinationPort = "newDestinationPort"
    case subnetUri = "subnetUri"
    case networkUri = "networkUri"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.`protocol` = try container.decode(Swift.String.self, forKey: .`protocol`)
    self.oldSourceIp = try container.decode(Swift.String.self, forKey: .oldSourceIp)
    self.newSourceIp = try container.decode(Swift.String.self, forKey: .newSourceIp)
    self.oldDestinationIp = try container.decode(Swift.String.self, forKey: .oldDestinationIp)
    self.newDestinationIp = try container.decode(Swift.String.self, forKey: .newDestinationIp)
    self.oldSourcePort = try container.decode(Swift.Int32.self, forKey: .oldSourcePort)
    self.newSourcePort = try container.decode(Swift.Int32.self, forKey: .newSourcePort)
    self.oldDestinationPort = try container.decode(Swift.Int32.self, forKey: .oldDestinationPort)
    self.newDestinationPort = try container.decode(Swift.Int32.self, forKey: .newDestinationPort)
    self.subnetUri = try container.decode(Swift.String.self, forKey: .subnetUri)
    self.networkUri = try container.decode(Swift.String.self, forKey: .networkUri)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.`protocol`, forKey: .`protocol`)
    try container.encode(self.oldSourceIp, forKey: .oldSourceIp)
    try container.encode(self.newSourceIp, forKey: .newSourceIp)
    try container.encode(self.oldDestinationIp, forKey: .oldDestinationIp)
    try container.encode(self.newDestinationIp, forKey: .newDestinationIp)
    try container.encode(self.oldSourcePort, forKey: .oldSourcePort)
    try container.encode(self.newSourcePort, forKey: .newSourcePort)
    try container.encode(self.oldDestinationPort, forKey: .oldDestinationPort)
    try container.encode(self.newDestinationPort, forKey: .newDestinationPort)
    try container.encode(self.subnetUri, forKey: .subnetUri)
    try container.encode(self.networkUri, forKey: .networkUri)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkmanagement.v1.ProxyConnectionInfo"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
