// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// For display only. Metadata associated with ProxyConnection.
public struct ProxyConnectionInfo: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// IP protocol in string format, for example: "TCP", "UDP", "ICMP".
  public var `protocol`: Swift.String = Swift.String()

  /// Source IP address of an original connection.
  public var oldSourceIp: Swift.String = Swift.String()

  /// Source IP address of a new connection.
  public var newSourceIp: Swift.String = Swift.String()

  /// Destination IP address of an original connection
  public var oldDestinationIp: Swift.String = Swift.String()

  /// Destination IP address of a new connection.
  public var newDestinationIp: Swift.String = Swift.String()

  /// Source port of an original connection. Only valid when protocol is TCP or
  /// UDP.
  public var oldSourcePort: Swift.Int32 = Swift.Int32()

  /// Source port of a new connection. Only valid when protocol is TCP or UDP.
  public var newSourcePort: Swift.Int32 = Swift.Int32()

  /// Destination port of an original connection. Only valid when protocol is TCP
  /// or UDP.
  public var oldDestinationPort: Swift.Int32 = Swift.Int32()

  /// Destination port of a new connection. Only valid when protocol is TCP or
  /// UDP.
  public var newDestinationPort: Swift.Int32 = Swift.Int32()

  /// Uri of proxy subnet.
  public var subnetUri: Swift.String = Swift.String()

  /// URI of the network where connection is proxied.
  public var networkUri: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ProxyConnectionInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ProxyConnectionInfo().with { $0.`protocol` = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let `protocol` = CodingKeys(stringValue: "protocol")
    static let oldSourceIp = CodingKeys(stringValue: "oldSourceIp")
    static let newSourceIp = CodingKeys(stringValue: "newSourceIp")
    static let oldDestinationIp = CodingKeys(stringValue: "oldDestinationIp")
    static let newDestinationIp = CodingKeys(stringValue: "newDestinationIp")
    static let oldSourcePort = CodingKeys(stringValue: "oldSourcePort")
    static let newSourcePort = CodingKeys(stringValue: "newSourcePort")
    static let oldDestinationPort = CodingKeys(stringValue: "oldDestinationPort")
    static let newDestinationPort = CodingKeys(stringValue: "newDestinationPort")
    static let subnetUri = CodingKeys(stringValue: "subnetUri")
    static let networkUri = CodingKeys(stringValue: "networkUri")

    static let _knownKeys: Set<Swift.String> = [
      "protocol",
      "oldSourceIp",
      "newSourceIp",
      "oldDestinationIp",
      "newDestinationIp",
      "oldSourcePort",
      "newSourcePort",
      "oldDestinationPort",
      "newDestinationPort",
      "subnetUri",
      "networkUri",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .`protocol`) {
      self.`protocol` = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .oldSourceIp) {
      self.oldSourceIp = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .newSourceIp) {
      self.newSourceIp = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .oldDestinationIp) {
      self.oldDestinationIp = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .newDestinationIp) {
      self.newDestinationIp = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .oldSourcePort) {
      self.oldSourcePort = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .newSourcePort) {
      self.newSourcePort = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .oldDestinationPort) {
      self.oldDestinationPort = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .newDestinationPort) {
      self.newDestinationPort = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .subnetUri) {
      self.subnetUri = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .networkUri) {
      self.networkUri = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.`protocol`, forKey: .`protocol`)
    try container.encode(self.oldSourceIp, forKey: .oldSourceIp)
    try container.encode(self.newSourceIp, forKey: .newSourceIp)
    try container.encode(self.oldDestinationIp, forKey: .oldDestinationIp)
    try container.encode(self.newDestinationIp, forKey: .newDestinationIp)
    try container.encode(self.oldSourcePort, forKey: .oldSourcePort)
    try container.encode(self.newSourcePort, forKey: .newSourcePort)
    try container.encode(self.oldDestinationPort, forKey: .oldDestinationPort)
    try container.encode(self.newDestinationPort, forKey: .newDestinationPort)
    try container.encode(self.subnetUri, forKey: .subnetUri)
    try container.encode(self.networkUri, forKey: .networkUri)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkmanagement.v1.ProxyConnectionInfo"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
