// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request for the `QueryOrgVpcFlowLogsConfigs` method.
public struct QueryOrgVpcFlowLogsConfigsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The parent resource of the VpcFlowLogsConfig, specified in
  /// the following format: `projects/{project_id}/locations/global`
  public var parent: Swift.String = Swift.String()

  /// Optional. Number of `VpcFlowLogsConfigs` to return.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. Page token from an earlier query, as returned in
  /// `next_page_token`.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. Lists the `VpcFlowLogsConfigs` that match the filter expression.
  /// A filter expression must use the supported [CEL logic operators]
  /// (https://cloud.google.com/vpc/docs/about-flow-logs-records#supported_cel_logic_operators).
  public var filter: Swift.String = Swift.String()

  /// Initialize a new instance of `QueryOrgVpcFlowLogsConfigsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = QueryOrgVpcFlowLogsConfigsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkmanagement.v1.QueryOrgVpcFlowLogsConfigsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
