// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// The Reachability service in the Google Cloud Network Management API provides
/// services that analyze the reachability within a single Google Virtual Private
/// Cloud (VPC) network, between peered VPC networks, between VPC and on-premises
/// networks, or between VPC networks and internet hosts. A reachability analysis
/// is based on Google Cloud network configurations.
///
/// You can use the analysis results to verify these configurations and
/// to troubleshoot connectivity issues.
///
/// @Snippet(path: "ReachabilityServiceQuickstart")
public class ReachabilityServiceClient: Clients.ReachabilityServiceProtocol {
  let inner: any Clients.ReachabilityServiceStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `ReachabilityServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.ReachabilityServiceStub = try Clients.ReachabilityServiceTransport(
      options)
    inner = Clients.ReachabilityServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.ReachabilityServiceLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists all Connectivity Tests owned by a project.
  ///
  /// @Snippet(path: "ReachabilityService_ListConnectivityTests")
  public func listConnectivityTests(
    request: ListConnectivityTestsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudNetworkManagementV1.ListConnectivityTestsResponse {
    try await self.inner.listConnectivityTests(request: request, options: options)
  }

  /// Lists all Connectivity Tests owned by a project.
  ///
  /// @Snippet(path: "ReachabilityService_ListConnectivityTests")
  public func listConnectivityTests(
    byItem: ListConnectivityTestsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ConnectivityTest, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudNetworkManagementV1.ListConnectivityTestsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listConnectivityTests(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets the details of a specific Connectivity Test.
  ///
  /// @Snippet(path: "ReachabilityService_GetConnectivityTest")
  public func getConnectivityTest(
    request: GetConnectivityTestRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudNetworkManagementV1.ConnectivityTest {
    try await self.inner.getConnectivityTest(request: request, options: options)
  }

  /// Creates a new Connectivity Test.
  /// After you create a test, the reachability analysis is performed as part
  /// of the long running operation, which completes when the analysis completes.
  ///
  /// If the endpoint specifications in `ConnectivityTest` are invalid
  /// (for example, containing non-existent resources in the network, or you
  /// don't have read permissions to the network configurations of listed
  /// projects), then the reachability result returns a value of `UNKNOWN`.
  ///
  /// If the endpoint specifications in `ConnectivityTest` are
  /// incomplete, the reachability result returns a value of
  /// <code>AMBIGUOUS</code>. For more information,
  /// see the Connectivity Test documentation.
  ///
  /// @Snippet(path: "ReachabilityService_CreateConnectivityTest")
  public func createConnectivityTest(
    request: CreateConnectivityTestRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createConnectivityTest(request: request, options: options)
  }

  /// Creates a new Connectivity Test.
  /// After you create a test, the reachability analysis is performed as part
  /// of the long running operation, which completes when the analysis completes.
  ///
  /// If the endpoint specifications in `ConnectivityTest` are invalid
  /// (for example, containing non-existent resources in the network, or you
  /// don't have read permissions to the network configurations of listed
  /// projects), then the reachability result returns a value of `UNKNOWN`.
  ///
  /// If the endpoint specifications in `ConnectivityTest` are
  /// incomplete, the reachability result returns a value of
  /// <code>AMBIGUOUS</code>. For more information,
  /// see the Connectivity Test documentation.
  ///
  /// @Snippet(path: "ReachabilityService_CreateConnectivityTest")
  public func createConnectivityTest(
    withPolling: CreateConnectivityTestRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<ConnectivityTest> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<ConnectivityTest>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try ConnectivityTest(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.createConnectivityTest(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<ConnectivityTest>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates the configuration of an existing `ConnectivityTest`.
  /// After you update a test, the reachability analysis is performed as part
  /// of the long running operation, which completes when the analysis completes.
  /// The Reachability state in the test resource is updated with the new result.
  ///
  /// If the endpoint specifications in `ConnectivityTest` are invalid
  /// (for example, they contain non-existent resources in the network, or the
  /// user does not have read permissions to the network configurations of
  /// listed projects), then the reachability result returns a value of
  /// <code>UNKNOWN</code>.
  ///
  /// If the endpoint specifications in `ConnectivityTest` are incomplete, the
  /// reachability result returns a value of `AMBIGUOUS`. See the documentation
  /// in `ConnectivityTest` for more details.
  ///
  /// @Snippet(path: "ReachabilityService_UpdateConnectivityTest")
  public func updateConnectivityTest(
    request: UpdateConnectivityTestRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateConnectivityTest(request: request, options: options)
  }

  /// Updates the configuration of an existing `ConnectivityTest`.
  /// After you update a test, the reachability analysis is performed as part
  /// of the long running operation, which completes when the analysis completes.
  /// The Reachability state in the test resource is updated with the new result.
  ///
  /// If the endpoint specifications in `ConnectivityTest` are invalid
  /// (for example, they contain non-existent resources in the network, or the
  /// user does not have read permissions to the network configurations of
  /// listed projects), then the reachability result returns a value of
  /// <code>UNKNOWN</code>.
  ///
  /// If the endpoint specifications in `ConnectivityTest` are incomplete, the
  /// reachability result returns a value of `AMBIGUOUS`. See the documentation
  /// in `ConnectivityTest` for more details.
  ///
  /// @Snippet(path: "ReachabilityService_UpdateConnectivityTest")
  public func updateConnectivityTest(
    withPolling: UpdateConnectivityTestRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<ConnectivityTest> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<ConnectivityTest>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try ConnectivityTest(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.updateConnectivityTest(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<ConnectivityTest>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Rerun an existing `ConnectivityTest`.
  /// After the user triggers the rerun, the reachability analysis is performed
  /// as part of the long running operation, which completes when the analysis
  /// completes.
  ///
  /// Even though the test configuration remains the same, the reachability
  /// result may change due to underlying network configuration changes.
  ///
  /// If the endpoint specifications in `ConnectivityTest` become invalid (for
  /// example, specified resources are deleted in the network, or you lost
  /// read permissions to the network configurations of listed projects), then
  /// the reachability result returns a value of `UNKNOWN`.
  ///
  /// @Snippet(path: "ReachabilityService_RerunConnectivityTest")
  public func rerunConnectivityTest(
    request: RerunConnectivityTestRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.rerunConnectivityTest(request: request, options: options)
  }

  /// Rerun an existing `ConnectivityTest`.
  /// After the user triggers the rerun, the reachability analysis is performed
  /// as part of the long running operation, which completes when the analysis
  /// completes.
  ///
  /// Even though the test configuration remains the same, the reachability
  /// result may change due to underlying network configuration changes.
  ///
  /// If the endpoint specifications in `ConnectivityTest` become invalid (for
  /// example, specified resources are deleted in the network, or you lost
  /// read permissions to the network configurations of listed projects), then
  /// the reachability result returns a value of `UNKNOWN`.
  ///
  /// @Snippet(path: "ReachabilityService_RerunConnectivityTest")
  public func rerunConnectivityTest(
    withPolling: RerunConnectivityTestRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<ConnectivityTest> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<ConnectivityTest>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try ConnectivityTest(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.rerunConnectivityTest(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<ConnectivityTest>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a specific `ConnectivityTest`.
  ///
  /// @Snippet(path: "ReachabilityService_DeleteConnectivityTest")
  public func deleteConnectivityTest(
    request: DeleteConnectivityTestRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteConnectivityTest(request: request, options: options)
  }

  /// Deletes a specific `ConnectivityTest`.
  ///
  /// @Snippet(path: "ReachabilityService_DeleteConnectivityTest")
  public func deleteConnectivityTest(
    withPolling: DeleteConnectivityTestRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<Void>.State
      in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response:
        return .init(done: true, result: .success(()))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.deleteConnectivityTest(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists information about the supported locations for this service.
  /// This method can be called in two ways:
  ///
  /// *   **List all public locations:** Use the path `GET /v1/locations`.
  /// *   **List project-visible locations:** Use the path
  /// `GET /v1/projects/{project_id}/locations`. This may include public
  /// locations as well as private or other locations specifically visible
  /// to the project.
  ///
  /// @Snippet(path: "ReachabilityService_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  /// This method can be called in two ways:
  ///
  /// *   **List all public locations:** Use the path `GET /v1/locations`.
  /// *   **List project-visible locations:** Use the path
  /// `GET /v1/projects/{project_id}/locations`. This may include public
  /// locations as well as private or other locations specifically visible
  /// to the project.
  ///
  /// @Snippet(path: "ReachabilityService_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "ReachabilityService_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Sets the access control policy on the specified resource. Replaces
  /// any existing policy.
  ///
  /// Can return `NOT_FOUND`, `INVALID_ARGUMENT`, and `PERMISSION_DENIED`
  /// errors.
  ///
  /// @Snippet(path: "ReachabilityService_SetIamPolicy")
  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.setIamPolicy(request: request, options: options)
  }

  /// Gets the access control policy for a resource. Returns an empty policy
  /// if the resource exists and does not have a policy set.
  ///
  /// @Snippet(path: "ReachabilityService_GetIamPolicy")
  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.getIamPolicy(request: request, options: options)
  }

  /// Returns permissions that a caller has on the specified resource. If the
  /// resource does not exist, this will return an empty set of
  /// permissions, not a `NOT_FOUND` error.
  ///
  /// Note: This operation is designed to be used for building
  /// permission-aware UIs and command-line tools, not for authorization
  /// checking. This operation may "fail open" without warning.
  ///
  /// @Snippet(path: "ReachabilityService_TestIamPermissions")
  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    try await self.inner.testIamPermissions(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "ReachabilityService_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "ReachabilityService_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "ReachabilityService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "ReachabilityService_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "ReachabilityService_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `ReachabilityServiceClient`.
  ///
  /// To mock `ReachabilityServiceClient` change your functions to receive
  /// `some ReachabilityServiceProtocol` or `any ReachabilityServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol ReachabilityServiceProtocol {
    /// See `ReachabilityServiceClient.listConnectivityTests`.
    func listConnectivityTests(request: ListConnectivityTestsRequest) async throws
      -> GoogleCloudNetworkManagementV1.ListConnectivityTestsResponse

    /// See `ReachabilityServiceClient.listConnectivityTests`.
    func listConnectivityTests(
      byItem: ListConnectivityTestsRequest
    ) throws -> any AsyncSequence<ConnectivityTest, Swift.Error>

    /// See `ReachabilityServiceClient.listConnectivityTests`.
    func listConnectivityTests(
      parent: Swift.String,
    ) throws -> any AsyncSequence<ConnectivityTest, Swift.Error>

    /// See `ReachabilityServiceClient.getConnectivityTest`.
    func getConnectivityTest(request: GetConnectivityTestRequest) async throws
      -> GoogleCloudNetworkManagementV1.ConnectivityTest

    /// See `ReachabilityServiceClient.getConnectivityTest`.
    func getConnectivityTest(
      name: Swift.String,
    ) async throws -> GoogleCloudNetworkManagementV1.ConnectivityTest

    /// See `ReachabilityServiceClient.createConnectivityTest`.
    func createConnectivityTest(request: CreateConnectivityTestRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `ReachabilityServiceClient.createConnectivityTest`.
    func createConnectivityTest(withPolling: CreateConnectivityTestRequest) async throws
      -> any GoogleCloudGax.PollableOperation<ConnectivityTest>

    /// See `ReachabilityServiceClient.createConnectivityTest`.
    func createConnectivityTest(
      parent: Swift.String,
      testId: Swift.String,
      resource: ConnectivityTest?,
    ) async throws -> any GoogleCloudGax.PollableOperation<ConnectivityTest>

    /// See `ReachabilityServiceClient.updateConnectivityTest`.
    func updateConnectivityTest(request: UpdateConnectivityTestRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `ReachabilityServiceClient.updateConnectivityTest`.
    func updateConnectivityTest(withPolling: UpdateConnectivityTestRequest) async throws
      -> any GoogleCloudGax.PollableOperation<ConnectivityTest>

    /// See `ReachabilityServiceClient.updateConnectivityTest`.
    func updateConnectivityTest(
      updateMask: GoogleCloudWkt.FieldMask?,
      resource: ConnectivityTest?,
    ) async throws -> any GoogleCloudGax.PollableOperation<ConnectivityTest>

    /// See `ReachabilityServiceClient.rerunConnectivityTest`.
    func rerunConnectivityTest(request: RerunConnectivityTestRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `ReachabilityServiceClient.rerunConnectivityTest`.
    func rerunConnectivityTest(withPolling: RerunConnectivityTestRequest) async throws
      -> any GoogleCloudGax.PollableOperation<ConnectivityTest>

    /// See `ReachabilityServiceClient.deleteConnectivityTest`.
    func deleteConnectivityTest(request: DeleteConnectivityTestRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `ReachabilityServiceClient.deleteConnectivityTest`.
    func deleteConnectivityTest(withPolling: DeleteConnectivityTestRequest) async throws
      -> any GoogleCloudGax.PollableOperation<Void>

    /// See `ReachabilityServiceClient.deleteConnectivityTest`.
    func deleteConnectivityTest(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `ReachabilityServiceClient.listLocations`.
    func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse

    /// See `ReachabilityServiceClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `ReachabilityServiceClient.getLocation`.
    func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location

    /// See `ReachabilityServiceClient.setIamPolicy`.
    func setIamPolicy(request: GoogleIAMV1.SetIamPolicyRequest) async throws -> GoogleIAMV1.Policy

    /// See `ReachabilityServiceClient.getIamPolicy`.
    func getIamPolicy(request: GoogleIAMV1.GetIamPolicyRequest) async throws -> GoogleIAMV1.Policy

    /// See `ReachabilityServiceClient.testIamPermissions`.
    func testIamPermissions(request: GoogleIAMV1.TestIamPermissionsRequest) async throws
      -> GoogleIAMV1.TestIamPermissionsResponse

    /// See `ReachabilityServiceClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `ReachabilityServiceClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `ReachabilityServiceClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `ReachabilityServiceClient.deleteOperation`.
    func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws

    /// See `ReachabilityServiceClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `ReachabilityServiceClient.cancelOperation`.
    func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

    /// See `ReachabilityServiceClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `ReachabilityServiceClient.listConnectivityTests`.
    func listConnectivityTests(
      request: ListConnectivityTestsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkManagementV1.ListConnectivityTestsResponse

    /// See `ReachabilityServiceClient.listConnectivityTests`.
    func listConnectivityTests(
      byItem: ListConnectivityTestsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<ConnectivityTest, Swift.Error>

    /// See `ReachabilityServiceClient.getConnectivityTest`.
    func getConnectivityTest(
      request: GetConnectivityTestRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkManagementV1.ConnectivityTest

    /// See `ReachabilityServiceClient.createConnectivityTest`.
    func createConnectivityTest(
      request: CreateConnectivityTestRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ReachabilityServiceClient.createConnectivityTest`.
    func createConnectivityTest(
      withPolling: CreateConnectivityTestRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<ConnectivityTest>

    /// See `ReachabilityServiceClient.updateConnectivityTest`.
    func updateConnectivityTest(
      request: UpdateConnectivityTestRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ReachabilityServiceClient.updateConnectivityTest`.
    func updateConnectivityTest(
      withPolling: UpdateConnectivityTestRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<ConnectivityTest>

    /// See `ReachabilityServiceClient.rerunConnectivityTest`.
    func rerunConnectivityTest(
      request: RerunConnectivityTestRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ReachabilityServiceClient.rerunConnectivityTest`.
    func rerunConnectivityTest(
      withPolling: RerunConnectivityTestRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<ConnectivityTest>

    /// See `ReachabilityServiceClient.deleteConnectivityTest`.
    func deleteConnectivityTest(
      request: DeleteConnectivityTestRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ReachabilityServiceClient.deleteConnectivityTest`.
    func deleteConnectivityTest(
      withPolling: DeleteConnectivityTestRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `ReachabilityServiceClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `ReachabilityServiceClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `ReachabilityServiceClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `ReachabilityServiceClient.setIamPolicy`.
    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `ReachabilityServiceClient.getIamPolicy`.
    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `ReachabilityServiceClient.testIamPermissions`.
    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    /// See `ReachabilityServiceClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `ReachabilityServiceClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `ReachabilityServiceClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `ReachabilityServiceClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.ReachabilityServiceProtocol {
  public func listConnectivityTests(request: ListConnectivityTestsRequest) async throws
    -> GoogleCloudNetworkManagementV1.ListConnectivityTestsResponse
  {
    try await self.listConnectivityTests(request: request, options: .init())
  }

  public func listConnectivityTests(
    request: ListConnectivityTestsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudNetworkManagementV1.ListConnectivityTestsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listConnectivityTests(
    byItem: ListConnectivityTestsRequest
  ) throws -> any AsyncSequence<ConnectivityTest, Swift.Error> {
    try self.listConnectivityTests(byItem: byItem, options: .init())
  }

  public func listConnectivityTests(
    byItem: ListConnectivityTestsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ConnectivityTest, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudNetworkManagementV1.ListConnectivityTestsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listConnectivityTests(
    parent: Swift.String,
  ) throws -> any AsyncSequence<ConnectivityTest, Swift.Error> {
    let request = ListConnectivityTestsRequest().with {
      $0.parent = parent
    }
    return try self.listConnectivityTests(byItem: request)
  }

  public func getConnectivityTest(request: GetConnectivityTestRequest) async throws
    -> GoogleCloudNetworkManagementV1.ConnectivityTest
  {
    try await self.getConnectivityTest(request: request, options: .init())
  }

  public func getConnectivityTest(
    request: GetConnectivityTestRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudNetworkManagementV1.ConnectivityTest {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getConnectivityTest(
    name: Swift.String,
  ) async throws -> GoogleCloudNetworkManagementV1.ConnectivityTest {
    let request = GetConnectivityTestRequest().with {
      $0.name = name
    }
    return try await self.getConnectivityTest(request: request)
  }

  public func createConnectivityTest(request: CreateConnectivityTestRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createConnectivityTest(request: request, options: .init())
  }

  public func createConnectivityTest(
    request: CreateConnectivityTestRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createConnectivityTest(withPolling: CreateConnectivityTestRequest) async throws
    -> any GoogleCloudGax.PollableOperation<ConnectivityTest>
  {
    try await self.createConnectivityTest(withPolling: withPolling, options: .init())
  }

  public func createConnectivityTest(
    withPolling: CreateConnectivityTestRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<ConnectivityTest> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<ConnectivityTest>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createConnectivityTest(
    parent: Swift.String,
    testId: Swift.String,
    resource: ConnectivityTest?,
  ) async throws -> any GoogleCloudGax.PollableOperation<ConnectivityTest> {
    let request = CreateConnectivityTestRequest().with {
      $0.parent = parent
      $0.testId = testId
      $0.resource = resource
    }
    return try await self.createConnectivityTest(withPolling: request)
  }

  public func updateConnectivityTest(request: UpdateConnectivityTestRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateConnectivityTest(request: request, options: .init())
  }

  public func updateConnectivityTest(
    request: UpdateConnectivityTestRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateConnectivityTest(withPolling: UpdateConnectivityTestRequest) async throws
    -> any GoogleCloudGax.PollableOperation<ConnectivityTest>
  {
    try await self.updateConnectivityTest(withPolling: withPolling, options: .init())
  }

  public func updateConnectivityTest(
    withPolling: UpdateConnectivityTestRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<ConnectivityTest> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<ConnectivityTest>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateConnectivityTest(
    updateMask: GoogleCloudWkt.FieldMask?,
    resource: ConnectivityTest?,
  ) async throws -> any GoogleCloudGax.PollableOperation<ConnectivityTest> {
    let request = UpdateConnectivityTestRequest().with {
      $0.updateMask = updateMask
      $0.resource = resource
    }
    return try await self.updateConnectivityTest(withPolling: request)
  }

  public func rerunConnectivityTest(request: RerunConnectivityTestRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.rerunConnectivityTest(request: request, options: .init())
  }

  public func rerunConnectivityTest(
    request: RerunConnectivityTestRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func rerunConnectivityTest(withPolling: RerunConnectivityTestRequest) async throws
    -> any GoogleCloudGax.PollableOperation<ConnectivityTest>
  {
    try await self.rerunConnectivityTest(withPolling: withPolling, options: .init())
  }

  public func rerunConnectivityTest(
    withPolling: RerunConnectivityTestRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<ConnectivityTest> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<ConnectivityTest>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteConnectivityTest(request: DeleteConnectivityTestRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteConnectivityTest(request: request, options: .init())
  }

  public func deleteConnectivityTest(
    request: DeleteConnectivityTestRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteConnectivityTest(withPolling: DeleteConnectivityTestRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Void>
  {
    try await self.deleteConnectivityTest(withPolling: withPolling, options: .init())
  }

  public func deleteConnectivityTest(
    withPolling: DeleteConnectivityTestRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteConnectivityTest(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let request = DeleteConnectivityTestRequest().with {
      $0.name = name
    }
    return try await self.deleteConnectivityTest(withPolling: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func setIamPolicy(request: GoogleIAMV1.SetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.setIamPolicy(request: request, options: .init())
  }

  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getIamPolicy(request: GoogleIAMV1.GetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.getIamPolicy(request: request, options: .init())
  }

  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func testIamPermissions(request: GoogleIAMV1.TestIamPermissionsRequest) async throws
    -> GoogleIAMV1.TestIamPermissionsResponse
  {
    try await self.testIamPermissions(request: request, options: .init())
  }

  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
