// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleRpc

/// Results of the configuration analysis from the last run of the test.
public struct ReachabilityDetails: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The overall result of the test's configuration analysis.
  public var result: ReachabilityDetails.Result = ReachabilityDetails.Result()

  /// The time of the configuration analysis.
  public var verifyTime: GoogleCloudWkt.Timestamp? = nil

  /// The details of a failure or a cancellation of reachability analysis.
  public var error: GoogleRpc.Status? = nil

  /// Result may contain a list of traces if a test has multiple possible
  /// paths in the network, such as when destination endpoint is a load balancer
  /// with multiple backends.
  public var traces: [Trace] = []

  /// Initialize a new instance of `ReachabilityDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ReachabilityDetails().with { $0.result = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The overall result of the test's configuration analysis.
  public enum Result: Codable, Equatable, Sendable {
    /// No result was specified.
    case unspecified
    /// Possible scenarios are:
    ///
    /// * The configuration analysis determined that a packet originating from
    ///   the source is expected to reach the destination.
    /// * The analysis didn't complete because the user lacks permission for
    ///   some of the resources in the trace. However, at the time the user's
    ///   permission became insufficient, the trace had been successful so far.
    case reachable
    /// A packet originating from the source is expected to be dropped before
    /// reaching the destination.
    case unreachable
    /// The source and destination endpoints do not uniquely identify
    /// the test location in the network, and the reachability result contains
    /// multiple traces. For some traces, a packet could be delivered, and for
    /// others, it would not be. This result is also assigned to
    /// configuration analysis of return path if on its own it should be
    /// REACHABLE, but configuration analysis of forward path is AMBIGUOUS.
    case ambiguous
    /// The configuration analysis did not complete. Possible reasons are:
    ///
    /// * A permissions error occurred--for example, the user might not have
    ///   read permission for all of the resources named in the test.
    /// * An internal error occurred.
    /// * The analyzer received an invalid or unsupported argument or was unable
    ///   to identify a known endpoint.
    case undetermined
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .reachable: return 1
      case .unreachable: return 2
      case .ambiguous: return 4
      case .undetermined: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "RESULT_UNSPECIFIED"
      case .reachable: return "REACHABLE"
      case .unreachable: return "UNREACHABLE"
      case .ambiguous: return "AMBIGUOUS"
      case .undetermined: return "UNDETERMINED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Result/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "RESULT_UNSPECIFIED": self = .unspecified
      case "REACHABLE": self = .reachable
      case "UNREACHABLE": self = .unreachable
      case "AMBIGUOUS": self = .ambiguous
      case "UNDETERMINED": self = .undetermined
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Result/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .reachable
      case 2: self = .unreachable
      case 4: self = .ambiguous
      case 5: self = .undetermined
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .reachable: return try container.encode(1)
      case .unreachable: return try container.encode(2)
      case .ambiguous: return try container.encode(4)
      case .undetermined: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkmanagement.v1.ReachabilityDetails"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
