// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// For display only. Metadata associated with a Redis Cluster.
public struct RedisClusterInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Name of a Redis Cluster.
  public var displayName: Swift.String = Swift.String()

  /// URI of a Redis Cluster in format
  /// "projects/{project_id}/locations/{location}/clusters/{cluster_id}"
  public var uri: Swift.String = Swift.String()

  /// URI of the network containing the Redis Cluster endpoints in format
  /// "projects/{project_id}/global/networks/{network_id}".
  public var networkUri: Swift.String = Swift.String()

  /// Discovery endpoint IP address of a Redis Cluster.
  public var discoveryEndpointIpAddress: Swift.String = Swift.String()

  /// Secondary endpoint IP address of a Redis Cluster.
  public var secondaryEndpointIpAddress: Swift.String = Swift.String()

  /// Name of the region in which the Redis Cluster is defined. For example,
  /// "us-central1".
  public var location: Swift.String = Swift.String()

  /// Initialize a new instance of `RedisClusterInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RedisClusterInfo().with { $0.displayName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkmanagement.v1.RedisClusterInfo"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
