// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// For display only. Metadata associated with a Compute Engine route.
public struct RouteInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Type of route.
  public var routeType: RouteInfo.RouteType = RouteInfo.RouteType()

  /// Type of next hop.
  public var nextHopType: RouteInfo.NextHopType = RouteInfo.NextHopType()

  /// Indicates where route is applicable. Deprecated, routes with NCC_HUB scope
  /// are not included in the trace in new tests.
  @available(*, deprecated)
  public var routeScope: RouteInfo.RouteScope = RouteInfo.RouteScope()

  /// Name of a route.
  public var displayName: Swift.String = Swift.String()

  /// URI of a route. SUBNET, STATIC, PEERING_SUBNET (only for peering network)
  /// and POLICY_BASED routes only.
  public var uri: Swift.String = Swift.String()

  /// Region of the route. DYNAMIC, PEERING_DYNAMIC, POLICY_BASED and ADVERTISED
  /// routes only. If set for POLICY_BASED route, this is a region of VLAN
  /// attachments for Cloud Interconnect the route applies to. If set to "all"
  /// for POLICY_BASED route, the route applies to VLAN attachments of Cloud
  /// Interconnect in all regions.
  public var region: Swift.String = Swift.String()

  /// Destination IP range of the route.
  public var destIpRange: Swift.String = Swift.String()

  /// String type of the next hop of the route (for example, "VPN tunnel").
  /// Deprecated in favor of the next_hop_type and next_hop_uri fields, not used
  /// in new tests.
  @available(*, deprecated)
  public var nextHop: Swift.String = Swift.String()

  /// URI of a VPC network where route is located.
  public var networkUri: Swift.String = Swift.String()

  /// Priority of the route.
  public var priority: Swift.Int32 = Swift.Int32()

  /// Instance tags of the route.
  public var instanceTags: [Swift.String] = []

  /// Source IP address range of the route. POLICY_BASED routes only.
  public var srcIpRange: Swift.String = Swift.String()

  /// Destination port ranges of the route. POLICY_BASED routes only.
  public var destPortRanges: [Swift.String] = []

  /// Source port ranges of the route. POLICY_BASED routes only.
  public var srcPortRanges: [Swift.String] = []

  /// Protocols of the route. POLICY_BASED routes only.
  public var protocols: [Swift.String] = []

  /// URI of the NCC Hub the route is advertised by. PEERING_SUBNET and
  /// PEERING_DYNAMIC routes that are advertised by NCC Hub only.
  public var nccHubUri: Swift.String? = nil

  /// URI of the destination NCC Spoke. PEERING_SUBNET and PEERING_DYNAMIC routes
  /// that are advertised by NCC Hub only.
  public var nccSpokeUri: Swift.String? = nil

  /// For ADVERTISED dynamic routes, the URI of the Cloud Router that advertised
  /// the corresponding IP prefix.
  public var advertisedRouteSourceRouterUri: Swift.String? = nil

  /// For ADVERTISED routes, the URI of their next hop, i.e. the URI of the
  /// hybrid endpoint (VPN tunnel, Interconnect attachment, NCC router appliance)
  /// the advertised prefix is advertised through, or URI of the source peered
  /// network. Deprecated in favor of the next_hop_uri field, not used in new
  /// tests.
  @available(*, deprecated)
  public var advertisedRouteNextHopUri: Swift.String? = nil

  /// URI of the next hop resource.
  public var nextHopUri: Swift.String = Swift.String()

  /// URI of a VPC network where the next hop resource is located.
  public var nextHopNetworkUri: Swift.String = Swift.String()

  /// For PEERING_SUBNET and PEERING_STATIC routes, the URI of the originating
  /// SUBNET/STATIC route.
  public var originatingRouteUri: Swift.String = Swift.String()

  /// For PEERING_SUBNET, PEERING_STATIC and PEERING_DYNAMIC routes, the name of
  /// the originating SUBNET/STATIC/DYNAMIC route.
  public var originatingRouteDisplayName: Swift.String = Swift.String()

  /// For PEERING_SUBNET and PEERING_DYNAMIC routes that are advertised by NCC
  /// Hub, the URI of the corresponding route in NCC Hub's routing table.
  public var nccHubRouteUri: Swift.String = Swift.String()

  /// Initialize a new instance of `RouteInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RouteInfo().with { $0.routeType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Type of route:
  public enum RouteType: Codable, Equatable, Sendable {
    /// Unspecified type. Default value.
    case unspecified
    /// Route is a subnet route automatically created by the system.
    case subnet
    /// Static route created by the user, including the default route to the
    /// internet.
    case `static`
    /// Dynamic route exchanged between BGP peers.
    case `dynamic`
    /// A subnet route received from peering network or NCC Hub.
    case peeringSubnet
    /// A static route received from peering network.
    case peeringStatic
    /// A dynamic route received from peering network or NCC Hub.
    case peeringDynamic
    /// Policy based route.
    case policyBased
    /// Advertised route. Synthetic route which is used to transition from the
    /// StartFromPrivateNetwork state in Connectivity tests.
    case advertised
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .subnet: return 1
      case .`static`: return 2
      case .`dynamic`: return 3
      case .peeringSubnet: return 4
      case .peeringStatic: return 5
      case .peeringDynamic: return 6
      case .policyBased: return 7
      case .advertised: return 101
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ROUTE_TYPE_UNSPECIFIED"
      case .subnet: return "SUBNET"
      case .`static`: return "STATIC"
      case .`dynamic`: return "DYNAMIC"
      case .peeringSubnet: return "PEERING_SUBNET"
      case .peeringStatic: return "PEERING_STATIC"
      case .peeringDynamic: return "PEERING_DYNAMIC"
      case .policyBased: return "POLICY_BASED"
      case .advertised: return "ADVERTISED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:RouteType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ROUTE_TYPE_UNSPECIFIED": self = .unspecified
      case "SUBNET": self = .subnet
      case "STATIC": self = .`static`
      case "DYNAMIC": self = .`dynamic`
      case "PEERING_SUBNET": self = .peeringSubnet
      case "PEERING_STATIC": self = .peeringStatic
      case "PEERING_DYNAMIC": self = .peeringDynamic
      case "POLICY_BASED": self = .policyBased
      case "ADVERTISED": self = .advertised
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:RouteType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .subnet
      case 2: self = .`static`
      case 3: self = .`dynamic`
      case 4: self = .peeringSubnet
      case 5: self = .peeringStatic
      case 6: self = .peeringDynamic
      case 7: self = .policyBased
      case 101: self = .advertised
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .subnet: return try container.encode(1)
      case .`static`: return try container.encode(2)
      case .`dynamic`: return try container.encode(3)
      case .peeringSubnet: return try container.encode(4)
      case .peeringStatic: return try container.encode(5)
      case .peeringDynamic: return try container.encode(6)
      case .policyBased: return try container.encode(7)
      case .advertised: return try container.encode(101)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Type of next hop:
  public enum NextHopType: Codable, Equatable, Sendable {
    /// Unspecified type. Default value.
    case unspecified
    /// Next hop is an IP address.
    case nextHopIp
    /// Next hop is a Compute Engine instance.
    case nextHopInstance
    /// Next hop is a VPC network gateway.
    case nextHopNetwork
    /// Next hop is a peering VPC. This scenario only happens when the user
    /// doesn't have permissions to the project where the next hop resource is
    /// located.
    case nextHopPeering
    /// Next hop is an interconnect.
    case nextHopInterconnect
    /// Next hop is a VPN tunnel.
    case nextHopVpnTunnel
    /// Next hop is a VPN gateway. This scenario only happens when tracing
    /// connectivity from an on-premises network to Google Cloud through a VPN.
    /// The analysis simulates a packet departing from the on-premises network
    /// through a VPN tunnel and arriving at a Cloud VPN gateway.
    case nextHopVpnGateway
    /// Next hop is an internet gateway.
    case nextHopInternetGateway
    /// Next hop is blackhole; that is, the next hop either does not exist or is
    /// unusable.
    case nextHopBlackhole
    /// Next hop is the forwarding rule of an Internal Load Balancer.
    case nextHopIlb
    /// Next hop is a
    /// [router appliance
    /// instance](https://cloud.google.com/network-connectivity/docs/network-connectivity-center/concepts/ra-overview).
    case nextHopRouterAppliance
    /// Next hop is an NCC hub. This scenario only happens when the user doesn't
    /// have permissions to the project where the next hop resource is located.
    case nextHopNccHub
    /// Next hop is Secure Web Proxy Gateway.
    case secureWebProxyGateway
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .nextHopIp: return 1
      case .nextHopInstance: return 2
      case .nextHopNetwork: return 3
      case .nextHopPeering: return 4
      case .nextHopInterconnect: return 5
      case .nextHopVpnTunnel: return 6
      case .nextHopVpnGateway: return 7
      case .nextHopInternetGateway: return 8
      case .nextHopBlackhole: return 9
      case .nextHopIlb: return 10
      case .nextHopRouterAppliance: return 11
      case .nextHopNccHub: return 12
      case .secureWebProxyGateway: return 13
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "NEXT_HOP_TYPE_UNSPECIFIED"
      case .nextHopIp: return "NEXT_HOP_IP"
      case .nextHopInstance: return "NEXT_HOP_INSTANCE"
      case .nextHopNetwork: return "NEXT_HOP_NETWORK"
      case .nextHopPeering: return "NEXT_HOP_PEERING"
      case .nextHopInterconnect: return "NEXT_HOP_INTERCONNECT"
      case .nextHopVpnTunnel: return "NEXT_HOP_VPN_TUNNEL"
      case .nextHopVpnGateway: return "NEXT_HOP_VPN_GATEWAY"
      case .nextHopInternetGateway: return "NEXT_HOP_INTERNET_GATEWAY"
      case .nextHopBlackhole: return "NEXT_HOP_BLACKHOLE"
      case .nextHopIlb: return "NEXT_HOP_ILB"
      case .nextHopRouterAppliance: return "NEXT_HOP_ROUTER_APPLIANCE"
      case .nextHopNccHub: return "NEXT_HOP_NCC_HUB"
      case .secureWebProxyGateway: return "SECURE_WEB_PROXY_GATEWAY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:NextHopType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "NEXT_HOP_TYPE_UNSPECIFIED": self = .unspecified
      case "NEXT_HOP_IP": self = .nextHopIp
      case "NEXT_HOP_INSTANCE": self = .nextHopInstance
      case "NEXT_HOP_NETWORK": self = .nextHopNetwork
      case "NEXT_HOP_PEERING": self = .nextHopPeering
      case "NEXT_HOP_INTERCONNECT": self = .nextHopInterconnect
      case "NEXT_HOP_VPN_TUNNEL": self = .nextHopVpnTunnel
      case "NEXT_HOP_VPN_GATEWAY": self = .nextHopVpnGateway
      case "NEXT_HOP_INTERNET_GATEWAY": self = .nextHopInternetGateway
      case "NEXT_HOP_BLACKHOLE": self = .nextHopBlackhole
      case "NEXT_HOP_ILB": self = .nextHopIlb
      case "NEXT_HOP_ROUTER_APPLIANCE": self = .nextHopRouterAppliance
      case "NEXT_HOP_NCC_HUB": self = .nextHopNccHub
      case "SECURE_WEB_PROXY_GATEWAY": self = .secureWebProxyGateway
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:NextHopType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .nextHopIp
      case 2: self = .nextHopInstance
      case 3: self = .nextHopNetwork
      case 4: self = .nextHopPeering
      case 5: self = .nextHopInterconnect
      case 6: self = .nextHopVpnTunnel
      case 7: self = .nextHopVpnGateway
      case 8: self = .nextHopInternetGateway
      case 9: self = .nextHopBlackhole
      case 10: self = .nextHopIlb
      case 11: self = .nextHopRouterAppliance
      case 12: self = .nextHopNccHub
      case 13: self = .secureWebProxyGateway
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .nextHopIp: return try container.encode(1)
      case .nextHopInstance: return try container.encode(2)
      case .nextHopNetwork: return try container.encode(3)
      case .nextHopPeering: return try container.encode(4)
      case .nextHopInterconnect: return try container.encode(5)
      case .nextHopVpnTunnel: return try container.encode(6)
      case .nextHopVpnGateway: return try container.encode(7)
      case .nextHopInternetGateway: return try container.encode(8)
      case .nextHopBlackhole: return try container.encode(9)
      case .nextHopIlb: return try container.encode(10)
      case .nextHopRouterAppliance: return try container.encode(11)
      case .nextHopNccHub: return try container.encode(12)
      case .secureWebProxyGateway: return try container.encode(13)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Indicates where routes are applicable.
  public enum RouteScope: Codable, Equatable, Sendable {
    /// Unspecified scope. Default value.
    case unspecified
    /// Route is applicable to packets in Network.
    case network
    /// Route is applicable to packets using NCC Hub's routing table.
    case nccHub
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .network: return 1
      case .nccHub: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ROUTE_SCOPE_UNSPECIFIED"
      case .network: return "NETWORK"
      case .nccHub: return "NCC_HUB"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:RouteScope/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ROUTE_SCOPE_UNSPECIFIED": self = .unspecified
      case "NETWORK": self = .network
      case "NCC_HUB": self = .nccHub
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:RouteScope/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .network
      case 2: self = .nccHub
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .network: return try container.encode(1)
      case .nccHub: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkmanagement.v1.RouteInfo"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
