// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A simulated forwarding path is composed of multiple steps.
/// Each step has a well-defined state and an associated configuration.
public struct Step: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// A description of the step. Usually this is a summary of the state.
  public var description: Swift.String = Swift.String()

  /// Each step is in one of the pre-defined states.
  public var state: Step.State = Step.State()

  /// This is a step that leads to the final state Drop.
  public var causesDrop: Swift.Bool = Swift.Bool()

  /// Project ID that contains the configuration this step is validating.
  public var projectId: Swift.String = Swift.String()

  /// Configuration or metadata associated with each step.
  /// The configuration is filtered based on viewer's permission. If a viewer
  /// has no permission to view the configuration in this step, for non-final
  /// states a special state is populated (VIEWER_PERMISSION_MISSING), and for
  /// final state the configuration is cleared.
  public var stepInfo: OneOf_StepInfo? = nil

  /// Initialize a new instance of `Step`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Step().with { $0.description = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case description = "description"
    case state = "state"
    case causesDrop = "causesDrop"
    case projectId = "projectId"
    case instance = "instance"
    case firewall = "firewall"
    case route = "route"
    case endpoint = "endpoint"
    case googleService = "googleService"
    case forwardingRule = "forwardingRule"
    case hybridSubnet = "hybridSubnet"
    case vpnGateway = "vpnGateway"
    case vpnTunnel = "vpnTunnel"
    case interconnectAttachment = "interconnectAttachment"
    case vpcConnector = "vpcConnector"
    case directVpcEgressConnection = "directVpcEgressConnection"
    case serverlessExternalConnection = "serverlessExternalConnection"
    case deliver = "deliver"
    case forward = "forward"
    case abort = "abort"
    case drop = "drop"
    case loadBalancer = "loadBalancer"
    case network = "network"
    case gkeMaster = "gkeMaster"
    case gkePod = "gkePod"
    case ipMasqueradingSkipped = "ipMasqueradingSkipped"
    case gkeNetworkPolicy = "gkeNetworkPolicy"
    case gkeNetworkPolicySkipped = "gkeNetworkPolicySkipped"
    case cloudSqlInstance = "cloudSqlInstance"
    case redisInstance = "redisInstance"
    case redisCluster = "redisCluster"
    case cloudFunction = "cloudFunction"
    case appEngineVersion = "appEngineVersion"
    case cloudRunRevision = "cloudRunRevision"
    case cloudRunJob = "cloudRunJob"
    case nat = "nat"
    case proxyConnection = "proxyConnection"
    case loadBalancerBackendInfo = "loadBalancerBackendInfo"
    case storageBucket = "storageBucket"
    case serverlessNeg = "serverlessNeg"
    case ngfwPacketInspection = "ngfwPacketInspection"
    case dmsPrivateConnection = "dmsPrivateConnection"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.description = try container.decode(Swift.String.self, forKey: .description)
    self.state = try container.decode(Step.State.self, forKey: .state)
    self.causesDrop = try container.decode(Swift.Bool.self, forKey: .causesDrop)
    self.projectId = try container.decode(Swift.String.self, forKey: .projectId)

    var stepInfo: OneOf_StepInfo? = nil
    let stepInfoCheckAndSet = {
      if stepInfo != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'stepInfo'"))
      }
      stepInfo = $0
    }
    if let instance = try container.decodeIfPresent(InstanceInfo?.self, forKey: .instance) {
      try stepInfoCheckAndSet(.instance(instance))
    }
    if let firewall = try container.decodeIfPresent(FirewallInfo?.self, forKey: .firewall) {
      try stepInfoCheckAndSet(.firewall(firewall))
    }
    if let route = try container.decodeIfPresent(RouteInfo?.self, forKey: .route) {
      try stepInfoCheckAndSet(.route(route))
    }
    if let endpoint = try container.decodeIfPresent(EndpointInfo?.self, forKey: .endpoint) {
      try stepInfoCheckAndSet(.endpoint(endpoint))
    }
    if let googleService = try container.decodeIfPresent(
      GoogleServiceInfo?.self, forKey: .googleService)
    {
      try stepInfoCheckAndSet(.googleService(googleService))
    }
    if let forwardingRule = try container.decodeIfPresent(
      ForwardingRuleInfo?.self, forKey: .forwardingRule)
    {
      try stepInfoCheckAndSet(.forwardingRule(forwardingRule))
    }
    if let hybridSubnet = try container.decodeIfPresent(
      HybridSubnetInfo?.self, forKey: .hybridSubnet)
    {
      try stepInfoCheckAndSet(.hybridSubnet(hybridSubnet))
    }
    if let vpnGateway = try container.decodeIfPresent(VpnGatewayInfo?.self, forKey: .vpnGateway) {
      try stepInfoCheckAndSet(.vpnGateway(vpnGateway))
    }
    if let vpnTunnel = try container.decodeIfPresent(VpnTunnelInfo?.self, forKey: .vpnTunnel) {
      try stepInfoCheckAndSet(.vpnTunnel(vpnTunnel))
    }
    if let interconnectAttachment = try container.decodeIfPresent(
      InterconnectAttachmentInfo?.self, forKey: .interconnectAttachment)
    {
      try stepInfoCheckAndSet(.interconnectAttachment(interconnectAttachment))
    }
    if let vpcConnector = try container.decodeIfPresent(
      VpcConnectorInfo?.self, forKey: .vpcConnector)
    {
      try stepInfoCheckAndSet(.vpcConnector(vpcConnector))
    }
    if let directVpcEgressConnection = try container.decodeIfPresent(
      DirectVpcEgressConnectionInfo?.self, forKey: .directVpcEgressConnection)
    {
      try stepInfoCheckAndSet(.directVpcEgressConnection(directVpcEgressConnection))
    }
    if let serverlessExternalConnection = try container.decodeIfPresent(
      ServerlessExternalConnectionInfo?.self, forKey: .serverlessExternalConnection)
    {
      try stepInfoCheckAndSet(.serverlessExternalConnection(serverlessExternalConnection))
    }
    if let deliver = try container.decodeIfPresent(DeliverInfo?.self, forKey: .deliver) {
      try stepInfoCheckAndSet(.deliver(deliver))
    }
    if let forward = try container.decodeIfPresent(ForwardInfo?.self, forKey: .forward) {
      try stepInfoCheckAndSet(.forward(forward))
    }
    if let abort = try container.decodeIfPresent(AbortInfo?.self, forKey: .abort) {
      try stepInfoCheckAndSet(.abort(abort))
    }
    if let drop = try container.decodeIfPresent(DropInfo?.self, forKey: .drop) {
      try stepInfoCheckAndSet(.drop(drop))
    }
    if let loadBalancer = try container.decodeIfPresent(
      LoadBalancerInfo?.self, forKey: .loadBalancer)
    {
      try stepInfoCheckAndSet(.loadBalancer(loadBalancer))
    }
    if let network = try container.decodeIfPresent(NetworkInfo?.self, forKey: .network) {
      try stepInfoCheckAndSet(.network(network))
    }
    if let gkeMaster = try container.decodeIfPresent(GKEMasterInfo?.self, forKey: .gkeMaster) {
      try stepInfoCheckAndSet(.gkeMaster(gkeMaster))
    }
    if let gkePod = try container.decodeIfPresent(GkePodInfo?.self, forKey: .gkePod) {
      try stepInfoCheckAndSet(.gkePod(gkePod))
    }
    if let ipMasqueradingSkipped = try container.decodeIfPresent(
      IpMasqueradingSkippedInfo?.self, forKey: .ipMasqueradingSkipped)
    {
      try stepInfoCheckAndSet(.ipMasqueradingSkipped(ipMasqueradingSkipped))
    }
    if let gkeNetworkPolicy = try container.decodeIfPresent(
      GkeNetworkPolicyInfo?.self, forKey: .gkeNetworkPolicy)
    {
      try stepInfoCheckAndSet(.gkeNetworkPolicy(gkeNetworkPolicy))
    }
    if let gkeNetworkPolicySkipped = try container.decodeIfPresent(
      GkeNetworkPolicySkippedInfo?.self, forKey: .gkeNetworkPolicySkipped)
    {
      try stepInfoCheckAndSet(.gkeNetworkPolicySkipped(gkeNetworkPolicySkipped))
    }
    if let cloudSqlInstance = try container.decodeIfPresent(
      CloudSQLInstanceInfo?.self, forKey: .cloudSqlInstance)
    {
      try stepInfoCheckAndSet(.cloudSqlInstance(cloudSqlInstance))
    }
    if let redisInstance = try container.decodeIfPresent(
      RedisInstanceInfo?.self, forKey: .redisInstance)
    {
      try stepInfoCheckAndSet(.redisInstance(redisInstance))
    }
    if let redisCluster = try container.decodeIfPresent(
      RedisClusterInfo?.self, forKey: .redisCluster)
    {
      try stepInfoCheckAndSet(.redisCluster(redisCluster))
    }
    if let cloudFunction = try container.decodeIfPresent(
      CloudFunctionInfo?.self, forKey: .cloudFunction)
    {
      try stepInfoCheckAndSet(.cloudFunction(cloudFunction))
    }
    if let appEngineVersion = try container.decodeIfPresent(
      AppEngineVersionInfo?.self, forKey: .appEngineVersion)
    {
      try stepInfoCheckAndSet(.appEngineVersion(appEngineVersion))
    }
    if let cloudRunRevision = try container.decodeIfPresent(
      CloudRunRevisionInfo?.self, forKey: .cloudRunRevision)
    {
      try stepInfoCheckAndSet(.cloudRunRevision(cloudRunRevision))
    }
    if let cloudRunJob = try container.decodeIfPresent(CloudRunJobInfo?.self, forKey: .cloudRunJob)
    {
      try stepInfoCheckAndSet(.cloudRunJob(cloudRunJob))
    }
    if let nat = try container.decodeIfPresent(NatInfo?.self, forKey: .nat) {
      try stepInfoCheckAndSet(.nat(nat))
    }
    if let proxyConnection = try container.decodeIfPresent(
      ProxyConnectionInfo?.self, forKey: .proxyConnection)
    {
      try stepInfoCheckAndSet(.proxyConnection(proxyConnection))
    }
    if let loadBalancerBackendInfo = try container.decodeIfPresent(
      LoadBalancerBackendInfo?.self, forKey: .loadBalancerBackendInfo)
    {
      try stepInfoCheckAndSet(.loadBalancerBackendInfo(loadBalancerBackendInfo))
    }
    if let storageBucket = try container.decodeIfPresent(
      StorageBucketInfo?.self, forKey: .storageBucket)
    {
      try stepInfoCheckAndSet(.storageBucket(storageBucket))
    }
    if let serverlessNeg = try container.decodeIfPresent(
      ServerlessNegInfo?.self, forKey: .serverlessNeg)
    {
      try stepInfoCheckAndSet(.serverlessNeg(serverlessNeg))
    }
    if let ngfwPacketInspection = try container.decodeIfPresent(
      NgfwPacketInspectionInfo?.self, forKey: .ngfwPacketInspection)
    {
      try stepInfoCheckAndSet(.ngfwPacketInspection(ngfwPacketInspection))
    }
    if let dmsPrivateConnection = try container.decodeIfPresent(
      PrivateConnectionInfo?.self, forKey: .dmsPrivateConnection)
    {
      try stepInfoCheckAndSet(.dmsPrivateConnection(dmsPrivateConnection))
    }
    self.stepInfo = stepInfo
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.causesDrop, forKey: .causesDrop)
    try container.encode(self.projectId, forKey: .projectId)

    if let choice = self.stepInfo {
      switch choice {
      case .instance(let value):
        try container.encode(value, forKey: .instance)
      case .firewall(let value):
        try container.encode(value, forKey: .firewall)
      case .route(let value):
        try container.encode(value, forKey: .route)
      case .endpoint(let value):
        try container.encode(value, forKey: .endpoint)
      case .googleService(let value):
        try container.encode(value, forKey: .googleService)
      case .forwardingRule(let value):
        try container.encode(value, forKey: .forwardingRule)
      case .hybridSubnet(let value):
        try container.encode(value, forKey: .hybridSubnet)
      case .vpnGateway(let value):
        try container.encode(value, forKey: .vpnGateway)
      case .vpnTunnel(let value):
        try container.encode(value, forKey: .vpnTunnel)
      case .interconnectAttachment(let value):
        try container.encode(value, forKey: .interconnectAttachment)
      case .vpcConnector(let value):
        try container.encode(value, forKey: .vpcConnector)
      case .directVpcEgressConnection(let value):
        try container.encode(value, forKey: .directVpcEgressConnection)
      case .serverlessExternalConnection(let value):
        try container.encode(value, forKey: .serverlessExternalConnection)
      case .deliver(let value):
        try container.encode(value, forKey: .deliver)
      case .forward(let value):
        try container.encode(value, forKey: .forward)
      case .abort(let value):
        try container.encode(value, forKey: .abort)
      case .drop(let value):
        try container.encode(value, forKey: .drop)
      case .loadBalancer(let value):
        try container.encode(value, forKey: .loadBalancer)
      case .network(let value):
        try container.encode(value, forKey: .network)
      case .gkeMaster(let value):
        try container.encode(value, forKey: .gkeMaster)
      case .gkePod(let value):
        try container.encode(value, forKey: .gkePod)
      case .ipMasqueradingSkipped(let value):
        try container.encode(value, forKey: .ipMasqueradingSkipped)
      case .gkeNetworkPolicy(let value):
        try container.encode(value, forKey: .gkeNetworkPolicy)
      case .gkeNetworkPolicySkipped(let value):
        try container.encode(value, forKey: .gkeNetworkPolicySkipped)
      case .cloudSqlInstance(let value):
        try container.encode(value, forKey: .cloudSqlInstance)
      case .redisInstance(let value):
        try container.encode(value, forKey: .redisInstance)
      case .redisCluster(let value):
        try container.encode(value, forKey: .redisCluster)
      case .cloudFunction(let value):
        try container.encode(value, forKey: .cloudFunction)
      case .appEngineVersion(let value):
        try container.encode(value, forKey: .appEngineVersion)
      case .cloudRunRevision(let value):
        try container.encode(value, forKey: .cloudRunRevision)
      case .cloudRunJob(let value):
        try container.encode(value, forKey: .cloudRunJob)
      case .nat(let value):
        try container.encode(value, forKey: .nat)
      case .proxyConnection(let value):
        try container.encode(value, forKey: .proxyConnection)
      case .loadBalancerBackendInfo(let value):
        try container.encode(value, forKey: .loadBalancerBackendInfo)
      case .storageBucket(let value):
        try container.encode(value, forKey: .storageBucket)
      case .serverlessNeg(let value):
        try container.encode(value, forKey: .serverlessNeg)
      case .ngfwPacketInspection(let value):
        try container.encode(value, forKey: .ngfwPacketInspection)
      case .dmsPrivateConnection(let value):
        try container.encode(value, forKey: .dmsPrivateConnection)
      }
    }
  }

  /// Type of states that are defined in the network state machine.
  /// Each step in the packet trace is in a specific state.
  public enum State: Codable, Equatable, Sendable {
    /// Unspecified state.
    case unspecified
    /// Initial state: packet originating from a Compute Engine instance.
    /// An InstanceInfo is populated with starting instance information.
    case startFromInstance
    /// Initial state: packet originating from the internet.
    /// The endpoint information is populated.
    case startFromInternet
    /// Initial state: packet originating from a VPC or on-premises network
    /// with internal source IP.
    /// If the source is a VPC network visible to the user, a NetworkInfo
    /// is populated with details of the network.
    case startFromPrivateNetwork
    /// Config checking state: verify ingress firewall rule.
    case applyIngressFirewallRule
    /// Config checking state: verify egress firewall rule.
    case applyEgressFirewallRule
    /// Config checking state: verify route.
    case applyRoute
    /// Config checking state: match forwarding rule.
    case applyForwardingRule
    /// Config checking state: packet sent or received under foreign IP
    /// address and allowed.
    case spoofingApproved
    /// Forwarding state: arriving at a Compute Engine instance.
    case arriveAtInstance
    /// Forwarding state: arriving at a Compute Engine internal load balancer.
    @available(*, deprecated)
    case arriveAtInternalLoadBalancer
    /// Forwarding state: arriving at a Compute Engine external load balancer.
    @available(*, deprecated)
    case arriveAtExternalLoadBalancer
    /// Forwarding state: arriving at a Cloud VPN gateway.
    case arriveAtVpnGateway
    /// Forwarding state: arriving at a Cloud VPN tunnel.
    case arriveAtVpnTunnel
    /// Transition state: packet header translated. The `nat` field is populated
    /// with the translation information.
    case nat
    /// Transition state: original connection is terminated and a new proxied
    /// connection is initiated.
    case proxyConnection
    /// Final state: packet could be delivered.
    case deliver
    /// Final state: packet could be dropped.
    case drop
    /// Final state: packet could be forwarded to a network with an unknown
    /// configuration.
    case forward
    /// Final state: analysis is aborted.
    case abort
    /// Special state: viewer of the test result does not have permission to
    /// see the configuration in this step.
    case viewerPermissionMissing
    /// Initial state: packet originating from a Google Kubernetes Engine cluster
    /// master. A GKEMasterInfo is populated with starting instance information.
    case startFromGkeMaster
    /// Initial state: packet originating from a Cloud SQL instance.
    /// A CloudSQLInstanceInfo is populated with starting instance information.
    case startFromCloudSqlInstance
    /// Initial state: packet originating from a Cloud Function.
    /// A CloudFunctionInfo is populated with starting function information.
    case startFromCloudFunction
    /// Forwarding state: arriving at a VPC connector.
    case arriveAtVpcConnector
    /// Initial state: packet originating from an App Engine service version.
    /// An AppEngineVersionInfo is populated with starting version information.
    case startFromAppEngineVersion
    /// Initial state: packet originating from a Cloud Run revision.
    /// A CloudRunRevisionInfo is populated with starting revision information.
    case startFromCloudRunRevision
    /// Initial state: packet originating from a Google service.
    /// The google_service information is populated.
    case startFromGoogleService
    /// Config checking state: verify load balancer backend configuration.
    case analyzeLoadBalancerBackend
    /// Initial state: packet originating from a Storage Bucket. Used only for
    /// return traces.
    /// The storage_bucket information is populated.
    case startFromStorageBucket
    /// Initial state: packet originating from a published service that uses
    /// Private Service Connect. Used only for return traces.
    case startFromPscPublishedService
    /// Initial state: packet originating from a serverless network endpoint
    /// group backend. Used only for return traces.
    /// The serverless_neg information is populated.
    case startFromServerlessNeg
    /// Initial state: packet originating from a Redis instance.
    /// A RedisInstanceInfo is populated with starting instance information.
    case startFromRedisInstance
    /// Initial state: packet originating from a Redis Cluster.
    /// A RedisClusterInfo is populated with starting Cluster information.
    case startFromRedisCluster
    /// Forwarding state: for packets originating from a serverless endpoint
    /// forwarded through Direct VPC egress.
    case directVpcEgressConnection
    /// Forwarding state: for packets originating from a serverless endpoint
    /// forwarded through public (external) connectivity.
    case serverlessExternalConnection
    /// Forwarding state: arriving at an interconnect attachment.
    case arriveAtInterconnectAttachment
    /// Forwarding state: arriving at a hybrid subnet. Appropriate routing
    /// configuration will be determined here.
    case arriveAtHybridSubnet
    /// Initial state: packet originating from a Google Kubernetes Engine Pod.
    /// A GkePodInfo is populated with starting Pod information.
    case startFromGkePod
    /// Transition state: GKE Pod IP masquerading is skipped. The
    /// `ip_masquerading_skipped` field is populated with the reason.
    case skipGkePodIpMasquerading
    /// Transition state: GKE Ingress Network Policy is skipped. The
    /// `gke_network_policy_skipped` field is populated with the reason.
    case skipGkeIngressNetworkPolicy
    /// Transition state: GKE Egress Network Policy is skipped. The
    /// `gke_network_policy_skipped` field is populated with the reason.
    case skipGkeEgressNetworkPolicy
    /// Forwarding state: arriving at a GKE Pod.
    case arriveAtGkePod
    /// Config checking state: verify ingress GKE network policy.
    case applyIngressGkeNetworkPolicy
    /// Config checking state: verify egress GKE network policy.
    case applyEgressGkeNetworkPolicy
    /// Forwarding state: Layer 7 packet inspection by the firewall endpoint
    /// based on the configured security profile group.
    case ngfwPacketInspection
    /// Initial state: packet originating from a DMS Private Connection.
    case startFromDmsPrivateConnection
    /// Initial state: packet originating from a Cloud Run Job.
    /// A CloudRunJobInfo is populated with starting Job information.
    case startFromCloudRunJob
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .startFromInstance: return 1
      case .startFromInternet: return 2
      case .startFromPrivateNetwork: return 3
      case .applyIngressFirewallRule: return 4
      case .applyEgressFirewallRule: return 5
      case .applyRoute: return 6
      case .applyForwardingRule: return 7
      case .spoofingApproved: return 8
      case .arriveAtInstance: return 9
      case .arriveAtInternalLoadBalancer: return 10
      case .arriveAtExternalLoadBalancer: return 11
      case .arriveAtVpnGateway: return 12
      case .arriveAtVpnTunnel: return 13
      case .nat: return 14
      case .proxyConnection: return 15
      case .deliver: return 16
      case .drop: return 17
      case .forward: return 18
      case .abort: return 19
      case .viewerPermissionMissing: return 20
      case .startFromGkeMaster: return 21
      case .startFromCloudSqlInstance: return 22
      case .startFromCloudFunction: return 23
      case .arriveAtVpcConnector: return 24
      case .startFromAppEngineVersion: return 25
      case .startFromCloudRunRevision: return 26
      case .startFromGoogleService: return 27
      case .analyzeLoadBalancerBackend: return 28
      case .startFromStorageBucket: return 29
      case .startFromPscPublishedService: return 30
      case .startFromServerlessNeg: return 31
      case .startFromRedisInstance: return 32
      case .startFromRedisCluster: return 33
      case .directVpcEgressConnection: return 35
      case .serverlessExternalConnection: return 36
      case .arriveAtInterconnectAttachment: return 37
      case .arriveAtHybridSubnet: return 38
      case .startFromGkePod: return 39
      case .skipGkePodIpMasquerading: return 40
      case .skipGkeIngressNetworkPolicy: return 41
      case .skipGkeEgressNetworkPolicy: return 42
      case .arriveAtGkePod: return 44
      case .applyIngressGkeNetworkPolicy: return 45
      case .applyEgressGkeNetworkPolicy: return 46
      case .ngfwPacketInspection: return 47
      case .startFromDmsPrivateConnection: return 48
      case .startFromCloudRunJob: return 50
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .startFromInstance: return "START_FROM_INSTANCE"
      case .startFromInternet: return "START_FROM_INTERNET"
      case .startFromPrivateNetwork: return "START_FROM_PRIVATE_NETWORK"
      case .applyIngressFirewallRule: return "APPLY_INGRESS_FIREWALL_RULE"
      case .applyEgressFirewallRule: return "APPLY_EGRESS_FIREWALL_RULE"
      case .applyRoute: return "APPLY_ROUTE"
      case .applyForwardingRule: return "APPLY_FORWARDING_RULE"
      case .spoofingApproved: return "SPOOFING_APPROVED"
      case .arriveAtInstance: return "ARRIVE_AT_INSTANCE"
      case .arriveAtInternalLoadBalancer: return "ARRIVE_AT_INTERNAL_LOAD_BALANCER"
      case .arriveAtExternalLoadBalancer: return "ARRIVE_AT_EXTERNAL_LOAD_BALANCER"
      case .arriveAtVpnGateway: return "ARRIVE_AT_VPN_GATEWAY"
      case .arriveAtVpnTunnel: return "ARRIVE_AT_VPN_TUNNEL"
      case .nat: return "NAT"
      case .proxyConnection: return "PROXY_CONNECTION"
      case .deliver: return "DELIVER"
      case .drop: return "DROP"
      case .forward: return "FORWARD"
      case .abort: return "ABORT"
      case .viewerPermissionMissing: return "VIEWER_PERMISSION_MISSING"
      case .startFromGkeMaster: return "START_FROM_GKE_MASTER"
      case .startFromCloudSqlInstance: return "START_FROM_CLOUD_SQL_INSTANCE"
      case .startFromCloudFunction: return "START_FROM_CLOUD_FUNCTION"
      case .arriveAtVpcConnector: return "ARRIVE_AT_VPC_CONNECTOR"
      case .startFromAppEngineVersion: return "START_FROM_APP_ENGINE_VERSION"
      case .startFromCloudRunRevision: return "START_FROM_CLOUD_RUN_REVISION"
      case .startFromGoogleService: return "START_FROM_GOOGLE_SERVICE"
      case .analyzeLoadBalancerBackend: return "ANALYZE_LOAD_BALANCER_BACKEND"
      case .startFromStorageBucket: return "START_FROM_STORAGE_BUCKET"
      case .startFromPscPublishedService: return "START_FROM_PSC_PUBLISHED_SERVICE"
      case .startFromServerlessNeg: return "START_FROM_SERVERLESS_NEG"
      case .startFromRedisInstance: return "START_FROM_REDIS_INSTANCE"
      case .startFromRedisCluster: return "START_FROM_REDIS_CLUSTER"
      case .directVpcEgressConnection: return "DIRECT_VPC_EGRESS_CONNECTION"
      case .serverlessExternalConnection: return "SERVERLESS_EXTERNAL_CONNECTION"
      case .arriveAtInterconnectAttachment: return "ARRIVE_AT_INTERCONNECT_ATTACHMENT"
      case .arriveAtHybridSubnet: return "ARRIVE_AT_HYBRID_SUBNET"
      case .startFromGkePod: return "START_FROM_GKE_POD"
      case .skipGkePodIpMasquerading: return "SKIP_GKE_POD_IP_MASQUERADING"
      case .skipGkeIngressNetworkPolicy: return "SKIP_GKE_INGRESS_NETWORK_POLICY"
      case .skipGkeEgressNetworkPolicy: return "SKIP_GKE_EGRESS_NETWORK_POLICY"
      case .arriveAtGkePod: return "ARRIVE_AT_GKE_POD"
      case .applyIngressGkeNetworkPolicy: return "APPLY_INGRESS_GKE_NETWORK_POLICY"
      case .applyEgressGkeNetworkPolicy: return "APPLY_EGRESS_GKE_NETWORK_POLICY"
      case .ngfwPacketInspection: return "NGFW_PACKET_INSPECTION"
      case .startFromDmsPrivateConnection: return "START_FROM_DMS_PRIVATE_CONNECTION"
      case .startFromCloudRunJob: return "START_FROM_CLOUD_RUN_JOB"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "START_FROM_INSTANCE": self = .startFromInstance
      case "START_FROM_INTERNET": self = .startFromInternet
      case "START_FROM_GOOGLE_SERVICE": self = .startFromGoogleService
      case "START_FROM_PRIVATE_NETWORK": self = .startFromPrivateNetwork
      case "START_FROM_GKE_MASTER": self = .startFromGkeMaster
      case "START_FROM_CLOUD_SQL_INSTANCE": self = .startFromCloudSqlInstance
      case "START_FROM_GKE_POD": self = .startFromGkePod
      case "START_FROM_REDIS_INSTANCE": self = .startFromRedisInstance
      case "START_FROM_REDIS_CLUSTER": self = .startFromRedisCluster
      case "START_FROM_CLOUD_FUNCTION": self = .startFromCloudFunction
      case "START_FROM_APP_ENGINE_VERSION": self = .startFromAppEngineVersion
      case "START_FROM_CLOUD_RUN_REVISION": self = .startFromCloudRunRevision
      case "START_FROM_CLOUD_RUN_JOB": self = .startFromCloudRunJob
      case "START_FROM_STORAGE_BUCKET": self = .startFromStorageBucket
      case "START_FROM_PSC_PUBLISHED_SERVICE": self = .startFromPscPublishedService
      case "START_FROM_SERVERLESS_NEG": self = .startFromServerlessNeg
      case "START_FROM_DMS_PRIVATE_CONNECTION": self = .startFromDmsPrivateConnection
      case "APPLY_INGRESS_FIREWALL_RULE": self = .applyIngressFirewallRule
      case "APPLY_EGRESS_FIREWALL_RULE": self = .applyEgressFirewallRule
      case "APPLY_ROUTE": self = .applyRoute
      case "APPLY_FORWARDING_RULE": self = .applyForwardingRule
      case "ANALYZE_LOAD_BALANCER_BACKEND": self = .analyzeLoadBalancerBackend
      case "SPOOFING_APPROVED": self = .spoofingApproved
      case "ARRIVE_AT_INSTANCE": self = .arriveAtInstance
      case "ARRIVE_AT_INTERNAL_LOAD_BALANCER": self = .arriveAtInternalLoadBalancer
      case "ARRIVE_AT_EXTERNAL_LOAD_BALANCER": self = .arriveAtExternalLoadBalancer
      case "ARRIVE_AT_HYBRID_SUBNET": self = .arriveAtHybridSubnet
      case "ARRIVE_AT_VPN_GATEWAY": self = .arriveAtVpnGateway
      case "ARRIVE_AT_VPN_TUNNEL": self = .arriveAtVpnTunnel
      case "ARRIVE_AT_INTERCONNECT_ATTACHMENT": self = .arriveAtInterconnectAttachment
      case "ARRIVE_AT_VPC_CONNECTOR": self = .arriveAtVpcConnector
      case "ARRIVE_AT_GKE_POD": self = .arriveAtGkePod
      case "DIRECT_VPC_EGRESS_CONNECTION": self = .directVpcEgressConnection
      case "SERVERLESS_EXTERNAL_CONNECTION": self = .serverlessExternalConnection
      case "NGFW_PACKET_INSPECTION": self = .ngfwPacketInspection
      case "NAT": self = .nat
      case "SKIP_GKE_POD_IP_MASQUERADING": self = .skipGkePodIpMasquerading
      case "SKIP_GKE_INGRESS_NETWORK_POLICY": self = .skipGkeIngressNetworkPolicy
      case "SKIP_GKE_EGRESS_NETWORK_POLICY": self = .skipGkeEgressNetworkPolicy
      case "APPLY_INGRESS_GKE_NETWORK_POLICY": self = .applyIngressGkeNetworkPolicy
      case "APPLY_EGRESS_GKE_NETWORK_POLICY": self = .applyEgressGkeNetworkPolicy
      case "PROXY_CONNECTION": self = .proxyConnection
      case "DELIVER": self = .deliver
      case "DROP": self = .drop
      case "FORWARD": self = .forward
      case "ABORT": self = .abort
      case "VIEWER_PERMISSION_MISSING": self = .viewerPermissionMissing
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .startFromInstance
      case 2: self = .startFromInternet
      case 3: self = .startFromPrivateNetwork
      case 4: self = .applyIngressFirewallRule
      case 5: self = .applyEgressFirewallRule
      case 6: self = .applyRoute
      case 7: self = .applyForwardingRule
      case 8: self = .spoofingApproved
      case 9: self = .arriveAtInstance
      case 10: self = .arriveAtInternalLoadBalancer
      case 11: self = .arriveAtExternalLoadBalancer
      case 12: self = .arriveAtVpnGateway
      case 13: self = .arriveAtVpnTunnel
      case 14: self = .nat
      case 15: self = .proxyConnection
      case 16: self = .deliver
      case 17: self = .drop
      case 18: self = .forward
      case 19: self = .abort
      case 20: self = .viewerPermissionMissing
      case 21: self = .startFromGkeMaster
      case 22: self = .startFromCloudSqlInstance
      case 23: self = .startFromCloudFunction
      case 24: self = .arriveAtVpcConnector
      case 25: self = .startFromAppEngineVersion
      case 26: self = .startFromCloudRunRevision
      case 27: self = .startFromGoogleService
      case 28: self = .analyzeLoadBalancerBackend
      case 29: self = .startFromStorageBucket
      case 30: self = .startFromPscPublishedService
      case 31: self = .startFromServerlessNeg
      case 32: self = .startFromRedisInstance
      case 33: self = .startFromRedisCluster
      case 35: self = .directVpcEgressConnection
      case 36: self = .serverlessExternalConnection
      case 37: self = .arriveAtInterconnectAttachment
      case 38: self = .arriveAtHybridSubnet
      case 39: self = .startFromGkePod
      case 40: self = .skipGkePodIpMasquerading
      case 41: self = .skipGkeIngressNetworkPolicy
      case 42: self = .skipGkeEgressNetworkPolicy
      case 44: self = .arriveAtGkePod
      case 45: self = .applyIngressGkeNetworkPolicy
      case 46: self = .applyEgressGkeNetworkPolicy
      case 47: self = .ngfwPacketInspection
      case 48: self = .startFromDmsPrivateConnection
      case 50: self = .startFromCloudRunJob
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .startFromInstance: return try container.encode(1)
      case .startFromInternet: return try container.encode(2)
      case .startFromPrivateNetwork: return try container.encode(3)
      case .applyIngressFirewallRule: return try container.encode(4)
      case .applyEgressFirewallRule: return try container.encode(5)
      case .applyRoute: return try container.encode(6)
      case .applyForwardingRule: return try container.encode(7)
      case .spoofingApproved: return try container.encode(8)
      case .arriveAtInstance: return try container.encode(9)
      case .arriveAtInternalLoadBalancer: return try container.encode(10)
      case .arriveAtExternalLoadBalancer: return try container.encode(11)
      case .arriveAtVpnGateway: return try container.encode(12)
      case .arriveAtVpnTunnel: return try container.encode(13)
      case .nat: return try container.encode(14)
      case .proxyConnection: return try container.encode(15)
      case .deliver: return try container.encode(16)
      case .drop: return try container.encode(17)
      case .forward: return try container.encode(18)
      case .abort: return try container.encode(19)
      case .viewerPermissionMissing: return try container.encode(20)
      case .startFromGkeMaster: return try container.encode(21)
      case .startFromCloudSqlInstance: return try container.encode(22)
      case .startFromCloudFunction: return try container.encode(23)
      case .arriveAtVpcConnector: return try container.encode(24)
      case .startFromAppEngineVersion: return try container.encode(25)
      case .startFromCloudRunRevision: return try container.encode(26)
      case .startFromGoogleService: return try container.encode(27)
      case .analyzeLoadBalancerBackend: return try container.encode(28)
      case .startFromStorageBucket: return try container.encode(29)
      case .startFromPscPublishedService: return try container.encode(30)
      case .startFromServerlessNeg: return try container.encode(31)
      case .startFromRedisInstance: return try container.encode(32)
      case .startFromRedisCluster: return try container.encode(33)
      case .directVpcEgressConnection: return try container.encode(35)
      case .serverlessExternalConnection: return try container.encode(36)
      case .arriveAtInterconnectAttachment: return try container.encode(37)
      case .arriveAtHybridSubnet: return try container.encode(38)
      case .startFromGkePod: return try container.encode(39)
      case .skipGkePodIpMasquerading: return try container.encode(40)
      case .skipGkeIngressNetworkPolicy: return try container.encode(41)
      case .skipGkeEgressNetworkPolicy: return try container.encode(42)
      case .arriveAtGkePod: return try container.encode(44)
      case .applyIngressGkeNetworkPolicy: return try container.encode(45)
      case .applyEgressGkeNetworkPolicy: return try container.encode(46)
      case .ngfwPacketInspection: return try container.encode(47)
      case .startFromDmsPrivateConnection: return try container.encode(48)
      case .startFromCloudRunJob: return try container.encode(50)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Configuration or metadata associated with each step.
  /// The configuration is filtered based on viewer's permission. If a viewer
  /// has no permission to view the configuration in this step, for non-final
  /// states a special state is populated (VIEWER_PERMISSION_MISSING), and for
  /// final state the configuration is cleared.
  public enum OneOf_StepInfo: Codable, Equatable, Sendable {
    /// Display information of a Compute Engine instance.
    indirect case instance(InstanceInfo?)
    /// Display information of a Compute Engine firewall rule.
    indirect case firewall(FirewallInfo?)
    /// Display information of a Compute Engine route.
    indirect case route(RouteInfo?)
    /// Display information of the source and destination under analysis.
    /// The endpoint information in an intermediate state may differ with the
    /// initial input, as it might be modified by state like NAT,
    /// or Connection Proxy.
    indirect case endpoint(EndpointInfo?)
    /// Display information of a Google service
    indirect case googleService(GoogleServiceInfo?)
    /// Display information of a Compute Engine forwarding rule.
    indirect case forwardingRule(ForwardingRuleInfo?)
    /// Display information of a hybrid subnet.
    indirect case hybridSubnet(HybridSubnetInfo?)
    /// Display information of a Compute Engine VPN gateway.
    indirect case vpnGateway(VpnGatewayInfo?)
    /// Display information of a Compute Engine VPN tunnel.
    indirect case vpnTunnel(VpnTunnelInfo?)
    /// Display information of an interconnect attachment.
    indirect case interconnectAttachment(InterconnectAttachmentInfo?)
    /// Display information of a VPC connector.
    indirect case vpcConnector(VpcConnectorInfo?)
    /// Display information of a serverless direct VPC egress connection.
    indirect case directVpcEgressConnection(DirectVpcEgressConnectionInfo?)
    /// Display information of a serverless public (external) connection.
    indirect case serverlessExternalConnection(ServerlessExternalConnectionInfo?)
    /// Display information of the final state "deliver" and reason.
    indirect case deliver(DeliverInfo?)
    /// Display information of the final state "forward" and reason.
    indirect case forward(ForwardInfo?)
    /// Display information of the final state "abort" and reason.
    indirect case abort(AbortInfo?)
    /// Display information of the final state "drop" and reason.
    indirect case drop(DropInfo?)
    /// Display information of the load balancers. Deprecated in favor of the
    /// `load_balancer_backend_info` field, not used in new tests.
    @available(*, deprecated)
    indirect case loadBalancer(LoadBalancerInfo?)
    /// Display information of a Google Cloud network.
    indirect case network(NetworkInfo?)
    /// Display information of a Google Kubernetes Engine cluster master.
    indirect case gkeMaster(GKEMasterInfo?)
    /// Display information of a Google Kubernetes Engine Pod.
    indirect case gkePod(GkePodInfo?)
    /// Display information of the reason why GKE Pod IP masquerading was
    /// skipped.
    indirect case ipMasqueradingSkipped(IpMasqueradingSkippedInfo?)
    /// Display information of a GKE Network Policy.
    indirect case gkeNetworkPolicy(GkeNetworkPolicyInfo?)
    /// Display information of the reason why GKE Network Policy evaluation was
    /// skipped.
    indirect case gkeNetworkPolicySkipped(GkeNetworkPolicySkippedInfo?)
    /// Display information of a Cloud SQL instance.
    indirect case cloudSqlInstance(CloudSQLInstanceInfo?)
    /// Display information of a Redis Instance.
    indirect case redisInstance(RedisInstanceInfo?)
    /// Display information of a Redis Cluster.
    indirect case redisCluster(RedisClusterInfo?)
    /// Display information of a Cloud Function.
    indirect case cloudFunction(CloudFunctionInfo?)
    /// Display information of an App Engine service version.
    indirect case appEngineVersion(AppEngineVersionInfo?)
    /// Display information of a Cloud Run revision.
    indirect case cloudRunRevision(CloudRunRevisionInfo?)
    /// Display information of a Cloud Run job.
    indirect case cloudRunJob(CloudRunJobInfo?)
    /// Display information of a NAT.
    indirect case nat(NatInfo?)
    /// Display information of a ProxyConnection.
    indirect case proxyConnection(ProxyConnectionInfo?)
    /// Display information of a specific load balancer backend.
    indirect case loadBalancerBackendInfo(LoadBalancerBackendInfo?)
    /// Display information of a Storage Bucket. Used only for return traces.
    indirect case storageBucket(StorageBucketInfo?)
    /// Display information of a Serverless network endpoint group backend. Used
    /// only for return traces.
    indirect case serverlessNeg(ServerlessNegInfo?)
    /// Display information of a layer 7 packet inspection by the firewall.
    indirect case ngfwPacketInspection(NgfwPacketInspectionInfo?)
    /// Display information of a DMS Private Connection.
    indirect case dmsPrivateConnection(PrivateConnectionInfo?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkmanagement.v1.Step"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
