// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleCloudLocation
@_spi(GoogleCloudInternal) public import GoogleIAMV1
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// The VPC Flow Logs service in the Google Cloud Network Management API provides
/// configurations that generate Flow Logs. The service and the configuration
/// resources created using this service are global.
///
/// @Snippet(path: "VpcFlowLogsServiceQuickstart")
public final class VpcFlowLogsServiceClient: Clients.VpcFlowLogsServiceProtocol, Sendable {
  let inner: any Clients.VpcFlowLogsServiceStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `VpcFlowLogsServiceClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.VpcFlowLogsServiceStub = try Clients.VpcFlowLogsServiceTransport(options)
    inner = Clients.VpcFlowLogsServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.VpcFlowLogsServiceLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists all `VpcFlowLogsConfigs` in a given project.
  ///
  /// @Snippet(path: "VpcFlowLogsService_ListVpcFlowLogsConfigs")
  public func listVpcFlowLogsConfigs(
    request: ListVpcFlowLogsConfigsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkManagementV1.ListVpcFlowLogsConfigsResponse {
    try await self.inner.listVpcFlowLogsConfigs(request: request, options: options)
  }

  /// Gets the details of a specific `VpcFlowLogsConfig`.
  ///
  /// @Snippet(path: "VpcFlowLogsService_GetVpcFlowLogsConfig")
  public func getVpcFlowLogsConfig(
    request: GetVpcFlowLogsConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkManagementV1.VpcFlowLogsConfig {
    try await self.inner.getVpcFlowLogsConfig(request: request, options: options)
  }

  /// Creates a new `VpcFlowLogsConfig`.
  /// If a configuration with the exact same settings already exists (even if the
  /// ID is different), the creation fails.
  /// Notes:
  ///
  ///   1. Creating a configuration with `state=DISABLED` will fail
  ///   2. The following fields are not considered as settings for the purpose
  ///   of the check mentioned above, therefore - creating another configuration
  ///   with the same fields but different values for the following fields will
  ///   fail as well:
  ///       * name
  ///       * create_time
  ///       * update_time
  ///       * labels
  ///       * description
  ///
  /// @Snippet(path: "VpcFlowLogsService_CreateVpcFlowLogsConfig")
  public func createVpcFlowLogsConfig(
    request: CreateVpcFlowLogsConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createVpcFlowLogsConfig(request: request, options: options)
  }

  /// Creates a new `VpcFlowLogsConfig`.
  /// If a configuration with the exact same settings already exists (even if the
  /// ID is different), the creation fails.
  /// Notes:
  ///
  ///   1. Creating a configuration with `state=DISABLED` will fail
  ///   2. The following fields are not considered as settings for the purpose
  ///   of the check mentioned above, therefore - creating another configuration
  ///   with the same fields but different values for the following fields will
  ///   fail as well:
  ///       * name
  ///       * create_time
  ///       * update_time
  ///       * labels
  ///       * description
  ///
  /// @Snippet(path: "VpcFlowLogsService_CreateVpcFlowLogsConfig")
  public func createVpcFlowLogsConfigPollingUntilDone(
    request: CreateVpcFlowLogsConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<VpcFlowLogsConfig> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<VpcFlowLogsConfig>.State in
      return try op._extractStatus(VpcFlowLogsConfig.self)
    }
    let rawOp = try await self.createVpcFlowLogsConfig(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<VpcFlowLogsConfig>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates an existing `VpcFlowLogsConfig`.
  /// If a configuration with the exact same settings already exists (even if the
  /// ID is different), the creation fails.
  /// Notes:
  ///
  ///   1. Updating a configuration with `state=DISABLED` will fail.
  ///   2. The following fields are not considered as settings for the purpose
  ///   of the check mentioned above, therefore - updating another configuration
  ///   with the same fields but different values for the following fields will
  ///   fail as well:
  ///       * name
  ///       * create_time
  ///       * update_time
  ///       * labels
  ///       * description
  ///
  /// @Snippet(path: "VpcFlowLogsService_UpdateVpcFlowLogsConfig")
  public func updateVpcFlowLogsConfig(
    request: UpdateVpcFlowLogsConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateVpcFlowLogsConfig(request: request, options: options)
  }

  /// Updates an existing `VpcFlowLogsConfig`.
  /// If a configuration with the exact same settings already exists (even if the
  /// ID is different), the creation fails.
  /// Notes:
  ///
  ///   1. Updating a configuration with `state=DISABLED` will fail.
  ///   2. The following fields are not considered as settings for the purpose
  ///   of the check mentioned above, therefore - updating another configuration
  ///   with the same fields but different values for the following fields will
  ///   fail as well:
  ///       * name
  ///       * create_time
  ///       * update_time
  ///       * labels
  ///       * description
  ///
  /// @Snippet(path: "VpcFlowLogsService_UpdateVpcFlowLogsConfig")
  public func updateVpcFlowLogsConfigPollingUntilDone(
    request: UpdateVpcFlowLogsConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<VpcFlowLogsConfig> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<VpcFlowLogsConfig>.State in
      return try op._extractStatus(VpcFlowLogsConfig.self)
    }
    let rawOp = try await self.updateVpcFlowLogsConfig(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<VpcFlowLogsConfig>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a specific `VpcFlowLogsConfig`.
  ///
  /// @Snippet(path: "VpcFlowLogsService_DeleteVpcFlowLogsConfig")
  public func deleteVpcFlowLogsConfig(
    request: DeleteVpcFlowLogsConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteVpcFlowLogsConfig(request: request, options: options)
  }

  /// Deletes a specific `VpcFlowLogsConfig`.
  ///
  /// @Snippet(path: "VpcFlowLogsService_DeleteVpcFlowLogsConfig")
  public func deleteVpcFlowLogsConfigPollingUntilDone(
    request: DeleteVpcFlowLogsConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteVpcFlowLogsConfig(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// QueryOrgVpcFlowLogsConfigs returns a list of all organization-level VPC
  /// Flow Logs configurations applicable to the specified project.
  ///
  /// @Snippet(path: "VpcFlowLogsService_QueryOrgVpcFlowLogsConfigs")
  public func queryOrgVpcFlowLogsConfigs(
    request: QueryOrgVpcFlowLogsConfigsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkManagementV1.QueryOrgVpcFlowLogsConfigsResponse {
    try await self.inner.queryOrgVpcFlowLogsConfigs(request: request, options: options)
  }

  /// ShowEffectiveFlowLogsConfigs returns a list of all VPC Flow Logs
  /// configurations applicable to a specified resource.
  ///
  /// @Snippet(path: "VpcFlowLogsService_ShowEffectiveFlowLogsConfigs")
  public func showEffectiveFlowLogsConfigs(
    request: ShowEffectiveFlowLogsConfigsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkManagementV1.ShowEffectiveFlowLogsConfigsResponse {
    try await self.inner.showEffectiveFlowLogsConfigs(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  /// This method can be called in two ways:
  ///
  /// *   **List all public locations:** Use the path `GET /v1/locations`.
  /// *   **List project-visible locations:** Use the path
  /// `GET /v1/projects/{project_id}/locations`. This may include public
  /// locations as well as private or other locations specifically visible
  /// to the project.
  ///
  /// @Snippet(path: "VpcFlowLogsService_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "VpcFlowLogsService_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Sets the access control policy on the specified resource. Replaces
  /// any existing policy.
  ///
  /// Can return `NOT_FOUND`, `INVALID_ARGUMENT`, and `PERMISSION_DENIED`
  /// errors.
  ///
  /// @Snippet(path: "VpcFlowLogsService_SetIamPolicy")
  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.setIamPolicy(request: request, options: options)
  }

  /// Gets the access control policy for a resource. Returns an empty policy
  /// if the resource exists and does not have a policy set.
  ///
  /// @Snippet(path: "VpcFlowLogsService_GetIamPolicy")
  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.getIamPolicy(request: request, options: options)
  }

  /// Returns permissions that a caller has on the specified resource. If the
  /// resource does not exist, this will return an empty set of
  /// permissions, not a `NOT_FOUND` error.
  ///
  /// Note: This operation is designed to be used for building
  /// permission-aware UIs and command-line tools, not for authorization
  /// checking. This operation may "fail open" without warning.
  ///
  /// @Snippet(path: "VpcFlowLogsService_TestIamPermissions")
  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    try await self.inner.testIamPermissions(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "VpcFlowLogsService_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "VpcFlowLogsService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "VpcFlowLogsService_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "VpcFlowLogsService_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `VpcFlowLogsServiceClient`.
  ///
  /// To mock `VpcFlowLogsServiceClient` change your functions to receive
  /// `some VpcFlowLogsServiceProtocol` or `any VpcFlowLogsServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol VpcFlowLogsServiceProtocol: Sendable {
    /// See `VpcFlowLogsServiceClient.createVpcFlowLogsConfig`.
    func createVpcFlowLogsConfigPollingUntilDone(request: CreateVpcFlowLogsConfigRequest)
      async throws -> any GoogleGax.PollableOperation<VpcFlowLogsConfig>

    /// See `VpcFlowLogsServiceClient.createVpcFlowLogsConfig`.
    func createVpcFlowLogsConfigPollingUntilDone(
      parent: Swift.String,
      vpcFlowLogsConfig: VpcFlowLogsConfig?,
      vpcFlowLogsConfigId: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<VpcFlowLogsConfig>

    /// See `VpcFlowLogsServiceClient.updateVpcFlowLogsConfig`.
    func updateVpcFlowLogsConfigPollingUntilDone(request: UpdateVpcFlowLogsConfigRequest)
      async throws -> any GoogleGax.PollableOperation<VpcFlowLogsConfig>

    /// See `VpcFlowLogsServiceClient.updateVpcFlowLogsConfig`.
    func updateVpcFlowLogsConfigPollingUntilDone(
      vpcFlowLogsConfig: VpcFlowLogsConfig?,
      updateMask: GoogleWKT.WKTFieldMask?,
    ) async throws -> any GoogleGax.PollableOperation<VpcFlowLogsConfig>

    /// See `VpcFlowLogsServiceClient.deleteVpcFlowLogsConfig`.
    func deleteVpcFlowLogsConfigPollingUntilDone(request: DeleteVpcFlowLogsConfigRequest)
      async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `VpcFlowLogsServiceClient.deleteVpcFlowLogsConfig`.
    func deleteVpcFlowLogsConfigPollingUntilDone(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `VpcFlowLogsServiceClient.listVpcFlowLogsConfigs`.
    func listVpcFlowLogsConfigs(
      request: ListVpcFlowLogsConfigsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkManagementV1.ListVpcFlowLogsConfigsResponse

    /// See `VpcFlowLogsServiceClient.getVpcFlowLogsConfig`.
    func getVpcFlowLogsConfig(
      request: GetVpcFlowLogsConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkManagementV1.VpcFlowLogsConfig

    /// See `VpcFlowLogsServiceClient.createVpcFlowLogsConfig`.
    func createVpcFlowLogsConfig(
      request: CreateVpcFlowLogsConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `VpcFlowLogsServiceClient.createVpcFlowLogsConfig`.
    func createVpcFlowLogsConfigPollingUntilDone(
      request: CreateVpcFlowLogsConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<VpcFlowLogsConfig>

    /// See `VpcFlowLogsServiceClient.updateVpcFlowLogsConfig`.
    func updateVpcFlowLogsConfig(
      request: UpdateVpcFlowLogsConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `VpcFlowLogsServiceClient.updateVpcFlowLogsConfig`.
    func updateVpcFlowLogsConfigPollingUntilDone(
      request: UpdateVpcFlowLogsConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<VpcFlowLogsConfig>

    /// See `VpcFlowLogsServiceClient.deleteVpcFlowLogsConfig`.
    func deleteVpcFlowLogsConfig(
      request: DeleteVpcFlowLogsConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `VpcFlowLogsServiceClient.deleteVpcFlowLogsConfig`.
    func deleteVpcFlowLogsConfigPollingUntilDone(
      request: DeleteVpcFlowLogsConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `VpcFlowLogsServiceClient.queryOrgVpcFlowLogsConfigs`.
    func queryOrgVpcFlowLogsConfigs(
      request: QueryOrgVpcFlowLogsConfigsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkManagementV1.QueryOrgVpcFlowLogsConfigsResponse

    /// See `VpcFlowLogsServiceClient.showEffectiveFlowLogsConfigs`.
    func showEffectiveFlowLogsConfigs(
      request: ShowEffectiveFlowLogsConfigsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkManagementV1.ShowEffectiveFlowLogsConfigsResponse

    /// See `VpcFlowLogsServiceClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `VpcFlowLogsServiceClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `VpcFlowLogsServiceClient.setIamPolicy`.
    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `VpcFlowLogsServiceClient.getIamPolicy`.
    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `VpcFlowLogsServiceClient.testIamPermissions`.
    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    /// See `VpcFlowLogsServiceClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `VpcFlowLogsServiceClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `VpcFlowLogsServiceClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.VpcFlowLogsServiceProtocol {
  public func listVpcFlowLogsConfigs(request: ListVpcFlowLogsConfigsRequest) async throws
    -> GoogleCloudNetworkManagementV1.ListVpcFlowLogsConfigsResponse
  {
    try await self.listVpcFlowLogsConfigs(request: request, options: .init())
  }

  public func listVpcFlowLogsConfigs(
    request: ListVpcFlowLogsConfigsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkManagementV1.ListVpcFlowLogsConfigsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listVpcFlowLogsConfigsByItems(
    request: ListVpcFlowLogsConfigsRequest
  ) -> any AsyncSequence<VpcFlowLogsConfig, Swift.Error> {
    self.listVpcFlowLogsConfigsByItems(request: request, options: .init())
  }

  /// Lists all `VpcFlowLogsConfigs` in a given project.
  ///
  /// @Snippet(path: "VpcFlowLogsService_ListVpcFlowLogsConfigs")
  public func listVpcFlowLogsConfigsByItems(
    request: ListVpcFlowLogsConfigsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<VpcFlowLogsConfig, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudNetworkManagementV1.ListVpcFlowLogsConfigsResponse in
      var request = request
      request.pageToken = token
      return try await self.listVpcFlowLogsConfigs(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listVpcFlowLogsConfigsByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<VpcFlowLogsConfig, Swift.Error> {
    let request = ListVpcFlowLogsConfigsRequest().with {
      $0.parent = parent
    }
    return self.listVpcFlowLogsConfigsByItems(request: request)
  }

  public func getVpcFlowLogsConfig(request: GetVpcFlowLogsConfigRequest) async throws
    -> GoogleCloudNetworkManagementV1.VpcFlowLogsConfig
  {
    try await self.getVpcFlowLogsConfig(request: request, options: .init())
  }

  public func getVpcFlowLogsConfig(
    request: GetVpcFlowLogsConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkManagementV1.VpcFlowLogsConfig {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getVpcFlowLogsConfig(
    name: Swift.String,
  ) async throws -> GoogleCloudNetworkManagementV1.VpcFlowLogsConfig {
    let request = GetVpcFlowLogsConfigRequest().with {
      $0.name = name
    }
    return try await self.getVpcFlowLogsConfig(request: request)
  }

  public func createVpcFlowLogsConfig(request: CreateVpcFlowLogsConfigRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createVpcFlowLogsConfig(request: request, options: .init())
  }

  public func createVpcFlowLogsConfig(
    request: CreateVpcFlowLogsConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createVpcFlowLogsConfigPollingUntilDone(request: CreateVpcFlowLogsConfigRequest)
    async throws -> any GoogleGax.PollableOperation<VpcFlowLogsConfig>
  {
    try await self.createVpcFlowLogsConfigPollingUntilDone(request: request, options: .init())
  }

  public func createVpcFlowLogsConfigPollingUntilDone(
    request: CreateVpcFlowLogsConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<VpcFlowLogsConfig> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<VpcFlowLogsConfig>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createVpcFlowLogsConfigPollingUntilDone(
    parent: Swift.String,
    vpcFlowLogsConfig: VpcFlowLogsConfig?,
    vpcFlowLogsConfigId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<VpcFlowLogsConfig> {
    let request = CreateVpcFlowLogsConfigRequest().with {
      $0.parent = parent
      $0.vpcFlowLogsConfig = vpcFlowLogsConfig
      $0.vpcFlowLogsConfigId = vpcFlowLogsConfigId
    }
    return try await self.createVpcFlowLogsConfigPollingUntilDone(request: request)
  }

  public func updateVpcFlowLogsConfig(request: UpdateVpcFlowLogsConfigRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateVpcFlowLogsConfig(request: request, options: .init())
  }

  public func updateVpcFlowLogsConfig(
    request: UpdateVpcFlowLogsConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateVpcFlowLogsConfigPollingUntilDone(request: UpdateVpcFlowLogsConfigRequest)
    async throws -> any GoogleGax.PollableOperation<VpcFlowLogsConfig>
  {
    try await self.updateVpcFlowLogsConfigPollingUntilDone(request: request, options: .init())
  }

  public func updateVpcFlowLogsConfigPollingUntilDone(
    request: UpdateVpcFlowLogsConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<VpcFlowLogsConfig> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<VpcFlowLogsConfig>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateVpcFlowLogsConfigPollingUntilDone(
    vpcFlowLogsConfig: VpcFlowLogsConfig?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<VpcFlowLogsConfig> {
    let request = UpdateVpcFlowLogsConfigRequest().with {
      $0.vpcFlowLogsConfig = vpcFlowLogsConfig
      $0.updateMask = updateMask
    }
    return try await self.updateVpcFlowLogsConfigPollingUntilDone(request: request)
  }

  public func deleteVpcFlowLogsConfig(request: DeleteVpcFlowLogsConfigRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteVpcFlowLogsConfig(request: request, options: .init())
  }

  public func deleteVpcFlowLogsConfig(
    request: DeleteVpcFlowLogsConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteVpcFlowLogsConfigPollingUntilDone(request: DeleteVpcFlowLogsConfigRequest)
    async throws -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteVpcFlowLogsConfigPollingUntilDone(request: request, options: .init())
  }

  public func deleteVpcFlowLogsConfigPollingUntilDone(
    request: DeleteVpcFlowLogsConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteVpcFlowLogsConfigPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteVpcFlowLogsConfigRequest().with {
      $0.name = name
    }
    return try await self.deleteVpcFlowLogsConfigPollingUntilDone(request: request)
  }

  public func queryOrgVpcFlowLogsConfigs(request: QueryOrgVpcFlowLogsConfigsRequest) async throws
    -> GoogleCloudNetworkManagementV1.QueryOrgVpcFlowLogsConfigsResponse
  {
    try await self.queryOrgVpcFlowLogsConfigs(request: request, options: .init())
  }

  public func queryOrgVpcFlowLogsConfigs(
    request: QueryOrgVpcFlowLogsConfigsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkManagementV1.QueryOrgVpcFlowLogsConfigsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func queryOrgVpcFlowLogsConfigsByItems(
    request: QueryOrgVpcFlowLogsConfigsRequest
  ) -> any AsyncSequence<VpcFlowLogsConfig, Swift.Error> {
    self.queryOrgVpcFlowLogsConfigsByItems(request: request, options: .init())
  }

  /// QueryOrgVpcFlowLogsConfigs returns a list of all organization-level VPC
  /// Flow Logs configurations applicable to the specified project.
  ///
  /// @Snippet(path: "VpcFlowLogsService_QueryOrgVpcFlowLogsConfigs")
  public func queryOrgVpcFlowLogsConfigsByItems(
    request: QueryOrgVpcFlowLogsConfigsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<VpcFlowLogsConfig, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudNetworkManagementV1.QueryOrgVpcFlowLogsConfigsResponse in
      var request = request
      request.pageToken = token
      return try await self.queryOrgVpcFlowLogsConfigs(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func showEffectiveFlowLogsConfigs(request: ShowEffectiveFlowLogsConfigsRequest)
    async throws -> GoogleCloudNetworkManagementV1.ShowEffectiveFlowLogsConfigsResponse
  {
    try await self.showEffectiveFlowLogsConfigs(request: request, options: .init())
  }

  public func showEffectiveFlowLogsConfigs(
    request: ShowEffectiveFlowLogsConfigsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudNetworkManagementV1.ShowEffectiveFlowLogsConfigsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func showEffectiveFlowLogsConfigsByItems(
    request: ShowEffectiveFlowLogsConfigsRequest
  ) -> any AsyncSequence<EffectiveVpcFlowLogsConfig, Swift.Error> {
    self.showEffectiveFlowLogsConfigsByItems(request: request, options: .init())
  }

  /// ShowEffectiveFlowLogsConfigs returns a list of all VPC Flow Logs
  /// configurations applicable to a specified resource.
  ///
  /// @Snippet(path: "VpcFlowLogsService_ShowEffectiveFlowLogsConfigs")
  public func showEffectiveFlowLogsConfigsByItems(
    request: ShowEffectiveFlowLogsConfigsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<EffectiveVpcFlowLogsConfig, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudNetworkManagementV1.ShowEffectiveFlowLogsConfigsResponse in
      var request = request
      request.pageToken = token
      return try await self.showEffectiveFlowLogsConfigs(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    self.listLocationsByItems(request: request, options: .init())
  }

  /// Lists information about the supported locations for this service.
  /// This method can be called in two ways:
  ///
  /// *   **List all public locations:** Use the path `GET /v1/locations`.
  /// *   **List project-visible locations:** Use the path
  /// `GET /v1/projects/{project_id}/locations`. This may include public
  /// locations as well as private or other locations specifically visible
  /// to the project.
  ///
  /// @Snippet(path: "VpcFlowLogsService_ListLocations")
  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleGax.RequestError.unimplemented
  }

  public func setIamPolicy(request: GoogleIAMV1.SetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.setIamPolicy(request: request, options: .init())
  }

  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getIamPolicy(request: GoogleIAMV1.GetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.getIamPolicy(request: request, options: .init())
  }

  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func testIamPermissions(request: GoogleIAMV1.TestIamPermissionsRequest) async throws
    -> GoogleIAMV1.TestIamPermissionsResponse
  {
    try await self.testIamPermissions(request: request, options: .init())
  }

  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "VpcFlowLogsService_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
