// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// For display only. Metadata associated with a Compute Engine VPN gateway.
public struct VpnGatewayInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Name of a VPN gateway.
  public var displayName: Swift.String = Swift.String()

  /// URI of a VPN gateway.
  public var uri: Swift.String = Swift.String()

  /// URI of a Compute Engine network where the VPN gateway is configured.
  public var networkUri: Swift.String = Swift.String()

  /// IP address of the VPN gateway.
  public var ipAddress: Swift.String = Swift.String()

  /// A VPN tunnel that is associated with this VPN gateway.
  /// There may be multiple VPN tunnels configured on a VPN gateway, and only
  /// the one relevant to the test is displayed.
  public var vpnTunnelUri: Swift.String = Swift.String()

  /// Name of a Google Cloud region where this VPN gateway is configured.
  public var region: Swift.String = Swift.String()

  /// Initialize a new instance of `VpnGatewayInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VpnGatewayInfo().with { $0.displayName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networkmanagement.v1.VpnGatewayInfo"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
